### ISSUE TITLE
Name conflicts with known open-source image optimizer.

### ISSUE THREAD

**Issue by joelkesler** [nystudio107/craft3-imageoptimize#1]
ImageOptim is a well known mac and web based image optimizer built by @pornel . As far as I can tell, the craft-imageoptim plugin is not affiliated with @pornel or his products.

I recommend changing the name (to craft3-imageoptimizer?) to avoid confusion and be a good open-source citizen.

**Comment by khalwat** [comment]
I'm not too sure there will be consumer confusion over a plugin for Craft CMS and a Mac application, but if there ends up being, I'm happy to change the name.

**Comment by pornel** [comment]
If you could change, that would be great. [ImageOptim](https://imageoptim.com) is now not only an app, but also an API used by plugins for various CMS-es. 
There are "some-CMS-ImageOptim" plugins that use the [ImageOptim API](https://imageoptim.com/api), so there is a potential for confusion.

**Comment by khalwat** [comment]
I'm guessing that changing the name to "SharperImage" wouldn't help me much from a naming conflict POV :)

**Comment by khalwat** [comment]
All done, refactored and renamed to: *ImageOptimize*

**Comment by pornel** [comment]
Thank you!
