### ISSUE TITLE
[FR] Ignore SVGs

### ISSUE THREAD

**Issue by stevehurst** [nystudio107/craft3-imageoptimize#100]
Is it possible to ignore SVGs in my ImageOptimize fields? Right now my SVGs are "re-sized" and saved in different folders, but there is no optimization taking place or needed. This will result in more bandwidth used, as different SVGs that are the same size will need to be cached for different screen sizes.

**Comment by khalwat** [comment]
Yeah there is also a request to "ignore animated .gif files" which I think makes sense. So we can generalize it more to "ignore files of this type", I think.

**Comment by khalwat** [comment]
Related: https://github.com/nystudio107/craft-imageoptimize/issues/73

**Comment by stevehurst** [comment]
Ah, good call there as well. Is there some simple template code to detect file type, in the meantime?

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-imageoptimize/commit/97eb6664d67b2e766408cf9cc5dffed966234d8b
