### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by redkrupp** [nystudio107/craft3-imageoptimize#102]
The plugin has stopped working since the latest 3.0.21 craft update.

The images aren't transformed. If upscale is disabled it says  image would be upscaled

it enabled then it says file format is not supported.

Rolling back to the previous craft build solves the problem.

**Comment by simoncox** [comment]
I installed mine 2 days ago 23rd August 2018 - I get an icon saying its optimising in the left-hand Craft menu, then it fails - everytime, thought I had set something up incorrectly - now am not so sure it was me...

![screen shot 2018-08-23 at 23 00 56](https://user-images.githubusercontent.com/90435/44616045-7a6ae800-a840-11e8-9295-a8072d6f4d31.png)
![screen shot 2018-08-23 at 23 04 13](https://user-images.githubusercontent.com/90435/44616044-79d25180-a840-11e8-96e5-3fd0f9f61639.png)

**Comment by khalwat** [comment]
Strange @EmptyStreets I'm not seeing anything in the change list that seems relevant

https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#3021---2018-08-21

I'll have a closer look.

**Comment by simoncox** [comment]
For mine - assuming it's the same issue  - config is set for Imgix. (I have that working).
Plugin version: 1.4.38 - added via plugin store
Craft version: 3.0.21

**Comment by khalwat** [comment]
@simoncox can you post a screenshot of your Imgix settings as set in Image Optimize?

**Comment by khalwat** [comment]
@EmptyStreets So as a test I did the followig:

* Deleted all of my transforms (folders prefixed with an `_` in the public Assets folder)
* Cleared the all the caches in the AdminCP
* Went to the Asset Volume in Settings -> Assets and clicked on **Save**

It properly kicked off the resaving:

<img width="370" alt="google chromescreensnapz217" src="https://user-images.githubusercontent.com/7570798/44620460-a8612400-a862-11e8-8f70-463babbdb485.png">

...and the resulting images seemed fine:

<img width="846" alt="google chromescreensnapz218" src="https://user-images.githubusercontent.com/7570798/44620469-cf1f5a80-a862-11e8-9bd1-0a137dda2ef5.png">

So I'm not sure if this is specific to Craft CMS 3.0.21 or not.

Is there anything in your `storage/logs/craft.log` that might be relevant?

**Comment by khalwat** [comment]
@simoncox I think the issue you're having is likely unrelated to the problem @EmptyStreets is having; I think it's likely to be an Imgix config issue. I'm assuming it works fine if you switch the method back to using Craft transforms?

**Comment by simoncox** [comment]
Here is the screen shot.
![screen shot 2018-08-25 at 18 32 03](https://user-images.githubusercontent.com/90435/44620932-348c3f00-a895-11e8-88fa-887a7372aab7.png)

I have the security token in but am not using it in any settings. I had not set it up using Craft. 
I tried switching the method to Craft - also failed.

FYI: I have set up two sources on imgix. Content images are being driven by your plugin and imgix, and a separate one for the static images I am using in the site that is direct to imgix.
This URL shows both https://simoncox.com/article/swanage-belle 
The banner and the gallery are through ImageOptimize and the boi image of me in the footer is direct to imgix (with src set). Other images on the site are not through imgix yet.

**Comment by khalwat** [comment]
@simoncox can you send me your `storage/logs/craft.log` and `storage/logs/queue.log` to andrew@nystudio107.com ?

Ideally, you'd delete them both, then make the problem happen, then send them immediately.

**Comment by simoncox** [comment]
I have a queue.log but not a craft log in there. Have checked the queue log and found this at the end:

2018-08-25 19:07:34 [86.134.26.205][1][-][error][craft\queue\QueueLogBehavior::afterError]  [226] Optimizing images in Content images (attempt: 1) - Error (time: 125.396s): Unable to compute the color palette of a blank or transparent image.
2018-08-25 19:07:34 [86.134.26.205][1][-][error][RuntimeException] RuntimeException: Unable to compute the color palette of a blank or transparent image. in /vendor/ksubileau/color-thief-php/lib/ColorThief/ColorThief.php:138

Trying again now after turning off the colour palette option.

**Comment by simoncox** [comment]
Yes! that's fixed it. Will send the log anyway.

**Comment by khalwat** [comment]
@simoncox I added a try/catch around ColorThief now to handle empty/transparent images (weird you're making a srcset of such an image tho!) https://github.com/nystudio107/craft-imageoptimize/commit/630f0c844cc37deb881e3cc393e118ea56b325d2

I wasn't even aware it could throw that error.

**Comment by khalwat** [comment]
So yes, this is entirely unrelated to the issue @EmptyStreets is having. Can you try what I outlined above @EmptyStreets ?

**Comment by simoncox** [comment]
Apologies to @emptystreets for the thread hijack - the date was a coincidence.

**Comment by redkrupp** [comment]
Yes, I've already tried that, no luck. Please see the attached file for logs, screenshots etc.
[ny107.zip](https://github.com/nystudio107/craft-imageoptimize/files/2321017/ny107.zip)
