### ISSUE TITLE
1.4.38 Creates Wrong Sizes?

### ISSUE THREAD

**Issue by davidhellmann** [nystudio107/craft3-imageoptimize#103]
My Image Fields have the sizes [200, 400, 800, 1200]
But IO Creates other Sizes

![image](https://user-images.githubusercontent.com/764292/44634561-c2525200-a99b-11e8-91cb-04bc32311f4e.png)

![image](https://user-images.githubusercontent.com/764292/44634563-c67e6f80-a99b-11e8-93d1-686bfb498796.png)

![image](https://user-images.githubusercontent.com/764292/44634571-cd0ce700-a99b-11e8-82da-74bf4234e866.png)

Never defined this sizes.

Try now a downgrade to 1.4.37

**Comment by davidhellmann** [comment]
Here my field
![image](https://user-images.githubusercontent.com/764292/44634651-c0d55980-a99c-11e8-9ac3-be8a123ecea2.png)

1.4.37 same problem. 


the root image is 981px and a png but he creates a 1200 as jpg

**Comment by davidhellmann** [comment]
And the overview images are all broken. just the preview SVG is visible (also in the sourcecode)
https://neubau-eyewear.com/sun

**Comment by davidhellmann** [comment]
ok, looks like 1.4.37 works for now

**Comment by davidhellmann** [comment]
Hm and it looks like then it create the images via command line it dosn't work. Then I go into an entry => open the image => hit save => the image are created fine

**Comment by davidhellmann** [comment]
Downgraded now to 1.4.36 and run creation via CLI.
But now I must go to bed. Write in few hours if that works.

**Comment by redkrupp** [comment]
It is totally related to my issue, [I've] (https://github.com/nystudio107/craft-imageoptimize/issues/102) also downgraded to 1.4.36 and it has started to work. Thanks David :)

**Comment by davidhellmann** [comment]
Weird stuff here.
Looks like one image volume doesn't works. 
When I Upload an image to `product` he creates the images but the srcsets are empty:

```<img class="a-image__image  lazyautosizes lazyloaded" src="" data-srcset="" data-sizes="auto" width="" height="auto" alt="Singular" sizes="87px">```

![image](https://user-images.githubusercontent.com/764292/44648177-84c3e800-a9e0-11e8-9310-2cbabb65c868.png)


I've created a test asset volume and this works fine.

**Comment by khalwat** [comment]
I'm going to have a look at the changes between the versions. To clarify @davidhellmann @EmptyStreets downgrading to 1.4.36 fixes all of your issues, including the CLI image generation?

**Comment by davidhellmann** [comment]
Yes, 1.4.36 works!

**Comment by khalwat** [comment]
This regression should be fixed in 1.4.39, give it a whirl -> https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.39
