### ISSUE TITLE
some optimized images are now working with cloudfront

### ISSUE THREAD

**Issue by daniellefrapp** [nystudio107/craft3-imageoptimize#105]
Hi there, 

I am hoping you can help me figure something out. On our site that has cloudfront in front of it some optimized image are not working. But are working fine when not using cloudfront

 cloudfront:
https://prod-www.cloud.applause.com/blog

non cloudfront:
http://prod-website.cloud.applause.com/blog

What is strange is the hero images are pulling from the same field and are working. 

Here is the working hero image code: 

```
<section class="hero parallax responsive-background" responsive-background-image>

  {% set optimizedImages = entry.blogFeaturedImage.one().optimizedimages %}

  <img src="{{ optimizedImages.src() }}" srcset="{{ optimizedImages.srcset() }}" sizes="100vw" />

  <div class="black-bg">

    <div class="hero-body">

      <h1 class="title txt-white txt-lg txt-uc txt-extra-extrabold">

        {{entry.title}}

      </h1>

    </div>

  </div>

</section>
```

and here is the code that is breaking:

```
	{% set blogImage = entry.blogFeaturedImage.one().optimizedimages %}

	<a href="{{ entry.url }}">

		<img src="{{ blogImage.src()}}" alt="{{entry.seoImageDescription}}" srcset="{{ blogImage.srcsetMaxWidth(768)}}"/>

	</a>
```

and here is what is in my asset field 
![screen shot 2018-09-13 at 3 26 23 pm](https://user-images.githubusercontent.com/33430386/45510864-73f9cd00-b769-11e8-88c0-7adc82523c5e.png)

Can you see anything wrong?

**Comment by khalwat** [comment]
When you say that they are not working... what do you mean exactly?

If it works without CloudFront, but doesn't work with CloudFront, it is most likely some kind of configuration issue with CloudFront. It should work just fine, I've used ImageOptimize + CloudFront on several sites.
