### ISSUE TITLE
OptimizedImages fields not showing up in entries section

### ISSUE THREAD

**Issue by pramod1988** [nystudio107/craft3-imageoptimize#106]
I have added volume & in field layout added that field. When i go to entries of that section where i have added that field showing me message that OptimizedImages fields only work when added to an Asset Volume's layout.
Craft cms veriosn 3.024 and ImageOptimize plugin version 1.4.38.
Why is the field not showing up?

**Comment by khalwat** [comment]
So a [per the documentation](https://github.com/nystudio107/craft-imageoptimize#using-the-optimized-images-field), the **Optimized Images** field should _only_ be added to an Asset Volume's layout. You do not need to, and should not add that field to your Section field layouts.

Please verify for me that after doing so, when you double-click on an Asset, you see a display similar to this:

![Screenshot](https://raw.githubusercontent.com/nystudio107/craft-imageoptimize/v1/resources/screenshots/image-variant-field.png)

c.f.: https://craftcms.stackexchange.com/questions/27715/using-imageoptimize-plugin-not-showing-field-on-entries

**Comment by pramod1988** [comment]
![screen shot 2018-09-17 at 7 06 12 pm](https://user-images.githubusercontent.com/2357085/45626311-d4ac4100-baac-11e8-8bf7-87f354747455.png)
![screen shot 2018-09-17 at 7 05 48 pm](https://user-images.githubusercontent.com/2357085/45626313-d6760480-baac-11e8-92ef-2c3e0a570e9d.png)
![screen shot 2018-09-17 at 7 07 59 pm](https://user-images.githubusercontent.com/2357085/45626379-0f15de00-baad-11e8-9f3f-4d65e19cdfe8.png)

I did the same as you suggested but in asset it is not showing the optimized image variant.

**Comment by khalwat** [comment]
Alright, so what this is telling me is that very likely something isn't set up correctly with your Asset Volumes. Can you post a screenshot of what your asset volume settings are for the asset volume that you added the Optimized Images field to?

Settings -> Assets ->click on the volume in question.

I'm interested in what you have set for **Base URL** and **File System Path**

Also, do you have your `volumes.php` set up at all as per: https://docs.craftcms.com/v3/config/#overriding-volume-settings

**Comment by pramod1988** [comment]
![screen shot 2018-09-17 at 7 20 44 pm](https://user-images.githubusercontent.com/2357085/45627715-299d8680-bab0-11e8-9f5b-78fae2341e13.png)
I have just created volumes.php
ASSET_BASE_URL=http://159.65.157.25/assets
ASSET_BASE_PATH= web/assets

**Comment by khalwat** [comment]
Show me your `general.php` where you define these aliases (you don't need to show me the entire file), and then also your `volumes.php`?

**Comment by pramod1988** [comment]
![screen shot 2018-09-17 at 7 38 24 pm](https://user-images.githubusercontent.com/2357085/45628339-7d5c9f80-bab1-11e8-9e3d-86125d2c0270.png)
![screen shot 2018-09-17 at 7 39 48 pm](https://user-images.githubusercontent.com/2357085/45628341-7f266300-bab1-11e8-85bc-dcd07dfd294b.png)

**Comment by khalwat** [comment]
Alright, looks good, although for your `volumes.php` you probably should use the aliases that you've created. Also I think your multi-environment config in `volumes.php` isn't set up quite right; have a look at: https://docs.craftcms.com/v3/config/environments.html#multi-environment-configs

So it'd look more like:

```
return [

    // All environments
    '*' => [
        'blog' => [
            'path' => '@basePath/img/blog/',
            'url' => '@baseUrl/img/blog/',
        ],
        'clients' => [
            'path' => '@basePath/img/clients/',
            'url' => '@baseUrl/img/clients/',
        ],
        'plugins' => [
            'path' => '@basePath/img/plugins/',
            'url' => '@baseUrl/img/plugins/',
        ],
        'site' => [
            'path' => '@basePath/img/site/',
            'url' => '@baseUrl/img/site/',
        ],
        'users' => [
            'path' => '@basePath/img/users/',
            'url' => '@baseUrl/img/users/',
        ],
    ],

    // Live (production) environment
    'live'  => [
    ],

    // Staging (pre-production) environment
    'staging'  => [
    ],

    // Local (development) environment
    'local'  => [
    ],
];
```

**Comment by khalwat** [comment]
This ended up just being some local config issues with Asset Volumes, and then getting rid of pending stuck Queue jobs. After that, away we go!
