### ISSUE TITLE
Progressive JPGs / Imgix Not Transforming

### ISSUE THREAD

**Issue by AdamChlan** [nystudio107/craft3-imageoptimize#107]
I was wondering if there is a limitation within the plugin that does not allow Progressive JGPs (pjpg) format from Imgix to be transformed/resized.

I'm noticing that I have some images where transforms are not being created, and these images all seem to be returning the pjpg format in my Imgix URL string. I have the format set to auto. 

Here is a screenshot of what I am seeing for these images.

<img width="425" alt="screenshot 2018-09-17 13 04 14" src="https://user-images.githubusercontent.com/757209/45638131-3dc69100-ba7a-11e8-808a-a232216f76b3.png">

**Comment by khalwat** [comment]
hmmmmm. It should be able to... this is how it handles interlaced images:

```
                // Handle interlaced images
                if (property_exists($transform, 'interlace')) {
                    if (($transform->interlace != 'none')
                        && (!empty($params['fm']))
                        && ($params['fm'] == 'jpg')
                    ) {
                        $params['fm'] = 'pjpg';
                    }
                }
```

**Comment by khalwat** [comment]
How can I attempt to replicate this?

**Comment by MikeMcChillin** [comment]
Also running into issues using Imgix with v `1.4.38`. In my case, all images show "image would be upscaled" even if they are large enough to transform without upscaling. Downgrading to `1.4.36` fixes for me (fix found via #103). To reproduce issues, I had the following settings:

General Settings:
- Imgix security token filled out
- Create Color Palette checked

ImageOptim Field Settings:
- Display Optimized Image Variants checked
- Display Dominant Color Palette checked
- Enforce Aspect Ratio checked
- 2x Retina Sizes checked
- Image Format set to "Auto"

![screen shot 2018-09-25 at 3 24 24 pm](https://user-images.githubusercontent.com/872219/46040944-413fc500-c0d7-11e8-8c7c-37171dac5125.png)
^ Image is 5000px wide, trying to be transformed into 704px with retina checked.

**Comment by khalwat** [comment]
Can you try downgrading to `1.4.37` and see if that's still working for you? Trying to narrow this down, @AdamChlan

**Comment by khalwat** [comment]
This regression should be fixed in 1.4.39, give it a whirl -> https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.39

**Comment by MikeMcChillin** [comment]
Just here to confirm the `1.439` release fixed my issue. Thank you!

**Comment by AdamChlan** [comment]
I'll be testing a bit later this week, and will report back.

**Comment by khalwat** [comment]
Cool @AdamChlan lmk!

**Comment by AdamChlan** [comment]
Finally got around to updating, and this indeed fixed the issue. Thank you!

**Comment by khalwat** [comment]
Thanks for letting me know!
