### ISSUE TITLE
Transform images like Crafts ”Stretch” mode instead of cropping

### ISSUE THREAD

**Issue by slebbo** [nystudio107/craft3-imageoptimize#11]
It would be great if one could have the option of not crop the image, and only stretch it proportionally after a desired width or height, like Crafts native ”Stretch” mode. If I understood how this plugin is working, one will need to set up an Asset Source each per image format, quite often we use mixed images of 4:3, 1:1, 16:9,9:16 etc which will make us end up with a lot of Asset Sources.

**Comment by khalwat** [comment]
Well, each Image Variant can be a different aspect ratio, so you wouldn't have to create a new asset source for each one, unless I'm misunderstanding you?

As for the stretch mode, if you proportionally stretch something, wouldn't you inherently be cropping it in the other dimension?

**Comment by slebbo** [comment]
Yes, what I want is to be able to have both portrait and landscape layout on my images in the same source, and just have the configured width to proportionally scale down the image without cropping it. 

Perhaps I've misunderstood how one is supposed to use the plugin, but now it seems to me that I'd need an asset source per image layout to avoid cropping on them.

I've attached some screenshots to illustrate what I mean;

![Optimized config](https://www.dropbox.com/s/1didmaop1t9554a/optimized.png?dl=1)
My configuration of Optimized
![The Asset Source ](https://www.dropbox.com/s/62ca0uncmr46xtv/assetsource.png?dl=1)
My asset source for both images
![Landscape layout](https://www.dropbox.com/s/qfljslh7293ddt7/landscape.png?dl=1)
The landscape image will scale down as desired
![Portait layout ](https://www.dropbox.com/s/fszyxt41v8ov2a7/portrait.png?dl=1)
But the portrait layout will be cropped

**Comment by khalwat** [comment]
So you should be able to do this by creating two Optimized Images fields, and adding them both to your Asset source.

One would have the landscape aspect ratios in it, the other would have the portrait aspect ratios in it (using the `?` Custom aspect ratio setting).

You'd need to do this to keep the srcSet separate for each image orientation.
