### ISSUE TITLE
Bug: ImageTransform::getAssetUri does not work for volumes with a path in the base URL

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft3-imageoptimize#112]
Example:

### Volume (s3) with a Base URL of:
`https://s3.us-east-2.amazonaws.com/my-bucket-name/`

Will yield invalid URLs with `my-bucket-name` as part of the path, e.g.:
`https://my-site.imgix.net/my-bucket-name/blake-mitchell.jpg?w=200`

For this to work with s3/google, you'd either have to use:

$volume->subfolder + $asset->path
OR
parse $volume->baseUrl out of $asset->url

**Comment by khalwat** [comment]
Related to: https://github.com/nystudio107/craft-imageoptimize/issues/113

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize/commit/1952106ac3038a14b24ac65aae825aa1ce9e9d37
