### ISSUE TITLE
JPG variant does not exist

### ISSUE THREAD

**Issue by bkmorse** [nystudio107/craft3-imageoptimize#113]
Craft 3, LEMP stack via docker

I went thru a few of the issues related to this w/o any success. The images upload fine to the folders.

I set the volumes.php

```
    // Local (development) environment
    'local'  => [
        'heros' => [
            'path' => '/var/www/html/public/uploads/heros',
            'url' => 'http://project.local/uploads/heros',
        ],    
    ],

```

I did not see errors in web.log

My environment variables are set for base path and url

```
CRAFTENV_CRAFT_ENVIRONMENT=local
CRAFTENV_BASE_PATH=/var/www/html/public
CRAFTENV_BASE_URL=http://project.local
```

<img width="1044" alt="screen shot 2018-10-08 at 3 58 05 pm" src="https://user-images.githubusercontent.com/84529/46630772-317ea280-cb13-11e8-993b-ca24f98d1946.png">

<img width="1044" alt="screen shot 2018-10-08 at 4 10 24 pm" src="https://user-images.githubusercontent.com/84529/46631210-ca61ed80-cb14-11e8-85dd-e23bd75cfcb4.png">

<img width="1036" alt="screen shot 2018-10-08 at 4 10 41 pm" src="https://user-images.githubusercontent.com/84529/46631211-ca61ed80-cb14-11e8-8664-94572e73922b.png">

<img width="1039" alt="screen shot 2018-10-08 at 4 07 07 pm" src="https://user-images.githubusercontent.com/84529/46631160-9a1a4f00-cb14-11e8-8687-a0871e9437a2.png">

<img width="867" alt="screen shot 2018-10-08 at 3 58 51 pm" src="https://user-images.githubusercontent.com/84529/46630774-32173900-cb13-11e8-94b2-4a07d1de6207.png">

**Comment by khalwat** [comment]
So it's really hard to tell from here, but it's going to be some kind of local dev setup issue. Have you consider trying to use aliases instead for your `volumes.php`?

**Comment by khalwat** [comment]
I think it may be related to: https://github.com/nystudio107/craft-imageoptimize/issues/112

**Comment by khalwat** [comment]
Turns out to not be related to #112 -- I did add some code to the next version to assist you in diagnosing it, though, @bkmorse

**Comment by khalwat** [comment]
Appears to be the same as https://github.com/nystudio107/craft-imageoptimize/issues/111

I've added some code to the next version that will turn the **image variant does not exist** into a link, so we can see what the generated image URL should be, and go from there to diagnose it.

**Comment by khalwat** [comment]
Okay so @bkmorse  please try version 1.4.41: https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.41

I don't expect it to _fix_ the issue you're seeing, but what it will do is make the ** image variant does not exist** a link to where the optimized images should be.

Try clicking on the link to see if the image then loads in a new browser window, and if not, have a look at the URL to see how it might not be set properly.

**Comment by khalwat** [comment]
Going to close this issue since it's likely the same as #111

**Comment by jalendport** [comment]
Fwiw, I've run into this same problem on Valet - I've detailed how I "solved" it over [here](https://github.com/verbb/icon-picker/issues/7#issuecomment-482761906) in case it's helpful to anyone.

**Comment by khalwat** [comment]
Relevant: https://discourse.brew.sh/t/brews-curl-openssl-cant-resolve-localhost-hostnames-set-up-in-dnsmasq-system-curl-has-no-issue/5327
