### ISSUE TITLE
Does not appear to be an image error in queue.log

### ISSUE THREAD

**Issue by icemancast** [nystudio107/craft3-imageoptimize#116]
We randomly get this error in our queue.log file when and the "This is not an image that can be manipulated" in the admin area. We tried different variations of files, sizes, names to see if we could accurately pinpoint when the error would occur but it seemed to be sporadic when it happened. Below is a log from queue as an example output from the log file. We are using imgix services. Please advise:

```
2018-10-12 18:01:21 [-][1][-][warning][craft\services\AssetTransforms::getLocalImageSource] Unable to delete the file "/serverpath/storage/runtime/assets/sources/16490.png": unlink(/serverpath/storage/runtime/assets/sources/16490.png): No such file or directory
 71771: 2018-10-12 18:01:21 [-][1][-][error][nystudio107\imageoptimize\jobs\ResaveOptimizedImages::execute] The file “/serverpath/storage/runtime/temp/1.delimiter.5bc119b184a2f0.80557217.png” does not appear to be an image.
 71772  2018-10-12 18:01:21 [-][1][-][info][yii\db\Command::execute] UPDATE `craft_queue` SET `progress`=0, `timeUpdated`=1539381681 WHERE `id`='3556'
 71773  2018-10-12 18:01:21 [-][1][-][profile begin][yii\db\Command::execute] UPDATE `craft_queue` SET `progress`=0, `timeUpdated`=1539381681 WHERE `id`='3556'
```

**Comment by khalwat** [comment]
Have you looked at the `1.delimiter.5bc119b184a2f0.80557217.png` to see if it's actually an image?

The thing I'm slightly confused about is that if you're using Imgix it shouldn't be doing anything on the server in any event?

**Comment by icemancast** [comment]
Yeah so I am not seeing that image there at all, could have been cleaned out already. So took the advice on the other issue to deactivate the plugin and reactivate the plugin and I haven't noticed the issue. Judging from your response does it sound like the initial install was some sort of hybrid between server/imgix? Also only settings for imgix are in config correct?

**Comment by icemancast** [comment]
I can not get it to error out consistently however when it does it seems that the images do not have a focal point. Similar to what these folks have experienced - https://github.com/nystudio107/craft-imageoptimize/issues/21#.  After setting a focal point, and saving the image, the transforms are created and the issue is fixed. Also wondering if this feature would likely fix it: https://github.com/nystudio107/craft-imageoptimize/issues/101

**Comment by khalwat** [comment]
huh. That's actually a really useful lead, I'll see if that helps me reproduce it (not having a Focal Point set)

**Comment by khalwat** [comment]
The only thing that makes sense to me re: the Imgix / Craft transform you mention is that there could be a task that never completes, which has the old Transform Method in it. Do you have anything in your `queue` table?

**Comment by icemancast** [comment]
So yes sometimes it ends up in queue table only after we save. So our current process is as follows. 

1. Upload image
2. If fail meaning we get the image could not be manipulated message, edit the image and set focal point
3. Save

It seems if we save the entry while the image could not be manipulated that it ends up stuck in the queue table.

**Comment by icemancast** [comment]
Also to answer your question there is nothing currently in the queue table.

**Comment by icemancast** [comment]
@khalwat does that help any?

**Comment by khalwat** [comment]
I tried replicating what you’re doing there, and it works without an issue, it’s confusing. I think maybe it may be specific to if you’re using Imgix?

**Comment by icemancast** [comment]
@khalwat believe is might be imgix related and also believe it to be something that is like a timing issue with the focal point. I just upgraded to version 1.4.43 also will note we are using imgix to do transformations and hosting images on s3.

1. If I upload an image
2. Save the entry
3. No image shows up on our endpoint.

1. If I upload the image
2. Set a focal point
3. Save the entry 
4. The image always shows up

So the step that we always have to make sure we do manually is set the focal point for the image. Even opening the window for setting in an entry and saving will fix the issue after saving the entry.

**Comment by khalwat** [comment]
Roger that. I'll see if there is a way I ensure that a focal point is always set on the image. It's odd that I can't reproduce it.

**Comment by khalwat** [comment]
I think I've addressed this in https://github.com/nystudio107/craft-imageoptimize/commit/28424d68edc55a5c33cbaa4be59f98ae8c8d3d94

Can you try setting the version to `dev-develop` and do a `composer update` to see if addresses it for you?

**Comment by khalwat** [comment]
Please try version 1.4.44 and let me know how that works for you: https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.44

**Comment by khalwat** [comment]
@icemancast

**Comment by icemancast** [comment]
@khalwat going to test it today and will report. Thank you.

**Comment by icemancast** [comment]
<img width="660" alt="screen shot 2018-11-19 at 2 39 11 pm" src="https://user-images.githubusercontent.com/110063/48734023-d956b800-ec09-11e8-9f0d-45e24eaf91cb.png">

1. If i upload
2. click save
3. save entry
All is good as it setup a focal point

But...
1. If I upload
2. save entry
Image is broken or uknown from api side and the image attached is what the preview image looks like.

**Comment by khalwat** [comment]
I have not forgotten :)

**Comment by icemancast** [comment]
Thank you.

**Comment by khalwat** [comment]
So as I've investigated this further, I think the issue absolutely requires that the images are hosted on S3 for it to happen.

Which would explain why I've been unable to reproduce it in my tests locally.

I'm not convinced that the focal point has anything to do with it; rather it seems more likely that the issue is the time it takes for the image to be uploaded to S3, and then for a _local_ version of the image to be downloaded for the transforms.

This is something Craft does normally, but for Imgix, there's no reason for it to be doing so (but I also think there's no reasonable way I can stop it).

**Comment by AdamChlan** [comment]
Any chance this setting could impact it, under Utilities -> Asset Indexes? Should this be turned off?

<img width="741" alt="screenshot 2019-01-02 13 17 07" src="https://user-images.githubusercontent.com/757209/50605674-fc26ee00-0e90-11e9-815e-f232877e886a.png">

**Comment by khalwat** [comment]
It's _possible_ but the issue is that this is happening for him for newly uploaded files, and there's no option available anywhere that I'm aware of that affects that.

The toggle in Utilities -> Asset Indexes only applies to when you click on Index, it isn't a saved setting unfortunately.

**Comment by denisyilmaz** [comment]
Hi, I'm experiencing a similar Issue. I have S3 setup with IMGIX with rather large image library (7000+).
I had to change some settings inside image-optimize which result in a `Optimizing images in media` task.
```json
{
    "criteria": {
        "siteId": 1,
        "volumeId": "3",
        "status": null,
        "enabledForSite": false
    },
    "fieldId": null,
    "force": false,
    "description": "Optimizing images in Media"
}
```

TTR is set to 4500 and queue is running via supervisor (queue/listen) as described in your blog-entry.

for some images the task fails with following error message (paths shortened for readability):

```bash
2020-11-18 15:40:37 [-][-][-][error][Imagine\Exception\RuntimeException] ImagickException: cache resources exhausted `./storage/runtime/temp/image-file.delimiter.5fb53263c054e8.68206049.jpg' @ error/cache.c/OpenPixelCache/3984 in ./vendor/pixelandtonic/imagine/src/Imagick/Imagick.php:189
Stack trace:
#0 ./vendor/pixelandtonic/imagine/src/Imagick/Imagick.php(189): Imagick->sampleimage()
#1 ./vendor/pixelandtonic/imagine/src/Imagick/Imagick.php(35): Imagine\Imagick\Imagick->thumbnailImage()
#2 ./vendor/pixelandtonic/imagine/src/Imagick/Image.php(317): Imagine\Imagick\Imagick->smartResize()
#3 ./vendor/craftcms/cms/src/image/Raster.php(379): Imagine\Imagick\Image->smartResize()
#4 ./vendor/craftcms/cms/src/image/Raster.php(241): craft\image\Raster->resize()
#5 ./vendor/craftcms/cms/src/services/AssetTransforms.php(1177): craft\image\Raster->scaleToFit()
#6 ./vendor/craftcms/cms/src/services/AssetTransforms.php(1095): craft\services\AssetTransforms->storeLocalSource()
#7 ./vendor/craftcms/cms/src/elements/Asset.php(1366): craft\services\AssetTransforms->getLocalImageSource()
#8 ./vendor/nystudio107/craft-imageoptimize/src/services/Placeholder.php(231): craft\elements\Asset->getTransformSource()
#9 ./vendor/nystudio107/craft-imageoptimize/src/services/Placeholder.php(211): nystudio107\imageoptimize\services\Placeholder->createImageFromAsset()
#10 ./vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(433): nystudio107\imageoptimize\services\Placeholder->createTempPlaceholderImage()
#11 ./vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(546): nystudio107\imageoptimize\services\OptimizedImages->generatePlaceholders()
#12 ./vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(130): nystudio107\imageoptimize\services\OptimizedImages->addVariantImageToModel()
#13 ./vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(248): nystudio107\imageoptimize\services\OptimizedImages->populateOptimizedImageModel()
#14 ./vendor/nystudio107/craft-imageoptimize/src/jobs/ResaveOptimizedImages.php(98): nystudio107\imageoptimize\services\OptimizedImages->updateOptimizedImageFieldData()
#15 ./vendor/yiisoft/yii2-queue/src/Queue.php(246): nystudio107\imageoptimize\jobs\ResaveOptimizedImages->execute()
#16 ./vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage()
#17 ./vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute()
#18 [internal function]: yii\queue\cli\Command->actionExec()
#19 ./vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#20 ./vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#21 ./vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction()
#22 ./vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction()
#23 ./vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#24 ./vendor/craftcms/cms/src/console/Application.php(88): yii\console\Application->runAction()
#25 ./vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#26 ./vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#27 ./craft(22): yii\base\Application->run()
#28 {main}

Next Imagine\Exception\RuntimeException: Resize operation failed in ./vendor/pixelandtonic/imagine/src/Imagick/Image.php:325
Stack trace:
#0 ./vendor/craftcms/cms/src/image/Raster.php(379): Imagine\Imagick\Image->smartResize()
#1 ./vendor/craftcms/cms/src/image/Raster.php(241): craft\image\Raster->resize()
#2 ./vendor/craftcms/cms/src/services/AssetTransforms.php(1177): craft\image\Raster->scaleToFit()
#3 ./vendor/craftcms/cms/src/services/AssetTransforms.php(1095): craft\services\AssetTransforms->storeLocalSource()
#4 ./vendor/craftcms/cms/src/elements/Asset.php(1366): craft\services\AssetTransforms->getLocalImageSource()
#5 ./vendor/nystudio107/craft-imageoptimize/src/services/Placeholder.php(231): craft\elements\Asset->getTransformSource()
#6 ./vendor/nystudio107/craft-imageoptimize/src/services/Placeholder.php(211): nystudio107\imageoptimize\services\Placeholder->createImageFromAsset()
#7 ./vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(433): nystudio107\imageoptimize\services\Placeholder->createTempPlaceholderImage()
#8 ./vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(546): nystudio107\imageoptimize\services\OptimizedImages->generatePlaceholders()
#9 ./vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(130): nystudio107\imageoptimize\services\OptimizedImages->addVariantImageToModel()
#10 ./vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(248): nystudio107\imageoptimize\services\OptimizedImages->populateOptimizedImageModel()
#11 ./vendor/nystudio107/craft-imageoptimize/src/jobs/ResaveOptimizedImages.php(98): nystudio107\imageoptimize\services\OptimizedImages->updateOptimizedImageFieldData()
#12 ./vendor/yiisoft/yii2-queue/src/Queue.php(246): nystudio107\imageoptimize\jobs\ResaveOptimizedImages->execute()
#13 ./vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage()
#14 ./vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute()
#15 [internal function]: yii\queue\cli\Command->actionExec()
#16 ./vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#17 ./vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#18 ./vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction()
#19 ./vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction()
#20 ./vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#21 ./vendor/craftcms/cms/src/console/Application.php(88): yii\console\Application->runAction()
#22 ./vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#23 ./vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#24 ./craft(22): yii\base\Application->run()
#25 {main}

```
