### ISSUE TITLE
child pid 48420 exit signal Segmentation fault (11)

### ISSUE THREAD

**Issue by FrencisAlreadyInUse** [nystudio107/craft3-imageoptimize#119]
Segmentation error when putting plugin to work and saving/adding new assets

**Comment by FrencisAlreadyInUse** [comment]
1. Installed plugin via composer. Installed image optim plugins with homebrew (mozjpeg, optipng, svgo, gifsicle)

At a certain point I got a lot of stalled task from "Optimising Web Assets". Bumped up the `memory_limit` & `max_execution_time` but didn't help. 
When checking the apache2 logs, I saw there were multiple:`exit signal Segmentation fault (11)`. 

Craft logged me out because I wasnt using the cms. When trying to log back in, it wasnt possible. Again an `exit signal Segmentation fault (11)`.

Deleted the craft-imageoptimize plugin with composer. Still couldn't login. By trying everything we could, it somehow got us back into the admin panel. (Reinstalled mysql, removed some .htaccess lines from the `web-folder`. After be abel to login again, the "Optimising Web Assets" is still stuck and throws an error every 5 minutes "An unknown error occurred." Looking back at the apache logs its again an `exit signal Segmentation fault (11)`.

**Comment by khalwat** [comment]
The segmentation fault is some process on your server running out of memory. The stalled tasks are a result of the task that is creating the optimized image variants apparently seg faulting somewhere.

The tasks are stored in the `queue` table; to you can truncate this table to stop it from trying to execute those tasks.
