### ISSUE TITLE
Crop to specific height

### ISSUE THREAD

**Issue by jonlongnecker** [nystudio107/craft3-imageoptimize#120]
I feel like maybe I've missed something simple somewhere. I want to set an explicit width and height for an image to crop to, but only see aspect ratios as an option.

If I try to crop it on the template side without using aspect ratios or an ImagesOptimized field, adding a height parameter doesn't seem to do anything. 

`{% set optimizedImages = craft.imageOptimize.createOptimizedImages(
	    entry.featuredImage.one(),
	    [
	        {
	            'width': 710,
		    'height': 220,
	            'useAspectRatio': false,
	            'retinaSizes': ['1', '2'],
	            'quality': 90,
	            'format': 'jpg',
	        },
	    ]
	) %}`

What's the best way to create a 710x220 image with ImageOptimize?

**Comment by khalwat** [comment]
The OptimizedImages field is a wrapper around creating `srcset`s for you. `srcset`s are always keyed off of a width, and the height is determined by the aspect ratio you pass in, or if you disabled the aspect ratio, it uses the original image's aspect ratio.

It sounds like what you really want to do in this case is just use a regular Craft transform. Image Optimize will still run the resulting image through the various optimizers, but it doesn't sound like you actually want to create a `srcset` -- in which case, the OptimizedImages field doesn't make sense to use.

**Comment by jonlongnecker** [comment]
Well I still want a srcset for retina images, just need it in those dimensions + 2x or whatever. I ran the math on the aspect ratio to set it as 1:3.23, but just seemed like a really roundabout way to do it. Be nice if the height parameter was an option ;)

**Comment by khalwat** [comment]
The general idea is that with a truly responsive design, the height for the `srcset` is something that the browser typically is left to figure out. You give it the media queries for the width, and it figures out the height based on that.

It's not very common that an image will stay the exact same height through all responsive sizes. If you're truly just doing it for retina/non-retina, I would probably just use a Craft transform.

But I think it's somewhat likely that you'd be better served using a responsive `srcset` with various widths/sizes (just in general, not seeing what you're working on).
