### ISSUE TITLE
Transform URL Missing Subfolder Directory

### ISSUE THREAD

**Issue by AdamChlan** [nystudio107/craft3-imageoptimize#121]
I am using Imgix in conjunction with ImageOptimize. I have an /assets/ directory in my root, where I am setting up directories for my various asset volumes. I have applied an Image Optimize field on a particular volume. Images upload to the server as expected.

When I add an image to the asset area in Craft, within my sub-folder, and double click on the image, it indicates the my variants do not exist. When I click on the link, it takes me to the Imgix URL, without the subfolder in the URL. If I manually add the subfolder after the Imgix domain, the image loads.

BAD:
https://mos-mouse-staging.imgix.net/Screen-Shot-2018-03-09-at-10.31.38-AM.jpg?auto=format&crop=focalpoint&domain=mos-mouse-staging.imgix.net&fit=crop&fp-x=0.5&fp-y=0.5&h=1440&ixlib=php-2.1.1&q=82&w=1440

GOOD:
https://mos-mouse-staging.imgix.net/home-stats/Screen-Shot-2018-03-09-at-10.31.38-AM.jpg?auto=format&crop=focalpoint&domain=mos-mouse-staging.imgix.net&fit=crop&fp-x=0.5&fp-y=0.5&h=1440&ixlib=php-2.1.1&q=82&w=1440

Not sure if something needs to be adjusted in the asset volume?

baseURL is: https://mydomain.com/assets/home-stats

**Comment by AdamChlan** [comment]
I ended up installing v 1.4.40 and my transforms and URLs look right now. Seems the latest version has an issue when using Imgix in conjunction w/ local asset folders.

**Comment by khalwat** [comment]
hmmmm. Well that should make it easy enough to track down.

**Comment by khalwat** [comment]
This is addressed in https://github.com/nystudio107/craft-imageoptimize/commit/b93d64e95e7a378b5a9d60f69b4d71f7c665a7b8

**Comment by khalwat** [comment]
@timkelty and I are looking into addressing this in a more proper manner... stay tuned.

**Comment by timkelty** [comment]
@AdamChlan what is the "Base URL" setting set to in imgix?
![screen shot 2018-11-02 at 1 52 39 pm](https://user-images.githubusercontent.com/18329/47931952-9cb75c80-dea6-11e8-952b-a30db1a6d3f2.png)

**Comment by khalwat** [comment]
Fixed in 1.4.43 -> https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.43
