### ISSUE TITLE
Check if webP exist?

### ISSUE THREAD

**Issue by davidhellmann** [nystudio107/craft3-imageoptimize#122]
Hey Andrew,

think I found a bug.

I create an image and disbaled my webp binary.
In my template I use:

```
 <source data-srcset="{{ opt.maxWidth ? imageSrcsetMaxWidthWebP : imageSrcsetWebP }}"
              data-sizes="100vw"
              type="image/webp"/>
```

My Image in the CP is like this (no webP Images)
![image](https://user-images.githubusercontent.com/764292/47779512-8c15b380-dcf9-11e8-96dd-221744d39914.png)

BUT, when I dump the srcSetWebP I get URLs back and that kill the images. 
![image](https://user-images.githubusercontent.com/764292/47779571-a6e82800-dcf9-11e8-8955-66fe6ffcac7d.png)

The image is not there but the url.

Maybe an option like `imageOptimize.webPSupport` would be nice to skip the source part.

**Comment by khalwat** [comment]
```twig
{% if craft.imageOptimize.serverSupportsWebP() %}
{% endif %}
```

It's always been in there, I just forgot to put it in the documentation.

Added it in https://github.com/nystudio107/craft-imageoptimize/commit/1ec9addefaf6a68ea29c1064adfdaa749ccf8820

**Comment by davidhellmann** [comment]
ah, thanks :)
