### ISSUE TITLE
Local Folder Volume Path Issue

### ISSUE THREAD

**Issue by agrigg** [nystudio107/craft3-imageoptimize#123]
After the Version 1.4.41 update, the correct paths are not getting sent to imgix. I have a volume called Uploads with the following properties:

Volume Type: Local Folder
Base URL: @web/uploads
File System Path: @webroot/uploads

My imgix source is configured as a Web Folder pointing to the base URL for the Craft 3 site.

Before, when an asset was uploaded to the Uploads volume, it would generate the imgix url as:

`<mysitename>.imgix.net/uploads/<filename>`

After Version 1.4.41 it is rendering it without the "uploads" folder as:

`<mysitename>.imgix.net/<filename>`

which doesn't exist so we get a 404

Looking at the commits it looks like this was caused by the changes to the getAssetUri method here: 

https://github.com/nystudio107/craft-imageoptimize/compare/1.4.40...1.4.41#diff-17cb8bff55af2466e4caddefa9ec1016

It seems like $asset->getPath() is not including the folder in the path possibly?

I reverted the plugin to 1.4.40 and this problem went away.

**Comment by nickcotton** [comment]
I've run into this as well but I think it's been addressed in #121. Hopefully a new release will be out soon, reverting to 1.4.40 caused other errors for me.

**Comment by agrigg** [comment]
Cool, thanks!

**Comment by khalwat** [comment]
Yep, this is the same as https://github.com/nystudio107/craft-imageoptimize/issues/121

**Comment by khalwat** [comment]
Fixed in 1.4.43 -> https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.43
