### ISSUE TITLE
Add config to enable or disable optimizations

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft3-imageoptimize#13]
In most situations I don't need to optimize my transforms in my local environment, so I don't install and manage libraries like jpegoptim in my dev environment. I usually match my staging environment to my production, so if I need to test things like creating a webp variant or doing image compression, I would do it on staging.

It would be great to either have an overall kill switch config option to simply ignore all optimizations from third-party libraries, or to have kill switches to enable/disable each type of optimization.

I'd still like to see the image transforms happen in my dev environment, so ideally the option to enable/disable optimizations would just mean that the functions that return an optimized URL would simply return a URL of the transformed image.

_NOTE: Right now I'm getting some errors that I think are based on the fact that I don't have the libraries installed, but this config option would not only fix these errors, but I think it would speed up local development by skipping extra steps of attempting the optimizations in the first place._

**Comment by khalwat** [comment]
So the errors you're seeing are harmless, and probably not slowing anything down in any meaningful way (they are just saying that the image processor doesn't exist).

But the ability to turn these things on or off is already there... check out the `activeImageProcessors` and `activeImageVariantCreators` settings in the mutli-environment aware `config.php`

If you don't want 'em to run, remove'em.
