### ISSUE TITLE
[FR] General ImageTransform API cleanup

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft3-imageoptimize#131]
Clean up $params/getTransformParams usage in favor of direct props

`$params` gets passed around in alot of methods, which I think is, maybe entirely vestigial (from when these methods were all static).

In `craft-imageoptimize-thumbor` I'm already using the props directly, as I didn't want to have to change the fn signature or make a wrapper method: https://github.com/nystudio107/craft-imageoptimize-thumbor/blob/v1/src/imagetransforms/ThumborImageTransform.php#L252

**Comment by khalwat** [comment]
It is vestigial, and I do want to do away with it; but I wanted to incrementally refactor things. Now that we have a good modular system for the Image Transforms, I can clean up these params.

Off of the top of my head, `generateTransformsBeforePageLoad` needs to be added to the CraftImageTransform... or potentially added in via the `ImageTransformTrait` so it applies to all things. For historical reasons, the params as cached as a static property on the plugin's main class; I just want to make sure I don't break anything major by removing it.

Shouldn't be too bad tho.

In addition:

* ~The `ImageTransformInterface` should be documented beyond just the passed parameters, and the base class should just `@inheritdoc`~ done
* Arguably `getAssetUri()` shouldn't be part of the interface

**Comment by khalwat** [comment]
This refactor happened in [1.6.0](https://github.com/nystudio107/craft-imageoptimize/blob/v1/CHANGELOG.md#160---20190705)
