### ISSUE TITLE
Buggy interactions when toggling "Enforce Aspect Ratio" after adding a new variant to a field

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft3-imageoptimize#134]
After adding a new variant to a field, the new variant's **Enforce Aspect Ratio** toggle hides the **Aspect Ratio** options, but the lightswitch remains enabled.

The lightswitch works properly for variants that existed before, but the **Aspect Ratio** settings always display, regardless of the **Enforce Aspect Ratio** value. Changing the value from off to on always hides, then shows the **Aspect Ratio** options.

**Comment by jsunsawyer** [comment]
Also, this causes aspect ratio to stay enforced, even though it looks like it has been disabled. Editing the field after saving initial settings allows you to go back in and properly toggle aspect ratio.

**Comment by khalwat** [comment]
Looks like something is amiss with the state when a new variant is added, thx.

**Comment by ilicmarko** [comment]
I will probably take this during the Hacktoberfest.

**Comment by khalwat** [comment]
I'm completely redoing how this all works so... this will be addressed as part of that new UX https://twitter.com/nystudio107/status/1356368143392903168?s=20
