### ISSUE TITLE
[FR] Support for Craft 3.1 environment variables

### ISSUE THREAD

**Issue by nettum** [nystudio107/craft3-imageoptimize#135]
Add support for enviroment variables on the settings page, at least for Imgix Key/Secret and Thumbor Secret to keep them out from `project.yaml`.  

As far as I can see you can override these values today in `image-optimize.php`:
```
return [
    ...
    'imageTransformTypeSettings' => [
        ImgixImageTransform::class => [
            'apiKey' => getenv('IMGIX_API_KEY'),
            'securityToken' => getenv('IMGIX_SECURITY_TOKEN'),
        ]
    ],
    ...
];
```
but it won't keep the secrets out of `project.yaml`?

See latest aws-s3 update for reference, https://github.com/craftcms/aws-s3/commit/c65b1342489395db81f9dd33b8b65be314a6acad 
![image](https://user-images.githubusercontent.com/798156/52129221-4689bf00-2637-11e9-8981-a5d0f1131425.png)

**Comment by khalwat** [comment]
Implemented in 1.5.2 https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.5.2
