### ISSUE TITLE
Focal Points don't work as desired when using imgix

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft3-imageoptimize#138]
I noticed that images weren't being centered on the focal point properly.

Adding `&crop=focalpoint` to the imgix url fixes this issue.

See: https://docs.imgix.com/apis/url/focalpoint-crop

**Comment by khalwat** [comment]
Thanks @jsunsawyer I'll get this rolled in!

**Comment by khalwat** [comment]
@jsunsawyer What type of cropping is being used on these images?

For anything other than `fit` or `stretch` it should indeed be adding that parameter:

https://github.com/nystudio107/craft-imageoptimize-imgix/blob/v1/src/imagetransforms/ImgixImageTransform.php#L152

**Comment by khalwat** [comment]
I see the code path that could happen... fixed in 1.5.4:

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.5.4
