### ISSUE TITLE
Optimized Image queue stuck

### ISSUE THREAD

**Issue by jangidgirish** [nystudio107/craft3-imageoptimize#139]
The craft queue jobs have stuck on `Optimizing images in Site Assets`  i have tried to debug the issue is coming with SVG image

I have also tried to execute optimize index from cli, the cli process has also stuck and returning following error
```

>:/var/www/craft_del$ php craft image-optimize/optimize/create
Creating optimized image variants
Optimizing images in Site Assets
0/216 - processing asset: 1 from field: Optimized Image
1/216 - processing asset: Poup Img from field: Optimized Image
2/216 - processing asset: Paul Morris 184484 Unsplash from field: Optimized Image
3/216 - processing asset: Our Story Hero Image from field: Optimized Image
4/216 - processing asset: Our Product Bg from field: Optimized Image
5/216 - processing asset: Netacea Laptop Png from field: Optimized Image
6/216 - processing asset: N Forward Slsh Mark from field: Optimized Image
Segmentation fault (core dumped)
```
And the system alert following error 
`php7.2 crashed with sigsegv ReadImage()`

I have also truncated craft_quque table as well increase php memory limit to 1024M, the issue is not resolved.

![image](https://user-images.githubusercontent.com/4018017/53086488-3b85c880-352b-11e9-845e-5245f48ef417.png)

**Craft CMS** 3.1.12
**PHP**  7.2.15-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  8 2019 15:37:29) ( NTS )
**ImageOptimize** 1.5.3

**Comment by khalwat** [comment]
Which SVG image is causing this issue?

There is an option in ImageOptimize to tell it to ignore SVG images... ImageOptimize just uses regular old Craft transforms to do its thing, so the odds are very good that this image will not be able to be transformed using Craft transforms either.

It's likely some kind of issue with Craft or more likely Imagine or Imagick/GD (whichever you are using).

So suggestions would be:

-- Try to fix the SVG by running it through https://jakearchibald.github.io/svgomg/
-- Turn on the option to have ImageOptimize ignore SVGs (it's in the Field settings)
-- Ensure you're using the latest versions of Imagick

**Comment by jangidgirish** [comment]
I have skipped svg images form optimize field, the issue is still coming, i was presuming, it's related to svg images because php cli process was stuck on svg image, but same issue is still coming on same image.
gd/Imagick both enabled on server, i am uncertain which is using i am unable to find setting option in plugin setting.
looking like the error is related imagick, letest Imagick is installed on server.
Let me try to fix svg image from editor.

Sorry the issue closed by mistake.

**Comment by jangidgirish** [comment]
I have debug issue deeply, the issue is related to `Imagick`, looks like imagick has conflict with `inkscape`
http://www.imagemagick.org/discourse-server/viewtopic.php?t=28416#p126176
I have just removed `inkscape` and restarted apache server then the queue jobs has been processed.

**Comment by khalwat** [comment]
Great news! Thanks for letting me know.
