### ISSUE TITLE
Support file-based config

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft3-imageoptimize#14]
Having the option to create transforms in the image-optimize.php config file would be a complimentary alternative to the current, matrix-style field config. This could be done by following the syntax of defaultVariants in a new array of transform options.

This would require a way to select a transform from the config file when you create the field on your asset source, so maybe a new field type could be used to select from the config file. Making the connect to the config file would allow for quick updates via the config file and it would allow for version control of these settings.

If someone deletes a transform from the array, it could fall back to the defaultVariants transform so the site doesn't break.

**Comment by khalwat** [comment]
ImageOptimize 1.4.3 allows you to define the default aspect ratios in the `config.php`

It's not _exactly_ what you wanted, but it's close :)
