### ISSUE TITLE
Images not optimized after uploading via front end form

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-imageoptimize#141]
We are using a front end form so users can submit their content. For images we use the asset/save-asset action, so images are uploaded before the entry is saved. The asset id's are then added to the entry form.

The problem we are facing is that the images don't seem to be processed. The optimise task is added to the queue, but when an entry is edited on the front end, they aren't generated. Until you go the the CP; then the jobs seem to start running.

Any idea how to fix this? We need those images to be processed after uploading via the front end, so users can preview their entry including images.

Craft CMS 3.1.16

**Comment by khalwat** [comment]
That's just how queue jobs work for Craft in general, unfortunately. They don't get time until the CP is accessed.

You can find alternative ways to run the queue here:

https://nystudio107.com/blog/exploring-the-craft-cms-3-console-command-line-interface-cli#queue
