### ISSUE TITLE
[FR] Make aspect ratio fields numer fields

### ISSUE THREAD

**Issue by janhenckens** [nystudio107/craft3-imageoptimize#142]
Right now, the aspectRatioX & aspectRatioYfields in the field settings are text fields that can contain anything.

We had a weird issue where a password-manager app filled one of those fields with a username, that got saved and that off course resulted in all sorts of errors. Took us a bit to track down too but it's fixed now :)

The error we got was A non-numeric value encountered so these fields are expected to be a number already. Maybe they could be changed to be actual number fields?

**Comment by khalwat** [comment]
Add:

* A Variant class with model validation rules
* An EmbeddedOIValidator for `getElementValidationRules()`

**Comment by khalwat** [comment]
I'm completely redoing how this all works so... this will be addressed as part of that new UX https://twitter.com/nystudio107/status/1356368143392903168?s=20
