### ISSUE TITLE
Retina checkbox duplicate ID

### ISSUE THREAD

**Issue by ilicmarko** [nystudio107/craft3-imageoptimize#143]
When you add a field with a type of `OptimizedImages` and you want to add a new variant (`Add variant above`) it will clone the first entry and try to update all the ids inside. Unfortunately, this doesn't work for Retina image checkboxes.

If we look at the code that does the update, we can see it matches a simple regex pattern of `-([0-9]+)-`.

https://github.com/nystudio107/craft-imageoptimize/blob/6a90a61847e66daef745eab25dc7a6a901ceafe3/src/assetbundles/optimizedimagesfield/dist/js/OptimizedImages.js#L163-L168

This pattern won't be matched because Craft is used for generating checkboxes (`checkboxGroupField`).

https://github.com/nystudio107/craft-imageoptimize/blob/6a90a61847e66daef745eab25dc7a6a901ceafe3/src/templates/_components/fields/OptimizedImages_settings.twig#L213-L220

For this reason, RegEx won't match and the ID won't update. Rendering the checkbox useless.

**Comment by khalwat** [comment]
Fixed via your PR, thank you!
