### ISSUE TITLE
Feature Request: Contrast Calculation

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft3-imageoptimize#147]
A nice addition to the dominant color calculation would be to color contrast for each, or overall (i.e. using the [YIQ color space](https://en.wikipedia.org/wiki/YIQ)).

This could help identify if any accompanying overlay text should be dark or light.

**Comment by khalwat** [comment]
I think a way to do it would be to convert the colors to HSL, and then average the lightness of the dominant colors.

I'd then make this available via a property on the image, so you can decide what level of lightness determines it being light or dark.

**Comment by khalwat** [comment]
Implemented via https://github.com/nystudio107/craft-imageoptimize/commit/0fe4ee4a8372a1ae2fb277fa1a8b55e18b2eef91

**Comment by joshuabaker** [comment]
Thanks!
