### ISSUE TITLE
[FR] Preserve aspect ratio for CP thumbnails

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft3-imageoptimize#148]
_This may or may not be specific to Imgix usage._

Currently, all images are cropped to squares in the CP. This is inconsistent with how Craft handles thumbnails by default, and makes it more difficult for users to reference different images within a group of uploaded images.

An example of how this could be confusing.

![square-thumbnails](https://user-images.githubusercontent.com/1007191/59370274-062e0200-8cf7-11e9-8088-db6943620174.png)
![actual-images](https://user-images.githubusercontent.com/1007191/59370280-0928f280-8cf7-11e9-94ef-da0e0db882d8.png)

**Comment by khalwat** [comment]
Yeah for sure this has something to do with Imgix specific usage.

**Comment by jsunsawyer** [comment]
If I remove the `'height' => $event->height,` line on line 198 (in the `handleGetAssetThumbUrlEvent` function) on `src/services/Optimize.php` this resolves the issue with thumbnails being forcibly cropped to square in the CP.

**Comment by khalwat** [comment]
Verified and fixed in https://github.com/nystudio107/craft-imageoptimize/commit/a333809d7ef6b89207b2f6226d4d182ad061f94a
