### ISSUE TITLE
ImageOptimize & Embedded Assets Thumbnail Compatibility

### ISSUE THREAD

**Issue by kylecotter** [nystudio107/craft3-imageoptimize#151]
Hey Andrew!

Not sure who this falls under, but when [Embedded Assets](https://github.com/spicywebau/craft-embedded-assets/) and Image Optimize are both enabled, asset thumbnails in the CP for an Embedded Asset defaults to a placeholder JSON thumbnail instead of the actual thumbnail of the embed. Disabling Image Optimize allows Embedded Assets to function as normal.

![Screen Shot on 2019-06-20 at 21-45-18](https://user-images.githubusercontent.com/505894/59891852-d2ad4080-93a4-11e9-85ad-cc47142e3460.png)
(Left is Image Optimized disabled)

Any insight you have is appreciated! Thanks!

cc/ @pvldigital

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize/commit/5fb4fe605a0d611844d71e92afe3f93b7a119e13
