### ISSUE TITLE
All images are optimized after adding new site

### ISSUE THREAD

**Issue by joao-proenca-ef** [nystudio107/craft3-imageoptimize#153]
I currently have a website with about 3500 images, and have 8 transforms.
When I add a new site, a task is triggered that starts Optimizing Images, and creates around 23000 tasks that take a day or more to run.

Since the images aren't language specific or translatable, I'm wondering why that is happening, what is the purpuse of it, and if it's possible not to be done or if it's really needed, as adding a new site means that tasks will be running for a while and we can't really add any new content in that language, since it will only duplicate the content to the new language after finishing all the tasks.

**Comment by khalwat** [comment]
Interesting. So the task is triggered because the Assets are being re-saved by Craft when you add a new site.

I'm not sure exactly why they are re-saving the assets, but the tasks should be very quick, because the images already exist.

**Comment by khalwat** [comment]
It looks like it re-saves the Assets because while assets are not localizable, their field layout is.

I'm surprised that the tasks take a long time to execute, because for transforms that have already been generated, it should be quite quick.
