### ISSUE TITLE
Data loss when replacing existing image fields with optimized image fields?

### ISSUE THREAD

**Issue by timmyomahony** [nystudio107/craft3-imageoptimize#154]
If I change a field type from regular image to an optimized image field:

- will I lose the current images for that section’s entries and have to resave images?
- if not, will the images be automatically optimized (even the the images were saved before using optimized images)

**Comment by khalwat** [comment]
So this isn't how ImageOptimize works... you don't convert an Assets field over to an Optimized Images field. Instead, you add the Optimized Images to your Asset volume.

It was designed this way for exactly the reason you're mentioning: to avoid data loss, and to have ImageOptimize's installation or removal be a non-destructive process.

See: https://github.com/nystudio107/craft-imageoptimize#using-the-optimized-images-field
