### ISSUE TITLE
Possible to run imageOptimize on non-craft-assets images (for example static files)?

### ISSUE THREAD

**Issue by timmyomahony** [nystudio107/craft3-imageoptimize#155]
Is it possible to run image optimization on images that are outside craft? For example, I have images that are used as static files throughout the site that aren't a part of the craft asset system. It would be great to be able to create responsive versions of these images using the CLI. I tried using the Twig approach but this seems limited to craft assets

**Comment by khalwat** [comment]
Unfortunately this isn't possible the way ImageOptimize is architected.

You might consider moving these images into the CMS, just to make various content authoring tasks easier for the client, or in this case (?) for you.
