### ISSUE TITLE
[FR] A way to access a raw Imgix URL

### ISSUE THREAD

**Issue by MikeMcChillin** [nystudio107/craft3-imageoptimize#157]
Currently, you're able to grab the imgix URL if an image is being transformed via an `Image Optimize` field type. But if an image lives outside of any `Image Optimize` field type and isn't transformed, there's no way to grab the Imgix URL for the asset.

I want a way to grab an asset's Imgix URL when it has been uploaded as an asset but that asset doesn't have an `Image Optimize` field on it. Since you're already loading the `imgix-php` library, it would be redundant to install another plugin for this. Maybe something like `{{ entry.myImage.one().imgixUrl }}`?

This would be useful for any SVG, logo, or other asset field that doesn't need to be transformed by an `Image Optimize` field, but still needs to be served via the Imgix CDN.

**Comment by khalwat** [comment]
Have you tried just doing `{{ entry.myImage.one().getUrl()  }}`?

**Comment by MikeMcChillin** [comment]
That would return a Craft Asset url instead of an Imgix url.

**Comment by khalwat** [comment]
@MikeMcChillin Have you tried it? The reason I ask is that if you call `.getUrl()` that ends up calling `Assets::getAssetUrl()` which throws the event that ImageOptimize listens for, and it should replace the Asset url with an Imgix URL.

**Comment by MikeMcChillin** [comment]
@khalwat That returns the AWS asset address for me rather than the Imgix URL.

**Comment by khalwat** [comment]
Gotcha. I agree, this would be a nice feature to add!

**Comment by khalwat** [comment]
Okay so here's the part that I don't understand. If you do `myAsset.getUrl()` it calls this:

https://github.com/craftcms/cms/blob/develop/src/elements/Asset.php#L779

...when then ends up calling `getAssetUrl()`:

https://github.com/craftcms/cms/blob/develop/src/services/Assets.php#L563

This then triggers the `EVENT_GET_ASSET_URL` event, which ImageOptimize intercepts:

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/ImageOptimize.php#L278

And then calls `handleGetAssetUrlEvent()`: 

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/services/Optimize.php#L141

AHA in tracing it, I see what's going on. That'll be in the next message.

**Comment by khalwat** [comment]
So it looks like we hit here:

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/services/Optimize.php#L148

...which does this:

```php
            // If there's no transform requested, and we can't manipulate the image anyway, just return the URL
            if ($transform === null
                || !ImageHelper::canManipulateAsImage(pathinfo($asset->filename, PATHINFO_EXTENSION))) {
                $volume = $asset->getVolume();
                return AssetsHelper::generateUrl($volume, $asset);
            }
```

So probably the right thing to do would be to attempt to generate a URL from the transform method, but just with no transform parameters added.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-imageoptimize/commit/b87df6d40c9673e5b5641c80fa35e5736d6a5d28

**Comment by noahcostello** [comment]
Is there any way to do this and load the url with the Imgix security token parameter?

In my case I want to load an image from the imgix cdn but I'm using secured urls.  I want to load a large transparent .png file to use as a tiled background image.  A transformed version from imgix ends up being 4x the size with auto compression and double the size with the lowest quality setting.

craft.assets().filename('map.png').one().getUrl() returns the file from imgix, but the s= hashed string paramater isn't on it. Thanks.
