### ISSUE TITLE
[FR] ability to set process priority

### ISSUE THREAD

**Issue by kishalmi** [nystudio107/craft3-imageoptimize#159]
it would be useful to set the `nice` level of optimizing processes, in order not to hog too much CPU. 
to prevent this getting too OS-specific, it could be an optional `commandPrefix` field for the commands - like so:

```// png optimizers
   'optipng' => [
     'commandPrefix' => '/usr/bin/nice -n 10 ',
     'commandPath' => '/usr/bin/optipng',
     'commandOptions' => '-o3 -strip all',
     'commandOutputFileFlag' => '',
   ],```

**Comment by khalwat** [comment]
So I thought about adding this, but decided that since all of the image optimization is done via a queue job, the `nice` would be better done there.

Check out the [Robust queue job handling in Craft CMS](https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms) article for details.
