### ISSUE TITLE
[FR] Dominant Color Override

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft3-imageoptimize#162]
I know that we can add our own field to override dominant colors, but it might be nice if it was built into the plugin so our template logic could stay the same.

This optional field would allow users to override a dominate color when the auto-detected color doesn't work well.

For example, a JPG image might have a white background and display on a white background. Fading this image in from a white placeholder background looks better than a solid block of some other dominant color, which can look jarring.

**Comment by khalwat** [comment]
This is probably something that is best left up to you with some template logic, I think.
