### ISSUE TITLE
[FR] Add schema support for imageoptimize in Craft 3.3 GraphQL api

### ISSUE THREAD

**Issue by djurdjen** [nystudio107/craft3-imageoptimize#163]
Right now the optimizedImages field in the AssetInterface is being referenced to as a `String` which breaks the query in GraphQL.

Craft version: 3.3.3
imageoptimize: 1.6.1
PHP: 7.2

**Comment by khalwat** [comment]
There hasn't been any released documention for plugin developers on how to add custom GraphQL schema for the implementation from Pixel & Tonic. As soon as there is, I will definitely be doing it.

**Comment by khalwat** [comment]
Implemented in 1.6.2 -> https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.2
