### ISSUE TITLE
This is not an image that can be manipulated or the images would all be up-scaled.

### ISSUE THREAD

**Issue by bdmtra** [nystudio107/craft3-imageoptimize#164]
If I upload image with 1920x1080 resolution I get "This is not an image that can be manipulated or the images would all be up-scaled" error message.

**Comment by khalwat** [comment]
Can you provide a screenshot of where you're seeing this message? Does it happen for all images, or just one image in particular?

Do you find any errors in your `storage/logs/web.log` ?

**Comment by khalwat** [comment]
Will re-open if I get additional information.
