### ISSUE TITLE
1:1 uploaded image getting cropped, can't understand why

### ISSUE THREAD

**Issue by chadcrowell** [nystudio107/craft3-imageoptimize#165]
I'm uploading this image: [https://d.pr/i/DSMGC9](https://d.pr/i/DSMGC9)

and two others formatted just like it to 2000x2000 to an Image Optimize field with these settings (note all versions are 1:1): [https://d.pr/v/4Oc26m](https://d.pr/v/4Oc26m)

and getting these resulting images: [https://d.pr/v/Gi6gkJ](https://d.pr/v/Gi6gkJ)

I can't understand why a 1:1 uploaded image that is getting transformed to a bunch of 1:1 sizes is getting cropped. Is there a setting somewhere I have wrong or am missing?

**Comment by khalwat** [comment]
Are they actually cropped incorrectly, or are they just incorrectly cropped when displayed as a thumbnail?

Can you get me the original image?

**Comment by chadcrowell** [comment]
Solved a while ago. I needed to wait for Cloudfront caching to clear.
