### ISSUE TITLE
Change imgix "fit" transform mode to be in line with Craft's "fit" transform mode

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft3-imageoptimize#167]
The transform method is currently set to `$params['fit'] = 'clamp';` in `ImgixImageTransform.php`.

It looks like this should probably be changed from `clamp` to `clip`.

See: https://docs.imgix.com/apis/url/size/fit

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize-imgix/releases/tag/1.1.1
