### ISSUE TITLE
Can't composer update to 1.6.2

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft3-imageoptimize#169]
Hello NYStudio107 Code Magicians, 

I'm running into an issue today, trying to update ImageOptimize to version 1.6.2. Running the updater in the backend as well as from the CLI results in this error message:

> Error: The "https://composer.craftcms.com/p/nystudio107/craft-imageoptimize-imgix/c642ab1cfc1bf5e4c9c3c265837b1e5201a6ed55436f1bbb47558a9c63a49384.json" file could not be downloaded (HTTP/1.1 404 Not Found)

I am on Craft Pro 3.3.4.1 and running PHP 7.3.9 at the moment. 

Thank you very much for any help on how to fix that problem as it stops me from updating the system. 

Best regards
Mike

**Comment by rogertinch** [comment]
Having this same issue on Craft 3.3.6 with ImageOptimize 1.6.2.

**Comment by jsunsawyer** [comment]
I am getting this exact error when trying to simply remove other disabled plugins in the CP.

**Comment by khalwat** [comment]
I think this might be some kind of issue with the Craft updater. I was able to do an update with `composer update` locally with no issues:

```
  - Installing nystudio107/craft-imageoptimize (1.6.2): Downloading (100%)
  - Installing nystudio107/craft-imageoptimize-thumbor (1.3.0): Downloading (100%)
  - Installing nystudio107/craft-imageoptimize-sharp (1.0.2): Downloading (100%)
  - Installing nystudio107/craft-imageoptimize-imgix (1.1.1): Downloading (100%)
```

I've posted an issue of there, and linked to this issue: https://github.com/craftcms/cms/issues/5063

**Comment by jsunsawyer** [comment]
I removed my disabled plugins via composer and all went well.

I just tried to update Retour to 3.1.26 from the CP and this was my full error.

```
Error: The "https://composer.craftcms.com/p/nystudio107/craft-imageoptimize-imgix/c642ab1cfc1bf5e4c9c3c265837b1e5201a6ed55436f1bbb47558a9c63a49384.json" file could not be downloaded (HTTP/1.1 404 Not Found)

Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Package "danielstjules/stringy" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
```

Hope this helps.

**Comment by khalwat** [comment]
Brandon has fixed this in https://github.com/craftcms/cms/issues/5063
