### ISSUE TITLE
SVG with embedded PNG throwing "Unknown Error" in CP, with SVG processing off

### ISSUE THREAD

**Issue by gbowne-quickbase** [nystudio107/craft3-imageoptimize#170]
My content team is churning away on content, and we've got the plugin running in production, just fine. We had an issue where updating an image [to add alt text] gave a save error with the "Unknown Error" alert in the CP. I traced it down and the top of the stack is below. And I've attached the image.

1) We have SVG processing off in the plugin
2) We don't have any SVG processors loaded on the machinge
3) The image itself says it won't be resized because that would be some upsizing
4) The image itself is a <facepalm>SVG with an embedded PNG</facepalm> because a designer was having problems and didn't ask for help. 

```
Next craft\errors\ImageException: Failed to load the SVG string. in /var/www/www.quickbase.com/vendor/craftcms/cms/src/image/Raster.php:508
Stack trace:
#0 /var/www/www.quickbase.com/vendor/craftcms/cms/src/services/Images.php(193): craft\image\Raster->loadFromSVG('<?xml version="...')
#1 /var/www/www.quickbase.com/vendor/nystudio107/craft-imageoptimize/src/services/Placeholder.php(259): craft\services\Images->loadImage('/var/www/www.qu...', true, 300)
#2 /var/www/www.quickbase.com/vendor/nystudio107/craft-imageoptimize/src/services/Placeholder.php(233): nystudio107\imageoptimize\services\Placeholder->createImageFromPath('/var/www/www.qu...', 300, 118, 75, Array)
#3 /var/www/www.quickbase.com/vendor/nystudio107/craft-imageoptimize/src/services/Placeholder.php(211): nystudio107\imageoptimize\services\Placeholder->createImageFromAsset(Object(craft\elements\Asset), 300, 118, 75, Array)
#4 /var/www/www.quickbase.com/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(348): nystudio107\imageoptimize\services\Placeholder->createTempPlaceholderImage(Object(craft\elements\Asset), 2.54, Array)
#5 /var/www/www.quickbase.com/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(444): nystudio107\imageoptimize\services\OptimizedImages->generatePlaceholders(Object(craft\elements\Asset), Object(nystudio107\imageoptimize\models\OptimizedImage), 2.54)
```

This isn't an urgent fix at all, I just wonder if it's avoidable programmatically.

**Comment by gbowne-quickbase** [comment]
I tried to upload the SVG, but that's not a valid type here, so I uploaded it as a txt file
[sprint_logo.svg.txt](https://github.com/nystudio107/craft-imageoptimize/files/3699016/sprint_logo.svg.txt)

**Comment by khalwat** [comment]
ImageOptimize just uses regular old Craft CMS transforms, so this is actually an issue with Craft CMS. 

The same thing should happen if you did a regular Craft transform on the image.

So if it's something you want resolved, you'd likely need to file an issue with Pixel & Tonic. It's throwing an error inside of their code.
