### ISSUE TITLE
Imgix 404 on Craft CMS update

### ISSUE THREAD

**Issue by TheFunkyMonk** [nystudio107/craft3-imageoptimize#171]
I'm getting the following output trying to run updates on a site (both Craft CMS 3.3.6 > 3.3.7 and Retour 3.1.25 > 3.1.26):

```
Error: The "https://composer.craftcms.com/p/nystudio107/craft-imageoptimize-imgix/c642ab1cfc1bf5e4c9c3c265837b1e5201a6ed55436f1bbb47558a9c63a49384.json" file could not be downloaded (HTTP/1.1 404 Not Found)

Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Package "danielstjules/stringy" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
```

I have tried `composer clear-cache && composer update` and even `rm -rf vendor && rm composer.lock && composer install`, but still getting that error trying to run updates.

I have a suspicion this isn't completely an issue with ImageOptimize, but it's about all I have to go on with that error message. Anything I might be missing?

**Comment by khalwat** [comment]
See:

https://github.com/nystudio107/craft-imageoptimize/issues/169

& 

https://github.com/craftcms/cms/issues/5063

**Comment by brandonkelly** [comment]
@TheFunkyMonk Please try again now.

**Comment by TheFunkyMonk** [comment]
Thanks for the quick responses, guys! FYI @brandonkelly I'm still getting:

```
Error: The "https://composer.craftcms.com/p/nystudio107/craft-imageoptimize-imgix/c642ab1cfc1bf5e4c9c3c265837b1e5201a6ed55436f1bbb47558a9c63a49384.json" file could not be downloaded (HTTP/1.1 404 Not Found)

Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Package "danielstjules/stringy" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
```

in the CP, though bumping `composer.json` manually and running `composer update` did work.

**Comment by Lennso** [comment]
Sorry guys, but how can i solve the problem? composer is up to date, i cleared my caches but im still getting: 
```
error: The "https://composer.craftcms.com/p/nystudio107/craft-imageoptimize-imgix/c642ab1cfc1bf5e4c9c3c265837b1e5201a6ed55436f1bbb47558a9c63a49384.json" file could not be downloaded (HTTP/1.1 404 Not Found)
```

**Comment by khalwat** [comment]
@Lennso you get this resolved?

**Comment by brandonkelly** [comment]
We got another report of an issue with this today, so I’ll look into it again.

**Comment by Lennso** [comment]
Sorry for the delayed response. its working now! thanks

**Comment by akanshutambi811** [comment]
I have a issue while updating Craft CMS


Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for craftcms/cms 3.3.15 -> satisfiable by craftcms/cms[3.3.15].
- craftcms/cms 3.3.15 requires twig/twig ~2.12.0 -> satisfiable by twig/twig[v2.12.1, v2.12.0] but these conflict with your requirements or minimum-stability.
Problem 2
- xpertbot/craft-wheelform 2.2.4 requires craftcms/cms ^3.0.0-RC1 -> satisfiable by craftcms/cms[3.3.15].
- xpertbot/craft-wheelform 2.2.4 requires craftcms/cms ^3.0.0-RC1 -> satisfiable by craftcms/cms[3.3.15].
- xpertbot/craft-wheelform 2.2.4 requires craftcms/cms ^3.0.0-RC1 -> satisfiable by craftcms/cms[3.3.15].
- craftcms/cms 3.3.15 requires twig/twig ~2.12.0 -> satisfiable by twig/twig[v2.12.1, v2.12.0] but these conflict with your requirements or minimum-stability.
- Installation request for xpertbot/craft-wheelform 2.2.4 -> satisfiable by xpertbot/craft-wheelform[2.2.4].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
