### ISSUE TITLE
Display gallery of images

### ISSUE THREAD

**Issue by Bcdo** [nystudio107/craft3-imageoptimize#173]
I am trying to implement this with a modal gallery as well. I wish that I could use .all() so that the frontend would show all the related assets within the query.

Example
```{% set optimizedImagesRelated = rom.imageRoomRelated.all().optimizedImages %}```
Gives an error "array with keys "0, 1, 2" does not exist."

To then show it in the gallery with 
```
{% for rel in relatedAssets %}
  <div class="item">
    <img class="img-responsive" src="{{ optimizedImagesRelated.src() }}"      alt="{{ rel.title }}"         srcset="{{ optimizedImagesRelated.srcset() }}" sizes="100vw">
  </div>
{% endfor %}      
```
Any suggestions of how to get the gallery, or carousel slide to show the images optimized?

**Comment by khalwat** [comment]
So nothing would change in your original query, it should be just:

```twig
{% set relatedAssets = rom.imageRoomRelated.all()%}
```

Which gives you an array of assets. Then you'd loop through the assets, and output the optimized images:

```twig
{% for rel in relatedAssets %}
   {% set optimizedImagesRelated = rel.optimizedImages %}
  <div class="item">
    <img class="img-responsive" src="{{ optimizedImagesRelated.src() }}"      alt="{{ rel.title }}"         srcset="{{ optimizedImagesRelated.srcset() }}" sizes="100vw">
  </div>
{% endfor %}      
```

You can see examples in the docs: https://nystudio107.com/docs/image-optimize/Using.html

**Comment by Bcdo** [comment]
Thank you so much, I do not know how I missed this!
Thanks for a great plugin as well!
