### ISSUE TITLE
Volume subfolder not being parsed when set as env variable

### ISSUE THREAD

**Issue by lukeyouell** [nystudio107/craft3-imageoptimize#174]
We're using the Craft AWS plugin for our asset volume and using Imgix to handle image transforms. We've noticed that the subfolder value is set as the env variable `$AWS_BUCKET_SUBFOLDER` it isn't being parsed when called using `getAssetUri()` https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/imagetransforms/ImageTransform.php#L102

We're seeing our image urls starting with `https://foo.imgix.net/%24AWS_BUCKET_SUBFOLDER` rather than the expected subfolder. This has been confirmed by dd'ing the subfolder within `getAssetUri()` function (linked to above)

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize/commit/268f92210ffac6530348871b2388b1b34392d14f
