### ISSUE TITLE
Add aspect ratio calculator, or automatically compute smallest ratio from X and Y inputs

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft3-imageoptimize#177]
<img width="856" alt="Screen Shot 2019-11-01 at 9 39 03 AM" src="https://user-images.githubusercontent.com/2158662/68029273-46cdee00-fc8d-11e9-8d54-a1b224b86a00.png">

When pulling assets from a design file or dev tools, it's usually easier to pull image dimensions as pixel values rather than an aspect ratio. It would be a time saver to be able to put in something like this:

`aspectRatioX` field value:1000 
`aspectRatioY` field value: 882

Ideally ImageOptimize would take this and figure out the aspect ratio to use from there. Alternatively, to provide some sort of calculator could also work, but may be a bit messy in the UI.

**Comment by khalwat** [comment]
So... you should be able to do this already? Image Optimize doesn't care what you put into the aspect ratio fields, they don't have to be reduced to any lowest common denominator.

**Comment by wbrowar** [comment]
You’re right. It seems to be working as expected. No need to change it.
