### ISSUE TITLE
SVG Thumbs Not Rendering

### ISSUE THREAD

**Issue by smockensturm** [nystudio107/craft3-imageoptimize#178]
Hello. What might cause an SVG thumbnail (which are essentially transforms) to fail rendering in the Control Panel?

Yes, we have the ignore SVG box checked, still no thumbs.

Cleared cache. Rebuilt indexes. Et cetera.

Craft Pro 3.3.15
ImageOptimize 1.6.4

**Comment by khalwat** [comment]
This should work, I'll have a look

**Comment by khalwat** [comment]
So I tested this, and it appears to be working here... can you give me information on your setup in terms of the driver (GD or Imagick) and general server setup?

![Screen Shot 2020-01-08 at 11 48 54 AM](https://user-images.githubusercontent.com/7570798/72000516-7c550180-3211-11ea-82b7-e651dbd1d7ef.png)

**Comment by smockensturm** [comment]
Sure.

PHP version | 7.3.13
Linux 3.10.0-693.11.6.1.ELK.el6.x86_64
MySQL 5.6.41
Imagick 3.4.3 (ImageMagick 6.7.2-7)
Craft Pro 3.3.15

Would you like admin access to the CP for a firsthand look?

**Comment by khalwat** [comment]
Sounds good, hit me up on Discord to work out the details?

**Comment by khalwat** [comment]
Gonna chalk this up to CloudFront configuration unless other information comes to light.

**Comment by smockensturm** [comment]
Still not rendering SVG thumbs with your plugin enabled. What else should I be looking for?

**Comment by khalwat** [comment]
I can have a look at it again today if you like; is the CloudFront issue all sorted out?

**Comment by smockensturm** [comment]
We have set the base url, distribution id and prefix. Cleared caches, everything looks jake on the front end. So... yes?

**Comment by smockensturm** [comment]
Hello. Thought we'd try a brand new local asset volume (no S3, no cloudfront) and see what happens. And it appears no CP thumbs of _any_ kind are rendering.

Also looks like the cloudfront base URL that we set for the Sharp service in your plugin is taking over rendering of the CP thumbs. Is that accurate?

**Comment by khalwat** [comment]
Yep that's correct, if you change the Transform Method, that changes it for everything. And this normally works fine, I have a number of sites where I'm using Imgix or Sharp for the transform method without incident.

What I'm curious to hear is if you're able to try a transform in a frontend template (just using a regular Craft transform) to see if that works.

I'm wondering if perhaps Sharp doesn't support transforming svg to other formats? Or if something else just isn't configured properly?

Can you check your browser's JavaScript console for errors on the Asset Index page (where thumbnails are shown) and then also zip up and send me all of your logs in `storage/logs/` so I can see if errors are being logged.

It'd be helpful if you set `devMode` to `true` on the site, and deleted all of the logs, and then reloaded the Asset Index page, and sent me the resulting logs in `storage/logs/` -- feel free to send them on Discord.

**Comment by smockensturm** [comment]
> What I'm curious to hear is if you're able to try a transform in a frontend template (just using a regular Craft transform) to see if that works.

I can confirm that it does for a jpg, not for an SVG.

> Can you check your browser's JavaScript console for errors on the Asset Index page

Sure. There are none.

> It'd be helpful if you set devMode to true on the site, and deleted all of the logs, and then reloaded the Asset Index page, and sent me the resulting logs in storage/logs/ -- feel free to send them on Discord.

Done and done.

**Comment by smockensturm** [comment]
I don't know if this is related or not, but if source files have an all caps extension (.JPG) the Sharp service also fails to send back a usable thumbnail.

**Comment by khalwat** [comment]
> I don't know if this is related or not, but if source files have an all caps extension (.JPG) the Sharp service also fails to send back a usable thumbnail.

For sure this seems like a bug in Sharp

**Comment by khalwat** [comment]
It was noted in this other issue: https://github.com/nystudio107/craft-imageoptimize/issues/187

...that the changes made fixed the issue for him using Sharp. I'll be releasing that build today.

**Comment by smockensturm** [comment]
This should be re-opened.

Why isn't your plugin rendering SVG thumbnails using the Sharp service when clearly the format *can* be processed?

<img width="1285" alt="Screen Shot 2020-02-05 at 5 17 34 PM" src="https://user-images.githubusercontent.com/6586518/73889345-7452a680-483d-11ea-8dd6-4497ce65f312.png">

**Comment by khalwat** [comment]
Another question would be: why does it properly render SVG thumbnails using Imgix and Thumbor?

Clearly something is amiss here.

**Comment by khalwat** [comment]
I merged in your PR (thank you for that) -- does this fix the issue for you?

**Comment by smockensturm** [comment]
Yes it does.

**Comment by khalwat** [comment]
Awesome, thanks for your patience & work on this. I'll cut a release tomorrow.

**Comment by khalwat** [comment]
Released: https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.9
