### ISSUE TITLE
Ability to hide Sub-folder list on variant setting page

### ISSUE THREAD

**Issue by theurbanu** [nystudio107/craft3-imageoptimize#179]
I have a setup where Craft dynamically creates a new sub-folder for every entry created. I will soon have hundreds of entries once all the content is added and would like to have a way to hide the sub-folder list on this page if possible. Thanks for your consideration!

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-imageoptimize/commit/6cd570c1e47c5d912af12b478b42a05744992ffd
