### ISSUE TITLE
Missing field type

### ISSUE THREAD

**Issue by E2design** [nystudio107/craft3-imageoptimize#18]
Installed version 1.3.2

Trying to add a ImageOptimize field. Can select it from the field type dropdown but after saving the field it responds with: "The field type “nystudio107\imageoptimize\fields\OptimizedImages” could not be found."

https://d.pr/free/i/ndVNxZ

**Comment by khalwat** [comment]
Is the plugin installed? Does that file actually exist on disk at `nystudio107.com/imageoptimize/fields/OptimizedImages.php`?

I'd suggest trying to re-install it, something isn't right.

**Comment by khalwat** [comment]
It's there in the repo:

https://github.com/nystudio107/craft3-imageoptimize/blob/master/src/fields/OptimizedImages.php

**Comment by E2design** [comment]
Plugin installed and file is there https://d.pr/free/i/XggnIn
However I do notice that the directory differs: (/craft3-imageoptimize/ vs. /imageoptimize/)
`nystudio107.com/craft3-imageoptimize/src/fields/OptimizedImages.php?`
Its installed using composer:
`composer require nystudio107/craft3-imageoptimize`

**Comment by khalwat** [comment]
yeah that's okay, Composer takes care of mapping it.

Is there anything interesting/useful in your `storage/logs/`?

**Comment by khalwat** [comment]
What version of Craft 3 are you running?

Did you create the Field with an older version of ImageOptimize, and then update it to a newer version?

Try deleting the field, and re-adding it (you can use the same name).

**Comment by E2design** [comment]
Nothing worth mentioning in the storage logs.

Uninstalled the plugin and removed all files manually. Reinstalled the files with composer and activated the plugin. The issue remains. I'm working locally using MAMP pro.

**Comment by khalwat** [comment]
Did you delete the Field when you uninstalled and re-installed the plugin though?

**Comment by khalwat** [comment]
If that doesn't work, you can try deleting `vendor/` and `composer.lock` and running `composer install` from scratch to make sure it isn't some weird Composer issue.

**Comment by E2design** [comment]
I'm on Craft beta 34.
I created the field using the latest version of imageoptimize.
Removing the field didn't help either. Adding a completely new field with a different name creating the same issue.
`composer dump-autoload ` no positive results
reinstalling composer no results

**Comment by khalwat** [comment]
Are you able to use _any_ plugin-provided Fields in your Craft 3 setup? Try:

https://github.com/craftcms/store-hours

-or-

https://github.com/nystudio107/craft3-recipe

**Comment by E2design** [comment]
The redirect plugin from Dolphiq was causing the issue.
All of the third-party plugin fields ended up with the same error.

Uninstalling the redirect plugin solved the issue.
