### ISSUE TITLE
Ignore SVG and Image Format

### ISSUE THREAD

**Issue by sgtpenguin** [nystudio107/craft3-imageoptimize#180]
It appears that the ignore svg option only works if the lowest width transform is set to "Auto" format.  When I set it to jpg, it no longer "ignores svg" and instead creates an ugly looking .jpg transform.

Perhaps this is by design but feels counter-intuitive to me and took me a while to diagnose.

Thanks for the great plugin!  It is truly well thought out and works wonders.

**Comment by khalwat** [comment]
In this case, I think it's trying to convert the SVG to a JPG (or at least that's what it thinks you want it to do) -- which should look nice, depending on your graphics driver.

But I guess if you tell it to completely ignore a format, you probably would expect it to completely ignore it?

**Comment by khalwat** [comment]
I've traced through the code, and I'm not seeing the behavior that you're describing:

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/services/OptimizedImages.php#L185

It just doesn't create any variants at all if you have told it to ignore that file type.

**Comment by sgtpenguin** [comment]
Apologies for not responding.  I completely forgot about this and in an unrelated incident today realized I had filtered all my github notifications.  I really appreciate you taking the time to look into it.

I was able to reproduce this again by just changing my lowest size variant (576px) to jpeg instead of auto.  Here's a before + after.
<img width="608" alt="Screenshot 2020-02-14 15 27 33" src="https://user-images.githubusercontent.com/16600959/74565451-3ccfb280-4f3f-11ea-8d5a-ca459ff93857.png">
<img width="611" alt="Screenshot 2020-02-14 15 27 20" src="https://user-images.githubusercontent.com/16600959/74565459-3f320c80-4f3f-11ea-9468-b82132446fe6.png">

> But I guess if you tell it to completely ignore a format, you probably would expect it to completely ignore it?

Yes.

> It just doesn't create any variants at all if you have told it to ignore that file type

I see what you're saying.  It's strange though –– with "auto" on (and only on the smallest varient) I get served the svg file but from a folder for that variant size.  so my srcset ends up being:

`/assets/_576x576_crop_center-center_60_line/PetrialServices_191108_205916.svg 576w`

maybe that's a clue?

Here are my settings for the field...
<img width="667" alt="Screenshot 2020-02-14 15 36 48" src="https://user-images.githubusercontent.com/16600959/74565931-4ad20300-4f40-11ea-81c8-553acfbcce7a.png">
<img width="312" alt="Screenshot 2020-02-14 15 36 50" src="https://user-images.githubusercontent.com/16600959/74565933-4ad20300-4f40-11ea-86fd-c580e482d931.png">
<img width="336" alt="Screenshot 2020-02-14 15 36 54" src="https://user-images.githubusercontent.com/16600959/74565934-4b6a9980-4f40-11ea-9cb8-110bf34e7576.png">
<img width="402" alt="Screenshot 2020-02-14 15 36 59" src="https://user-images.githubusercontent.com/16600959/74565935-4b6a9980-4f40-11ea-8e10-046c387d1e37.png">
<img width="410" alt="Screenshot 2020-02-14 15 37 04" src="https://user-images.githubusercontent.com/16600959/74565936-4b6a9980-4f40-11ea-8dff-bbc5887ac968.png">

**Comment by khalwat** [comment]
Looks like I dropped the ball on this one. If this is still a problem @sgtpenguin please add to the ticket, and I will re-open.
