### ISSUE TITLE
[FR] colorPalette in RGBA

### ISSUE THREAD

**Issue by thefubon** [nystudio107/craft3-imageoptimize#181]
{{ optimizedImages.colorPalette[0] }}

Everything turns out very cool, I can’t understand how to draw a conclusion like this. How to output in RGBA. So that I can use c in gradient as in the examples below
<img width="712" alt="Снимок экрана 2019-12-16 в 10 33 53" src="https://user-images.githubusercontent.com/43171309/70887686-970bd000-1fef-11ea-8792-fcbbc82c88fe.png">

```
{% css %}
  .uk-overlay-secondary {
    background: -webkit-gradient(linear, left top, right top, from(rgba(0, 0, 0, 0)), to(rgba(0, 0, 0, 0.75)));
    background: -webkit-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5));
    background: -moz-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5));
     background: -o-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5));
    background: -ms-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5));
    background: linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5));
    background-color: rgba(0, 0, 0, 0);
   }
{% endcss %}
```

**Comment by khalwat** [comment]
You'd have to use an algorithm to convert the `#XXXXXX` hex colors into RGBA.

Seems like it might be a nifty feature to add though?

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-imageoptimize/commit/91a0acd480818a3e08b6a7295add616aae90bc4a
