### ISSUE TITLE
Images not rendering/processing properly

### ISSUE THREAD

**Issue by johnnymueller** [nystudio107/craft3-imageoptimize#182]
Hello there,

I'm having issues with some of my image variants not being processed properly. Out of ~130 images I'm only seeing 2 that are having this error for the largest variant I've created. I've tried clearing caches and reindexing and even re-uploading, but some images look as if they only rendered halfway and the rest of the image is a solid color block similar to the placeholder SVG.

![Screen Shot 2019-12-16 at 11 53 26 AM](https://user-images.githubusercontent.com/369241/70934259-c4aa4680-1ffa-11ea-8e13-0eee994f24d5.png)

Any thoughts on what's going on?

**Comment by khalwat** [comment]
If I had to guess, it'd be that your instance is running out of either execution time or RAM attempting to do the large image transform.

Likely it's running out of RAM. Can you give me details on your hosting setup/environment?

**Comment by johnnymueller** [comment]
I think you're right. We're using Arcustech and I just double checked the Memory Limit and we're at 128M instead of 256M. I'll bump it up and see if that fixes things.

Will I need to do anything to re-trigger the transforms for these images?

**Comment by khalwat** [comment]
Just re-save the Asset volume and away you go!

**Comment by johnnymueller** [comment]
Thanks! That did the trick :)
