### ISSUE TITLE
Cropped images not updating (using IO + Imgix)

### ISSUE THREAD

**Issue by jakedohm** [nystudio107/craft3-imageoptimize#183]
Hi Andrew!

We’re running into an issue where image edits using the built-in image editor aren’t being properly saved. I thought this was a Craft issue, because it didn't even cross my mind it could've been an Image Optimize issue, but when Andris dug in he said Craft is doing it's job properly. Here's his response:

> Have a feeling like you might be barking up the wrong tree for this one - after editing the image, Craft makes all the right calls, including getting the fresh element html code to update the Asset input with the new thumbnail, except that gets hijacked and you get this in response:

```
{"html":"[redacted] <div class='elementthumb' data-sizes='30px' data-srcset='https://poshcouturerentals.imgix.net/uploads/images/Products/Amber_Louis_Ghost_Chair_Front_side.jpg?auto=compress%2Cformat&crop=focalpoint&domain=poshcouturerentals.imgix.net&fit=crop&fp-x=0.5&fp-y=0.5&ixlib=php-2.3.0&w=30 30w, https://poshcouturerentals.imgix.net/uploads/images/Products/Amber_Louis_Ghost_Chair_Front_side.jpg?auto=compress%2Cformat&crop=focalpoint&domain=poshcouturerentals.imgix.net&fit=crop&fp-x=0.5&fp-y=0.5&ixlib=php-2.3.0&w=60 60w, https://poshcouturerentals.imgix.net/uploads/images/Products/Amber_Louis_Ghost_Chair_Front_side.jpg?auto=compress%2Cformat&crop=focalpoint&domain=poshcouturerentals.imgix.net&fit=crop&fp-x=0.5&fp-y=0.5&ixlib=php-2.3.0&w=100 100w, https://poshcouturerentals.imgix.net/uploads/images/Products/Amber_Louis_Ghost_Chair_Front_side.jpg?auto=compress%2Cformat&crop=focalpoint&domain=poshcouturerentals.imgix.net&fit=crop&fp-x=0.5&fp-y=0.5&ixlib=php-2.3.0&w=200 200w'></div><div class=\"label\"><span class=\"title\">Amber_Louis_Ghost_Chair_Front_side</span></div></div>","headHtml":"[redacted]"}
```

Here’s a screen recording of the issue: https://www.dropbox.com/s/aa23zeen2ynqx6o/Craft%20Image%20Editor%20Bug.mov?dl=0

**Comment by khalwat** [comment]
My guess is that the image is cached on Imgix's end, and because none of the parameters changed, it has no reason to think it needs to invalidate the image.

**Comment by khalwat** [comment]
So there actually is code in there already to do the purging. Before an asset is replaced we purge the URL:

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/ImageOptimize.php#L344

...and then after it is replaced, we re-generate it:

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/ImageOptimize.php#L363

And then in the Imgix Image Transform method, it grabs the purge URL, and then sends it off to Imgix:

https://github.com/nystudio107/craft-imageoptimize-imgix/blob/v1/src/imagetransforms/ImgixImageTransform.php#L216

Note that Imgix does not guarantee that this process happens immediately:

https://docs.imgix.com/setup/purging-images

And indeed, they recommend:

> To absolutely ensure compliance for an updated image, it is best to give the image a new path by renaming the file. Purging an image is only recommended when absolutely necessary.

That said, it's *possible* that something isn't working as intended in the purge system that is already in place in Image Optimize. 

If you do this editing test locally with `devMode` on, do you see in the logs where Image Optimize is attempting to purge the URL? Any errors reported?

If you manually purge the image, what happens?

**Comment by khalwat** [comment]
Will re-open if more information is provided
