### ISSUE TITLE
some images returning 404 with imgix

### ISSUE THREAD

**Issue by proximo7** [nystudio107/craft3-imageoptimize#184]
When we enable imgix with image optimize some images return 404 but not all. In addition, when any new images are added those images also return 404 in the control panel and on the front end. I've tried deleting all transforms, rebuilding asset index, resaving asset volume but still get the same problem. I cannot see any pattern to the errors either. All the images are standard jpg files. Changing the transform method to Craft fixed everything.

Craft 3.3.19
ImageOptimize 1.6.6

**Comment by khalwat** [comment]
Can you give me example of URLs that work, and URLs that do not work?

Can you test this in local dev with `devMode` on and see if ImageOptimize logs any useful information?

**Comment by khalwat** [comment]
Will re-open if more information is provided
