### ISSUE TITLE
[FR] Option to include image heights in srcset

### ISSUE THREAD

**Issue by dguillory** [nystudio107/craft3-imageoptimize#186]
In some cases, like using [lazysizes with object-fit](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/object-fit), it's useful to have the heights included in the srcset:

`large.jpg 1600w 900h, medium.jpg 800w 450h`

Would it be possible to have the option to get a srcset string with heights (that can be accessed via graphQL)?

**Comment by khalwat** [comment]
mmmm I'll have to think on this one, because that's specific to LazySizes alone.

Probably I'll come up with a more general solution.
