### ISSUE TITLE
Disable SVG transform

### ISSUE THREAD

**Issue by umkasanki** [nystudio107/craft3-imageoptimize#187]
Hi guys!
I use ImageOptimize with Sharp / AWS Serverless Image Handler.
I have an issue with generation thumbnails of SVG assets in the CP.

![изображение](https://user-images.githubusercontent.com/496132/72702957-5f032a00-3b65-11ea-95bf-c00db659f631.png)

The asset link doesn't work correctly:

![изображение](https://user-images.githubusercontent.com/496132/72703054-a12c6b80-3b65-11ea-8808-a6f49bd98a94.png)

Then I try to open asset link instead SVG I see the code of svg:

![изображение](https://user-images.githubusercontent.com/496132/72703100-bf926700-3b65-11ea-889f-b50fe4625781.png)

Then I try to use svg in the frontend I get the same problem:

![изображение](https://user-images.githubusercontent.com/496132/72703367-78f13c80-3b66-11ea-96e4-011f88bdbffa.png)
![изображение](https://user-images.githubusercontent.com/496132/72703390-84dcfe80-3b66-11ea-908c-ae73cc8d77b7.png)

Amazon S3 1.2.5
ImageOptimize 1.6.7
Craft Pro 3.3.20.1

**Comment by smockensturm** [comment]
Same. Good luck with this. Let me know what you come up with.

**Comment by khalwat** [comment]
Yep, it's the same as this issue: https://github.com/nystudio107/craft-imageoptimize/issues/178

It appears to be a limitation in the AWS implementation of their Serverless Image Transform service.

I've put some code into the latest develop version of Image Optimize, you can try it out by changing your semver to:

```
"dev-develop as 1.6.8"
```

...and then doing `composer update`

Let me know how you go in the other thread.

**Comment by simeon-smith** [comment]
This works for me. When is 1.6.8 planned for release?

**Comment by khalwat** [comment]
Great @simeon-smith -- I will issue a release on Monday the 27th of January, 2020.

**Comment by smockensturm** [comment]
Hey there @simeon-smith would you mind sharing your Sharp setup? How what are you using for that?

This bit?

https://nystudio107.com/blog/setting-up-your-own-image-transform-service

We're still having trouble rendering SVG thumbnails. (Renders SVG _variants_ no problem... but no thumbs. No thumbs. No ^&@%*^$ thumbs.

<img width="1285" alt="Screen Shot 2020-02-05 at 5 17 34 PM" src="https://user-images.githubusercontent.com/6586518/73888422-99461a00-483b-11ea-988a-03585fd60a70.png">

**Comment by simeon-smith** [comment]
@smockensturm, I don't have it displayed in the CMS. But the URL works with that change, which it didn't before.

**Comment by smockensturm** [comment]
@simeon-smith So you don't have SVG thumbnails in the CP either?

**Comment by umkasanki** [comment]
Fixed on frontend 
![изображение](https://user-images.githubusercontent.com/496132/73950841-acc1b580-490d-11ea-815b-4e6f0964e602.png)

But on CP problem still exist(
Thumbnail not working.
![изображение](https://user-images.githubusercontent.com/496132/73951004-f4e0d800-490d-11ea-9b86-64fe38896249.png)
