### ISSUE TITLE
Unable to configure Imgix; blank CP

### ISSUE THREAD

**Issue by howells** [nystudio107/craft3-imageoptimize#189]
I'm at a complete loss as to how to confirm Image Optimize for Imgix. My image-optimize.php is as follows:

```
return [

    '*' => [

    ],

    'dev' => [
        'transformClass' => CraftImageTransform::class,
    ],

    'production' => [
        'transformClass' => ImgixImageTransform::class,
        'imageTransformTypeSettings' => array(
            'domain' => 'xxxxxx.imgix.net',
            'apiKey' => 'xxxxxx',
            'securityToken' => 'xxxxxx',
        ),

    ],

];
```

Yet my images are still being served as Craft transforms, and when I visit the Image Optimize CP in production it's just blank: 

<img width="1069" alt="Screenshot 2020-01-31 at 10 10 28" src="https://user-images.githubusercontent.com/145849/73531266-f7c16180-4411-11ea-9015-7ebb4ec89339.png">

Any idea of where I'm messing up here would be hugely appreciated!

EDIT: in my logs I now get an error when trying to view entries: `Class ImgixImageTransform does not exist` - is `ImgixImageTransform::class` not correct?

**Comment by khalwat** [comment]
This is my fault, it's not documented properly.

I've updated the `config.php` docs: https://github.com/nystudio107/craft-imageoptimize/commit/4f7cd7221ad746b96accfa92fded74a13e50d721

```php
    /**
     * @var array Settings for the image transform components
     *
     * The data is stored in the following format, with the key being the class
     * of the image transform method:
     *
     * 'imageTransformTypeSettings' => [
     *    ImgixImageTransform::class => [
     *        'domain' => 'XXXXX',
     *        'apiKey' => 'XXXXX',
     *        'securityToken' => 'XXXXX',
     *    ]
     * ],
     */
    'imageTransformTypeSettings' => [],
```

Typically you shouldn't need to change the type of the transform from environment to environment though.

**Comment by howells** [comment]
Perfect - I actually managed to get it to work but isn't as clean as this.

**Comment by howells** [comment]
Afraid I'm still having problems here: given this config file, my images are alwasy processed using Imgix, instead of Craft on dev:

```
<?php

use nystudio107\imageoptimize\imagetransforms\CraftImageTransform;
use nystudio107\imageoptimize\imagetransforms\ImgixImageTransform;

return [

    '*' => [
        'autoSharpenScaledImages' => false,
    ],

    'dev' => [
        'transformClass' => CraftImageTransform::class,
    ],

    'production' => [

        'transformClass' => ImgixImageTransform::class,

        'imageTransformTypeSettings' => [
            ImgixImageTransform::class => [
                'domain' => 'xxxx.imgix.net',
                'apiKey' => 'xxx',
                'securityToken' => 'xxx',
            ],
        ],

    ],

];
```

Any ideas where i'm going wrong?

**Comment by khalwat** [comment]
Check your `storage/logs/web.log` for `[error]`s

**Comment by howells** [comment]
`Failed to instantiate component or class "ImgixImageTransform".`

Really don't know where to go from here. I tried requiring `nystudio107/craft-imageoptimize-imgix` explicitly, but doesn't make a difference.

**Comment by howells** [comment]
Re: your earlier point:

> Typically you shouldn't need to change the type of the transform from environment to environment though.

My local dev image source is different to my production source, the former not being available online so I wouldn't be able to map an Imgix source to it, which is why I'm trying to do this.

**Comment by khalwat** [comment]
Yep, the problem is in your namespace -- it should be:

```php
<?php

use nystudio107\imageoptimize\imagetransforms\CraftImageTransform;
use nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform;
```

see: https://github.com/nystudio107/craft-imageoptimize-imgix/blob/v1/src/imagetransforms/ImgixImageTransform.php#L11

The Imgix Image Transform is in a separate Composer package, and thus a separate namespace from ImageOptimize itself.

**Comment by howells** [comment]
I figured it out by crawling through the source :-) thanks
