### ISSUE TITLE
Cannot upload new file on craft 3.0.0-beta.35 and 36

### ISSUE THREAD

**Issue by robinleblon** [nystudio107/craft3-imageoptimize#19]
Uploading a new image to an Asset location with OptimizedImage field, yields this error.

<img width="476" alt="screen shot 2017-11-30 at 00 10 35" src="https://user-images.githubusercontent.com/274523/33404076-40134518-d563-11e7-8d9a-a254fc0af2f4.png">

**Comment by khalwat** [comment]
Thanks, I know what's going on. Will fix it shortly

**Comment by khalwat** [comment]
This is fixed in 1.3.3:

https://github.com/nystudio107/craft3-imageoptimize/releases/tag/1.3.3
