### ISSUE TITLE
Image transforms with graphQL

### ISSUE THREAD

**Issue by Toni-hr98** [nystudio107/craft3-imageoptimize#190]
https://nystudio107.com/docs/image-optimize/ Can someone help me with the image-optimize plugin brought by Nystudio107.

I am using it headless, with graphql. But I want to use the default craft image transformer... So i can query images like this:

 ... on amazon_Asset {
                    optimizeImages {
                        src
                        srcset
                        srcWebp
                        srcsetWebp @transform(handle: "testo")
                        maxSrcsetWidth
                        placeholderImage
                        placeholderBox
                        placeholderSilhouette
                    }
                }

**Comment by khalwat** [comment]
I answered this in Discord, but essentially, ImageOptimize pre-generates all of the image transforms, so you can't add them post-facto.

Think of each Optimized Images field as a wrapper for a `srcset` -- if you need a different `srcset` for art direction reasons, then you'd want a new Optimized Images field.

You can add as many fields as you want to an Asset Volume, but it'll pre-generate all of the images whether you need them or not. You can limit this by a per-subfolder basis to help mitigate this.
