### ISSUE TITLE
problems with ImageOptimize after install

### ISSUE THREAD

**Issue by ballmannweber** [nystudio107/craft3-imageoptimize#196]
1. the plugin lists tools like jpegoptim, gifsicle or optipng as not installed but they are… but the shown paths are wrong.
2. you write that we should “copy the imageoptimize/config.php file to Craft's config/ directory, renaming it to image-optimize.php, and make your changes there to override default settings.“ but we cannot find that a directory named „ imageoptimize“ or that config-file.
<img width="1399" alt="Bildschirmfoto 2020-03-16 um 16 16 21" src="https://user-images.githubusercontent.com/5177628/76805743-f12f5380-67df-11ea-8b2e-cb51ad94c770.png">

**Comment by khalwat** [comment]
You need to correct the paths. Copy the `config.php` file to your Craft `config/` directory, and rename it `imageoptimize.php`

You can find details here: https://nystudio107.com/docs/image-optimize/Configuring.html#native-craft-images

> The only configuration for ImageOptimize is in the config.php file, which is a multi-environment friendly way to store the default settings. Don't edit this file, instead copy it to craft/config as image-optimize.php and make your changes there.

**Comment by ballmannweber** [comment]
I understood this but can't find a config.php anywhere. where is that file on the server?

**Comment by khalwat** [comment]
Ah, sorry! It's in the plugin's root directory, so in your local install:

`vendor/nystudio107/craft-imageoptimize/src/config.php`

or you can see it here:

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/config.php
