### ISSUE TITLE
[FR] Create a utility that displays the same library info as on the Settings screen

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft3-imageoptimize#198]
In a setup where Project Config is used and in an environment where `allowAdminChanges` has been set to false, it would still be great to see the status of the image libraries as you can see them on the Settings page.

A Utility seems to make sense for this and it could also house action buttons for some of the commonly used console commands to give it more of a reason to be there, even when you are using a third-party service.

**Comment by khalwat** [comment]
I like it.

**Comment by wbrowar** [comment]
Bumping this again. If not a Utility then it might be nice as a console command to tell you what libraries are installed and set up for use. Either way, being able to see what libraries are on without diving into the installed packages on the server or turning admin changes back on in a production site would be great.

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.21
