### ISSUE TITLE
GraphQL only pulls back JPG's

### ISSUE THREAD

**Issue by joebentaylor1995** [nystudio107/craft3-imageoptimize#199]
For some reason when using this plugin, the returned result is always a bad quality JPG.

This is my GraphQL:
`
query MyQuery {
  craft {
    entry(slug: "mission") {
      ... on CRAFT_pages_mission_Entry {
        missionPhilosophyImage {
          ... on CRAFT_generalImages_Asset {
            optimizedImages {
              optimizedImageUrls
              srcsetWebp
              srcset
              optimizedWebPImageUrls
              src
              srcWebp
            }
          }
        }
      }
    }
  }
}

`

and my returned result (baring in mind this is an uploaded PNG image)
`
{
  "data": {
    "craft": {
      "entry": {
        "missionPhilosophyImage": [
          {
            "optimizedImages": {
              "optimizedImageUrls": [
                "https://s3.us-east-1.amazonaws.com/levinriegner-website-images/_576x432_crop_center-center_60_line/16558/philosophy.jpg"
              ],
              "srcsetWebp": "https://s3.us-east-1.amazonaws.com/levinriegner-website-images/_576x432_crop_center-center_60_line/16558/philosophy.jpg.webp 576w",
              "srcset": "https://s3.us-east-1.amazonaws.com/levinriegner-website-images/_576x432_crop_center-center_60_line/16558/philosophy.jpg 576w",
              "optimizedWebPImageUrls": [
                "https://s3.us-east-1.amazonaws.com/levinriegner-website-images/_576x432_crop_center-center_60_line/16558/philosophy.jpg.webp"
              ],
              "src": "https://s3.us-east-1.amazonaws.com/levinriegner-website-images/_576x432_crop_center-center_60_line/16558/philosophy.jpg",
              "srcWebp": "https://s3.us-east-1.amazonaws.com/levinriegner-website-images/_576x432_crop_center-center_60_line/16558/philosophy.jpg.webp"
            }
          }
        ]
      }
    }
  }
}
`

**Comment by khalwat** [comment]
So ImageOptimize will convert the images to whatever you tell it to.

My guess is that in this case, the field was set up to always convert to `.jpg` format, probably with reasonably high compression on it.

You can adjust these settings in the Field settings, including a "none" setting to cause it to not force an image format conversion, if that's what you want.
