### ISSUE TITLE
Deleted images should be purged from Imgix

### ISSUE THREAD

**Issue by juresrpcic** [nystudio107/craft3-imageoptimize#20]
When an image is deleted from Craft entirely (from assets), it should probably also call the "purge image" API call on Imgix / [imgix docs link](https://docs.imgix.com/setup/purging-images):

```bash
curl "https://api.imgix.com/v2/image/purger" \
  -u "$API_KEY:" \
  -d "url=$URL_TO_PURGE"
```

Not sure what to do about the cached transforms when an image is purged - Imgix says it changes cache headers, but I was getting the old image (after manually purging the image from Imgix dashboard) until I did a hard reset in Chrome ("Empty cache and hard reload").

**Comment by khalwat** [comment]
Yep, good point. I'll do this.

**Comment by khalwat** [comment]
Done in ImageOptimize 1.4.0:

https://github.com/nystudio107/craft3-imageoptimize/releases/tag/1.4.0
