### ISSUE TITLE
Error when processing through CLI

### ISSUE THREAD

**Issue by bartrylant** [nystudio107/craft3-imageoptimize#200]
I've installed Image Optimize on an existing Craft site (images hosted on S3 with CloudFront). Because there are already lots of images on this website, I thought it was a good idea to run `./craft image-optimize/optimize/create`. However, after processing 335 from 14569, I got `Het bestand “/home/xxxxx/webapps/xxxxx/storage/runtime/assets/sources/15909.jpg” lijkt geen afbeelding te zijn.` (File does not seems to be an image.)

3 questions:
- Why does it look for pictures inside the storage folder? Every uploaded file is in S3
- The file is an image, while the plugin says it is not
- How can I resume the processing without doing the first 335 images again?

Craft 3.4.16, php 7.4.4

**Comment by khalwat** [comment]
Images are always downloaded before they are transformed. That's just how Craft transforms work, and Image Optimize just uses regular old Craft transforms to do its thing.
