### ISSUE TITLE
Remove mtime and focal from url

### ISSUE THREAD

**Issue by redkrupp** [nystudio107/craft3-imageoptimize#202]
I just switched from local assets to digitlaocean spaces via plugin - https://plugins.craftcms.com/dospaces

what I've noticed is that the transforms URL's have changed to ugly ones

    _300x189_crop_center-center_line/golden.png.webp?mtime=20200425014445&focal=none

is there a way to remove mtime and focal strings from the final address?

**Comment by khalwat** [comment]
This would be up to the Digital Ocean Spaces plugin, it must be adding it -- Image Optimize doesn't add those URL params.
