### ISSUE TITLE
Insane long page due to folder listing

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-imageoptimize#203]
![Screenshot 2020-05-17 at 10 17 41](https://user-images.githubusercontent.com/1286410/82140513-4d8a1000-982f-11ea-9fc7-29902ee346fe.jpg)

Also takes some serious time to load in our case...

**Comment by khalwat** [comment]
How/why are there so many folders in this asset volume?

I guess I could have an option to disable this feature if you like?

**Comment by saltymouse** [comment]
This came up for me as well for optimized images in blog posts. The image asset field's "Default Asset Location" is set to `<VolumeName>: {owner.slug}` for organizational purposes (knowing which image belongs to which blog post).

A "Show more/less" toggle after 10 or so items might work.

**Comment by khalwat** [comment]
Maybe I can just not display them if there are, say, > 20 of them (because it's really unlikely you're going to be doing anything per-subfolder in that case)?

**Comment by saltymouse** [comment]
That would work for me. Indeed, I think it's safe to assume sub-folders would just inherit optimizations from the parent folder if it gets that long.

**Comment by khalwat** [comment]
You can completely disable this via the Plugin Settings too.

**Comment by saltymouse** [comment]
I still have a few sub-folder optimizations I'm using on other volumes, so I still need that setting for now. I'll look into that setting ("Limit by Sub-Folder") if the sub-folders get too unwieldy, in which case I'll reorganize those remaining sub-folders into their own asset volumes, which will allow me to turn off that setting.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize/commit/400b08341cd8923ee78238b50501e4aab67e49f0
