### ISSUE TITLE
This is not an image that can be manipulated

### ISSUE THREAD

**Issue by isteinacker** [nystudio107/craft3-imageoptimize#205]
Hi - trying to set up image optimize, getting _"This is not an image that can be manipulated"_ for each of the images in the library.

Transform Method is Craft, Image Processors and Image Variant Creators show up as installed OK in the settings.

<img width="1115" alt="Screenshot 2020-05-31 at 12 32 09" src="https://user-images.githubusercontent.com/66203343/83350215-eb570200-a33a-11ea-8e7c-96ca8a71ced8.png">

after the initial installation of the plug in, optimized images were not showing in the image details dialog. after I installed the last craft updates it was working, then after changing one setting in the images-optimized.php config it is not working again - also when using the old settings.

[dynamically creating image variants](https://nystudio107.com/docs/image-optimize/Using.html#dynamically-creating-optimized-image-variants) is working fine.

when setting the _"allowUpScaledImageVariants"_ to true error message showing _"This is not an image that can be manipulated or the images would all be up-scaled"_ even though images are huge.

**Comment by khalwat** [comment]
@isteinacker what change did you make to the `images-optimized.php config` that caused it to not work afterwards?

Can you post your `images-optimized.php config` here?

**Comment by khalwat** [comment]
Will re-open if more info is given
