### ISSUE TITLE
[FR] Ability to run CLI commands on a specific Asset Volume

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [nystudio107/craft3-imageoptimize#207]
I love this plugin, but I think it could be handy to have a CLI command that would allow us to run asset field variants on a specific volume:

I have a few sources that I'm attaching various field variants to like Uploads and Listings. On the Listings volume I'm attaching just a single variant on it. I know that we have these options already:

```
- image-optimize/optimize                          Optimize Command
    image-optimize/optimize/create                 Create all of the OptimizedImages Field variants by creating all of the
    image-optimize/optimize/create-asset           Create a single OptimizedImage for the passed in Asset ID
```
But I think being able to do something like ` image-optimize/optimize/create-asset-volume` that would only run the variants on a specific volume would be helpful. This way we wouldn't have to create `all of the variants`.

This is a feature request and thank you for creating such an amazing tool!

**Comment by khalwat** [comment]
This was added in 1.6.18 -> https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.18
