### ISSUE TITLE
Flip image

### ISSUE THREAD

**Issue by umkasanki** [nystudio107/craft3-imageoptimize#209]
Hello.
It seems something wrong with saving images after flipping in Craft images editor.
All functions (rotate and cropping..) works good but not flip vertical/horisontal...

See video: https://youtu.be/tgFYIH8loik

Craft:: 3.4.22.1
Amazon S3: 1.2.8
ImageOptimize: 1.6.13 (Sharp)

Could you check it?
Thanks.

**Comment by michtio** [comment]
@umkasanki could you test that with Image Optimize as well? As I don't see the image thumbnail from Craft itself Flip either?

**Comment by umkasanki** [comment]
@michtio not. the thumbnail also does not update.
The problem is present when using the Sharp transform Method.
For testing, I tried to switch to native Craft transformations, in this case image manipulation works better.
