### ISSUE TITLE
Using redis queue driver doesn't work with cli commands

### ISSUE THREAD

**Issue by samatcd** [nystudio107/craft3-imageoptimize#210]
I'm using the following configuration in `config/app.php` to use a redis queue runner for performance reasons.

```php
return [
    'components' => [
        'redis' => [
            'class' => yii\redis\Connection::class,
            'hostname' => getenv('REDIS_HOST'),
            'port' => getenv('REDIS_PORT') ?: 6379,
            'password' => getenv('REDIS_PASSWORD') ?: null,
            'retries' => 1,
        ],
        'queue' => [
            'class' => \yii\queue\redis\Queue::class,
            'redis' => 'redis', // Redis connection component or its config
            'channel' => 'queue', // Queue channel key
        ]
    ]
];
```

However, when I try run `craft image-optimize/optimize/create` I get an error with the way the queue run method is being invoked:

```
herokuishuser@production-worker-5bc795bf79-jm669:~$ php craft image-optimize/optimize/create
Creating optimized image variants
Exception 'ArgumentCountError' with message 'Too few arguments to function yii\queue\redis\Queue::run(), 0 passed in /app/vendor/nystudio107/craft-imageoptimize/src/console/controllers/OptimizeController.php on line 63 and at least 1 expected'

in /app/vendor/yiisoft/yii2-queue/src/drivers/redis/Queue.php:55

Stack trace:
#0 /app/vendor/nystudio107/craft-imageoptimize/src/console/controllers/OptimizeController.php(63): yii\queue\redis\Queue->run()
#1 [internal function]: nystudio107\imageoptimize\console\controllers\OptimizeController->actionCreate()
#2 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#4 /app/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction()
#5 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction()
#6 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#7 /app/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction()
#8 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#9 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#10 /app/craft(23): yii\base\Application->run()
#11 {main}
```

When I remove the `queue` config, the CLI command runs perfectly.

**Comment by khalwat** [comment]
You're actually not going to gain any performance by using Redis for the queue -- all it changes is whether the (tiny) queue job info is stored.  Check out this article for some details:

https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms

IO won't work with queue mechanisms that don't support the Craft standard queue interface.

**Comment by samatcd** [comment]
Actually it can have a significant impact on performance on a busy database server. It is extremely useful to be able to offload queue job tracking to an under-utilised Redis cluster, and saves significant expense in our setup.

I do however accept your argument about supporting non-standard queue interfaces. I'll have a look at writing a Redis driver implementation based on `craft\queue\QueueInterface`.

**Comment by khalwat** [comment]
I'm really surprised to hear that -- because typically queue job tracking is very lightweight, and things are (generally) not being constantly added to the queue.

But as with anything, it depends -- I can certainly see there might be a setup where it could help.

Let me see if I can't at least mitigate this issue for you.

**Comment by khalwat** [comment]
@samatcd I added support here: https://github.com/nystudio107/craft-imageoptimize/commit/4a07703533e0886f984d52783047d26ab6bc9791

Note: I did not set up a local Redis queue to test this; if we have further issues, I will do so.

You can set your semver to `dev-develop` to get this version and test it out.

**Comment by samatcd** [comment]
Thanks! I'll give it a go and let you know how it goes!

**Comment by khalwat** [comment]
I'm assuming this worked :)
