### ISSUE TITLE
Issue using ImageOptimize in Matrix

### ISSUE THREAD

**Issue by derkaan** [nystudio107/craft3-imageoptimize#211]
Hi,

I'm currently evaluating Craft incl. OptimizedImages for upcoming projects and stuck in setting up OptimizedImages correctly.

**What I did:**
- Installed ImageOptimize via the PluginStore 
- Copied the ImageOptimize-config from vendor to cms/config/image-optimize.php
- I've setup a volume for images 
- Except svgo, all other image transformers are installed via apt-get

Due to its flexibility my test site uses only one matrix field, which hold all layout sections (this might change in future).
The matrix is added as field to my image-volume.

When I add OptimizedImages as an additional field, I get following notification:
"OptimizedImages fields only work when added to an Asset Volume's layout."

To be on the safe side I also tested to create a OptimizedImages field directly (non-Matrix).
This seems to work. At least I don't get the same msg as in the matrix field.

Therefore my question is, if there is anything I need to do differntly in case of matrix fields?

In case it is relevant, these are my used versions:
- Craft Solo 3.4.25 (will be upgraded to Pro after successful evaluation)
- ImageOptimize 1.6.14

Cheers

**Comment by michtio** [comment]
@derkaan 

Image Optimize is not a field you would add to your content section, or in a matrix block for that matter. It is as the error says. 
You need to add the field as a custom field on your Volume that you use to save your images in from your Image/Assets Field.

<img width="599" alt="Screenshot 2020-06-29 at 16 47 43" src="https://user-images.githubusercontent.com/5818021/86020503-49edc980-ba28-11ea-8ffb-c57f0d31d292.png">

**Comment by derkaan** [comment]
@michtio Thanks a lot. That helped me.
