### ISSUE TITLE
[FR] Extra option to variants to create optimizations based on orientation.

### ISSUE THREAD

**Issue by michtio** [nystudio107/craft3-imageoptimize#213]
Hey Andrew,

Recently ran into a few cases on different projects where the following could be useful:

An image gallery has to be created, the image gallery exists out of portraits and landscapes, the current solution is to create a "Optimize Landscape Images" and "Optimize Portrait Images", which are both added to the Gallery Volume.

Now what this does, no matter if it's a portrait or landscape image, it will fire all optimizations, let's say 5 variants per image times two. In the current situation that fires 10 different transforms.

How I see it, is adding an option ( true / false ) if you want optimization based on orientation. 

1. You add a new variant
2. Select your breakpoint
3. Select if you want it to be landscape / portrait
4. Set your aspect ratio and the remaining options

What is the advantage of this:

1. You don't have to create twig logic to decide which Optimized Image Field it should fetch it's data from ( which is also harder with GraphQL, since you need to pull in both fields, and then add logic into your JS as well ) 
2. There will be half as much transforms being ran, which will save precious server CPU time, and on asset heavy site it will save $$$
3. It will also save a lot of storage room, since the useless Landscape transforms from Portrait Images or vice versa won't need to be saved, again saving $$$ on asset heavy websites.

**Comment by khalwat** [comment]
I'm completely redoing how this all works so... this will be addressed as part of that new UX https://twitter.com/nystudio107/status/1356368143392903168?s=20
