### ISSUE TITLE
Image transforms not executing after asset upload via front end entry form.

### ISSUE THREAD

**Issue by tom-byrom** [nystudio107/craft3-imageoptimize#214]
Hi - I have a front end entry form. It allows people to upload a cover photo via a file input which relates to an 'Asset' field type.

When they publish the entry form they get re-directed to the live entry.

The cover photo does not display it just shows a 1x1 pixel SVG in the code.

Now this is likely happening because the image transforms are not taking place automatically in the abckground. The variation creation and transforms only execute when I login as an admin to Craft and the job runs.

If i don't log in to the back end the transform never takes place?

Am I missing something? How can we avoid all of this?

Thanks

**Comment by tom-byrom** [comment]
https://github.com/nystudio107/craft-imageoptimize/issues/141

Didnt see this answer - gonna use the async plugin!

**Comment by tom-byrom** [comment]
One question I do still have (sorry) can I change that initial 1x1 grey square while the transforms are being generated? To something more applicable like a placeholder image?

**Comment by khalwat** [comment]
I don't think that's something you can change.
