### ISSUE TITLE
Extra Validation on Custom Aspect Ratios

### ISSUE THREAD

**Issue by michtio** [nystudio107/craft3-imageoptimize#215]
When you want to create your own Aspect Ratios it is possible to add your own number to AspectRatioX and AspectRatioY

Problem:
- Encountered an issue where as an oversight in one of the AspectRatio Number fields a letter was entered. "9u".
- This saved without any issue
- CLI tool `./craft resave/assets` was ran and every image errored with "A non well formed numeric value encountered"
- Running Image Optimize itself just got stuck, and never moved forward

Possible Solution:
Add a little field validation, so only numeric values can be saved, and if a non-numeric value is entered in `AspectRatioX` or `AspectRatioY` the field doesn't save but shows an error message

**Comment by khalwat** [comment]
I'm completely redoing how this all works so... this will be addressed as part of that new UX https://twitter.com/nystudio107/status/1356368143392903168?s=20
