### ISSUE TITLE
Specifying alternative transformClass for a specific volume

### ISSUE THREAD

**Issue by howells** [nystudio107/craft3-imageoptimize#216]
I'm about to start the long, fraught process of migrating locally stored files to Fortrabbit's Object Storage. Currently I have my local files served by Imgx, so have my `transformClass` set to `ImgixImageTransform::class`. However, for the new Object Storage volume, the details will obviously be different since it'll be pointing to a different source (or I might not use Imgix at all). Is there a way that I could specify transforms on a per-volume basis?

**Comment by khalwat** [comment]
Unfortunately, this isn't how ImageOptimize operates.
