### ISSUE TITLE
Update went wrong (format cannot be manipulated)

### ISSUE THREAD

**Issue by ThinkGraphical** [nystudio107/craft3-imageoptimize#217]
### Describe the bug
We went from Craft 3.2.10 to 3.4.26 & ImageOptimize 1.6.0 to 1.6.14.
Noticed the srcset weren't generated properly, saw the `format cannot be manipulated` error in the backend where the Optimized Image Variants are being displayed.

### What we found
After some debugging, we noticed that the project.yaml was misformed (see screenshot).
Looks like the quality & format parameter were merged into 1, which resulted in the srcset generation acting up weirdly.

We fixed it by changing the format to `'jpg'` instead of `'82'` or we could just have removed the format setting.

Probably a one-off issue, but just letting you know, maybe it rings a bell.
Perhaps it got something to do with the single quotes missing around `jpg`?

### Screenshots
![Screenshot 2020-07-10 at 08 57 44](https://user-images.githubusercontent.com/1651789/87126664-def48c00-c28c-11ea-971c-04ce6c24c694.png)

### Versions
- Plugin version: 1.6.0 -> 1.6.14
- Craft version: 3.2.10 -> 3.4.26

**Comment by khalwat** [comment]
This is a bug in Craft CMS -- specifically with Project Config munging up associative arrays.

https://github.com/craftcms/cms/issues/6320

https://github.com/craftcms/cms/issues/6317

**Comment by brandonkelly** [comment]
There’s actually nothing wrong with the posted screenshot. More verbose, but will resolve to the same thing either way.
