### ISSUE TITLE
Hide ImageOptimize fields that do not meet the subfolder restriction

### ISSUE THREAD

**Issue by benatleith** [nystudio107/craft3-imageoptimize#218]
When using the subfolder restriction feature (requested in [104](https://github.com/nystudio107/craft-imageoptimize/issues/104) and implemented in [r1.6.5](https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.5), all assigned ImageOptimize fields are shown on the Asset edit screen for the Volume, even if they have no effect. 

Furthermore, the IO field that does _not_ apply to the current subfolder shows a misleading error message which suggests an image processing error rather than the fact a subfolder restriction was applied:

> ![Screenshot 2020-07-14 at 17 55 49](https://user-images.githubusercontent.com/15892203/87485969-fd160f80-c631-11ea-9786-786e8b748029.png)

Therefore on the Asset edit screen I think it would be better to remove or hide any IO fields that do not meet the field's subfolder restrictions.

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-imageoptimize/commit/6f61940eeb3eeb1750b690e1495a157e83156081
