### ISSUE TITLE
Transforms folders don't get removed on image deletion - webp remains

### ISSUE THREAD

**Issue by juresrpcic** [nystudio107/craft3-imageoptimize#22]
When ImageOptimize is enabled, `.webp` files get created for both ImageOptimize transforms (using the field type) and standard Craft transforms. When an image is deleted from Craft (through Assets), the `.jpg` transforms get deleted with the image, but `.jpg.webp` files remain together with the folders (eg. `_600x337_crop_center-center_82_line`).

It would be good to delete both file types + the folders or it will leave unused folders/files on the server.

Thanks! (great plugin!)

**Comment by khalwat** [comment]
That's a good idea

**Comment by khalwat** [comment]
https://github.com/craftcms/cms/issues/2212

**Comment by khalwat** [comment]
The event I need should be added to Craft CMS 3 RC3, I'll add the feature when that ships.

**Comment by khalwat** [comment]
This is fixed in ImageOptimize 1.4.4:

https://github.com/nystudio107/craft3-imageoptimize/releases/tag/1.4.4

...which _requires_ Craft CMS 3 RC3 or later.
