### ISSUE TITLE
Browsers displaying wrong srcset size

### ISSUE THREAD

**Issue by nathansnelgrove** [nystudio107/craft3-imageoptimize#220]
I've got a problem where Google is reporting that the current source of an image that should be no bigger than 250px wide, or 500px wide (retina), is actually being served as 1920px wide.

I have no idea what the problem is.

I have set up the image variants as follows, with high or very high image quality and auto image formats:
- 1920w, 2x retina
- 1350w, 2x retina
- 1000w, 2x retina
- 700w, 2x retina,
- 450w, 2x retina
- 500w, 2x retina

Here's my code for the images in question:
```  
<picture>
    <source data-srcset="{{ optimizedImages.srcsetWebP() }}" 
            data-sizes="(min-width:1600px) 310px, (min-width:725px) 45vw, 95vw"
            type="image/webp" />
    <img class="lazyload{% if block.imageType %} {{ block.imageType.value }}{% endif %}"
        src="{{ optimizedImages.placeholderBox() }}"
        data-srcset="{{ optimizedImages.srcset() }}"
        data-sizes="(min-width:1600px) 310px, (min-width:725px) 45vw, 95vw"
        {% if image.imageAltText %}
            alt="{{ image.imageAltText }}"
        {% else %}
            alt="{{ image.title }}"
        {% endif %} />    
</picture>
```

At 900px wide, when it should serve 450px or so images and deliver 1000px images on retina, Google reports that the file being served is 1920px wide. Firefox reports the same.

I have tried incognito mode, using the Developer Tools in a separate window, using the *exact* width of 900px, so it shouldn't deliver anything optimized for larger than that. My understanding is that it should be delivering an image optimized for 45vw of 900px, or its retina variant.

Does this make sense to you? I feel like this must be user error, but I don't know where I'm going wrong.

**Comment by nathansnelgrove** [comment]
I have narrowed down this issue. It looks like the problems come from using webp as an image format. If I remove webP, the browser loads the correct images.

I can't think of why this would be a problem, unless I'm misunderstanding how to display images on the frontend...

**Comment by khalwat** [comment]
So this isn't an issue with ImageOptimize -- it's creating the variants you asked it to. Probably the best tutorial on image srcset, etc. is here:

https://cloudfour.com/thinks/responsive-images-101-definitions/

I don't think this is going to have to do with using webp or not.

**Comment by nathansnelgrove** [comment]
@khalwat I get what you're saying, but the issue did appear to be related to webp. The plugin created the right variants, but on the front-end, it would only ever display the highest-resolution one, instead of using the correct webp image for the monitor DPI and resolution.
