### ISSUE TITLE
No plugin exists with the handle "image-optimize".

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [nystudio107/craft3-imageoptimize#222]
### Describe the bug
I have a fresh 3.5 install running and tried installing the plugin within it and get this error:

```
No plugin exists with the handle "image-optimize".
```

### To reproduce
1. Go to Plugin Store
2. Click on Try on the plugin
3. Then you'll receive the error.

I also tried installing the plugin from the Plugin list and received that error again:

```
Invalid plugin – craft\errors\InvalidPluginException
No plugin exists with the handle "image-optimize".
```

### Expected behavior

I expect to be able install the plugin

### Versions
- Plugin version: 1.6.14
- Craft version: 3.5

**Comment by khalwat** [comment]
This isn't an issue with Image Optimize, but rather an issue with the plugin store -- I've been able to download and install it without issue, so likely it has been resolved.

**Comment by DynamiteGoesBoom** [comment]
Okay and thanks @khalwat :)

Have a great one and thanks for all that you do for all of us 👍
