### ISSUE TITLE
Transformed images not getting format=auto, breaking automatic webp

### ISSUE THREAD

**Issue by jakedohm** [nystudio107/craft3-imageoptimize#226]
### Describe the bug
When transforming an image from a template* it the automatic addition of `auto=format` in the Imgix URL is stripped, causing the image to only be served in their original format, losing performance gains. When I _don't_ pass in a transform to `getUrl` the plugin behaves as expected, and the image is automatically served as `webp` (when possible). It's only when I pass in settings for the transform that this functionality is lost.

So, this works properly:
```twig
{{ entry.image.one().getUrl() }}
```
But this breaks (the transform works, but not the auto format)
```twig
{{ entry.image.one().getUrl({ width: 500, height: 500 )} }}
```

### To reproduce
Steps to reproduce the behaviour:
1. Configure Imgix (CP settings don't matter)
2. Transform an image within a template

### Expected behaviour
The transformed image should also have `format=auto` appended to the URL.

### Versions
- Plugin version: 1.6.16
- Craft version: 3.5.7

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize/pull/228
