### ISSUE TITLE
[FR] optional height value for Image Variants

### ISSUE THREAD

**Issue by moldedjelly** [nystudio107/craft3-imageoptimize#227]
### The problem
I love the Image Variant system and how it generates them on image save. I'd like to generate my image variants for a gallery system where the front-end display of the images will fit into a set aspect ratio view area (eg. square aspect). With the current approach of the Image Variant system fixed on image width only, for portrait images uploaded, it generates unnecessarily tall images.

### Possible solution
The ability to specify an optional height value so that the image is resized to fit within the width and height (basically in a similar way to how width and height values work in standard "fit" image transforms).

**Comment by khalwat** [comment]
I'm completely redoing how this all works so... this will be addressed as part of that new UX https://twitter.com/nystudio107/status/1356368143392903168?s=20
