### ISSUE TITLE
Ability to minify the Optimized Image Variants (like matrix fields) so easier to reorganise/reorder

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft3-imageoptimize#229]
### Is your feature request related to a problem? Please describe.
It would be great if you could minify the Optimized Image Variants options like you can with native matrix fields.
I guess ideally, it would perhaps in minified view show the image width and aspect ratio.
But I would find this easier to move the Image Variants and re-order based on size etc as required.

So you can double click on these and...
<img width="1509" alt="Screenshot 2020-09-21 at 15 16 10" src="https://user-images.githubusercontent.com/5698596/93778142-78410680-fc1d-11ea-867f-6dc4f57fc01a.png">
... make them minified like these:
<img width="1137" alt="Screenshot 2020-09-21 at 15 17 01" src="https://user-images.githubusercontent.com/5698596/93778184-8131d800-fc1d-11ea-9f0a-83d27373a12f.png">

**Comment by khalwat** [comment]
Interesting idea, I like it. I'll have to see how Matrix blocks do this.

**Comment by khalwat** [comment]
I'm completely redoing how this all works so... this will be addressed as part of that new UX https://twitter.com/nystudio107/status/1356368143392903168?s=20
