### ISSUE TITLE
Reverse Srcset order for x2 and x3 images. OR always output the srcset order based on the widths (largest -> smallest)

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft3-imageoptimize#230]
### Is your feature request related to a problem? Please describe.
Ok, so this is probably my OCD being way too high and if you tell me where to go, I'll undersrtand.
But it would be great if the srcset image order for 'Retina' Sizes could be reversed.

At the moment I have the following setup in Image Optimize.
All 8x5 aspect ratio.
1200w
992w
768w
576w
I have then added a 160w with the 2x and 3x selected so it will also generate 320w and 480w images.
These are used mostly for the teaser images on articles, hence them being small, but it fills the gap so it isn't loading 576w as the minimum size. As this is much larger than required.

The problem is the output looks like this:
```
https://hatchendtuition.loc/uploads/images/_1200x750_crop_center-center_82_line/hatch-end-tuition-ss-570197419.jpg 1200w, 
https://hatchendtuition.loc/uploads/images/_992x620_crop_center-center_82_line/hatch-end-tuition-ss-570197419.jpg 992w,
https://hatchendtuition.loc/uploads/images/_768x480_crop_center-center_60_line/hatch-end-tuition-ss-570197419.jpg 768w, 
https://hatchendtuition.loc/uploads/images/_576x360_crop_center-center_60_line/hatch-end-tuition-ss-570197419.jpg 576w, 
https://hatchendtuition.loc/uploads/images/_160x100_crop_center-center_82_line/hatch-end-tuition-ss-570197419.jpg 160w,  
https://hatchendtuition.loc/uploads/images/_320x200_crop_center-center_61_line/hatch-end-tuition-ss-570197419.jpg 320w,
https://hatchendtuition.loc/uploads/images/_480x300_crop_center-center_41_line/hatch-end-tuition-ss-570197419.jpg 480w
```

This is super annoying to me. I think it should reverse the the x2, x3 order. 
```
https://hatchendtuition.loc/uploads/images/_1200x750_crop_center-center_82_line/hatch-end-tuition-ss-570197419.jpg 1200w, 
https://hatchendtuition.loc/uploads/images/_992x620_crop_center-center_82_line/hatch-end-tuition-ss-570197419.jpg 992w,
https://hatchendtuition.loc/uploads/images/_768x480_crop_center-center_60_line/hatch-end-tuition-ss-570197419.jpg 768w, 
https://hatchendtuition.loc/uploads/images/_576x360_crop_center-center_60_line/hatch-end-tuition-ss-570197419.jpg 576w,
https://hatchendtuition.loc/uploads/images/_480x300_crop_center-center_41_line/hatch-end-tuition-ss-570197419.jpg 480w,
https://hatchendtuition.loc/uploads/images/_320x200_crop_center-center_61_line/hatch-end-tuition-ss-570197419.jpg 320w,
https://hatchendtuition.loc/uploads/images/_160x100_crop_center-center_82_line/hatch-end-tuition-ss-570197419.jpg 160w,
```

Or if it can get super clever **always** output the srcset order by size regardless, as you might have a cross over of sizes if a 2x, 3x image was used in between single size options. But this might not be easily done?

I don't think the srcset order matters, it is only the sizes that matters, but it irks me to be honest. I know it has no impact in terms of functionality etc. So appreciate if you rule it out, but please consider my sanity before you throw it away. :-)

Thank you for listening....

**Comment by khalwat** [comment]
Yeah I actually checked into this, and the order doesn't matter to the browser... so probably this is a "won't fix".
