### ISSUE TITLE
Sharp 'contain' and Craft 'fit' Transform Mode Discrepancies 

### ISSUE THREAD

**Issue by darinlarimore** [nystudio107/craft3-imageoptimize#242]
### Question
Hello, we are using the image optimize plugin in conjunction with the aws sharp image handler and have a question having to do with transform settings.

We noticed that when using the '**fit**' transform, images returned by image optimize have "letterboxing" unlike the natively craft transformed images. (see screenshot)

We have tried using the '**inside**' sharp image transform outlined here https://sharp.pixelplumbing.com/api-resize#resize and this seems to give us results more like Craft. Is this intentionally set to differ for some reason?

### Additional context
<img width="1037" alt="fig1" src="https://user-images.githubusercontent.com/20300635/104634314-74bf0880-566e-11eb-90a9-18ab509741cd.png">

**Comment by khalwat** [comment]
hmmm not intentional, I think probably it should map to "inside" as you've indicated

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize-sharp/releases/tag/1.0.6

**Comment by darinlarimore** [comment]
Excellent, Thank you! @khalwat
