### ISSUE TITLE
How to deal with different file extensions like GIF or SVG if ignored?

### ISSUE THREAD

**Issue by leemunroe** [nystudio107/craft3-imageoptimize#247]
### Question
I have implemented image optimize and have it working for JPG and PNG. Our content creators can upload animated gifs. 

I've purposely checked the ignore SVGs and GIFs checkboxes as I'd prefer to use the exact file they upload in these instances.

![image](https://user-images.githubusercontent.com/15963/105285897-27f59900-5b6a-11eb-8294-f00cc8e10eab.png)

What is the best practice for supporting this in the twig template? i.e. if optimizedImages isn't present then fallback to the regular image?

### Additional context

What I currently have in Twig.

```
{% set imageopt = entry.heroImage.one().optimizedimages %}
          {% set minWidth = 700 %}
          <img class="lazy img-feature-hero"
               src="{{ siteUrl }}images/placeholder.png"
               data-src="{{ imageopt.src() }}"
               data-srcset="{{ imageopt.srcset() }}"
               alt="{{ entry.heading }}"
               {% if entry.heroImageWidth is defined and entry.heroImageWidth %} width="{{ entry.heroImageWidth }}"{% else %} width="{{ minWidth }}"{% endif %}
          >
```

Thanks for your help

**Comment by khalwat** [comment]
You could either check the extension, or you could do something like:

```twig
{% set imageopt = entry.heroImage.one().optimizedimages %}
{% if imageopt.srcset | length %}
...do something
{% endif %}
```
...to not process images for which no `srcset` exists.
