### ISSUE TITLE
Command line create fails for most images

### ISSUE THREAD

**Issue by sgtpenguin** [nystudio107/craft3-imageoptimize#248]
A few image transforms were missing, I believe due to a timeout or memory error when many assets were being uploaded at once.  I ran `php craft image-optimize/optimize/create`, which appeared to complete without a problem.  After this no transforms were showing up on the front end.  Transformed files still exist on the server but asset dialogs would display "This image can not be manipulated" for all optimized fields.  I tried dumping cache and running index assets.  Then I updated imageoptimize to try with the `--force` command.  After running `optimize/create` again, I began seeing this message for most, but not all assets.  I'm guessing the error messaging appeared this time due to the update.

`Could not create transform for: Responsive Test4 - Final format: jpg - Element extension: jpg - canManipulateAsImage: 1
`
This asset exists and used to be transformed.  If I download it and do replace asset it transforms correctly.  This is not a viable workaround for the 3k+ assets on the site, but shows me that the plugin works.

I have then deleted all transforms from the server, dumped cache, and ran index assets to try to start fresh.  Hard to say exactly, but maybe around 30% of images transform, the rest give the `Could not create transform for` error.

No settings were changed, was previously working fine for weeks.  Any ideas for getting these to transforms to happen or getting more clarity on the "Could not create transform" error?

Thank you

**Comment by khalwat** [comment]
@sgtpenguin check your logs to see if any additional information was logged -- search on `[error]` in both the `web.log` and the `queue.log` (and maybe the `console.log` if you're running commands via it).

It sounds to me like not enough RAM is allocated to PHP which is causing the Craft image transforms (done via Imagine) to fail.

**Comment by khalwat** [comment]
Discussing this with you on Discord, it sounded like Craft's asset indexing was the issue here?

**Comment by khalwat** [comment]
Will re-open if more info is provided
