### ISSUE TITLE
Control panel thumbnail generation offloading

### ISSUE THREAD

**Issue by zawilliams** [nystudio107/craft3-imageoptimize#250]
### Question

Does this plugin offload the thumbnails generated in the control panel? For example, the thumbnails typically are pulled in via a URL like this: `https://mypage.url/index.php?p=admin/actions/assets/thumb&uid=64b1e633-280e-4b95-8558-76b5e46f51be&width=120&height=80&v=1608156921`. Would these get processed via ImageOptimize?

**Comment by khalwat** [comment]
Yes, they would.
