### ISSUE TITLE
Control panel performance

### ISSUE THREAD

**Issue by almeric** [nystudio107/craft3-imageoptimize#251]
### Is your feature request related to a problem? Please describe.
When an asset has multiple `OptimizedImages` fields, or many different sizes the performance of the asset page in the Control Panel can be very slow. (We're using the AWS Serverless Image Handler). It looks like all the images are being loaded at once.

### Describe the solution you would like
I think the most simple solution would be to lazy load all image variants on the control panel. That way the initial load of the page would be fast & the user would be provided of visual feedback instead of an long wait time.

**Comment by khalwat** [comment]
There is an option in the Field Settings to disable the display of these: **Display Optimized Image Variants**

I am working on a major new version, and will keep the lazy loading in mind for it however!
