### ISSUE TITLE
This is not an image that can be manipulated on every upload

### ISSUE THREAD

**Issue by cookie10codes** [nystudio107/craft3-imageoptimize#256]
### Describe the bug
On our local setup, the image seems to be converting well, but on our staging environment we continuously get a message it can't be manipulated. We need to run `php craft image-optimize/optimize/create --force` every time someone is uploading an image.

### To reproduce
On every upload

### Expected behaviour
Don't see the problem why it shouldn't optimise right away

### Screenshots
Develop:
<img width="610" alt="Screenshot 2021-02-11 at 12 53 23" src="https://user-images.githubusercontent.com/20947573/107633895-04a1a380-6c69-11eb-9612-fee941333b2f.png">

Staging:
<img width="532" alt="Screenshot 2021-02-11 at 12 53 09" src="https://user-images.githubusercontent.com/20947573/107633907-09feee00-6c69-11eb-839d-22e6cad134da.png">

### Versions
- Plugin version: 3.6.3
- Craft version: 1.6.21

**Comment by michtio** [comment]
As extra information:

This uses the lambda function to run ( Sharp method ) - Local works exactly the same way.

**Comment by khalwat** [comment]
You just need to regenerate the images on that server -- you can use the CLI command to do so.

While the images are coming from Sharp, the saved URLs still need to be generated and saved in the db

https://nystudio107.com/docs/image-optimize/Using.html#command-line-optimized-image-variant-creation

```
php craft image-optimize/optimize/create
```

**Comment by cookie10codes** [comment]
@khalwat but it's for every new upload, we can't just run that after every new image upload? Or am I missing something?

**Comment by khalwat** [comment]
Definitely should not be happening on every image upload. I'd suggest checking your logs, something is likely misconfigured
