### ISSUE TITLE
Gifs aren't working despite skipping them : using Imgix

### ISSUE THREAD

**Issue by J-Protz** [nystudio107/craft3-imageoptimize#257]
### Question
I am trying to allow the client to use a gif, however even when I create a new asset volume and **don't** add the imageOptimize field to it, the url is returning an Imgix url, and is not animating, it just shows a still image. I'm not sure if this is an Imgix configuration issue, or if I need to be able to access my local files. I think ideally since I didn't add the field to this volume I should be able to access `mySite/assets/gifs/myGif.gif`

### Additional context
Here is my code for accessing the url:

```twig
<img src="{{block.image.one().getUrl()}}" alt="{{block.image.one().title}}">
```

Here is the gif I'm selecting within a gif volume:

<img width="1202" alt="Screen Shot 2021-02-11 at 11 34 46 AM" src="https://user-images.githubusercontent.com/70289763/107667008-272dbf80-6c5d-11eb-9456-2985f57c1d5b.png">

My asset volume fields:

<img width="1440" alt="Screen Shot 2021-02-11 at 11 36 33 AM" src="https://user-images.githubusercontent.com/70289763/107667249-65c37a00-6c5d-11eb-83e9-46a714fa093a.png">

I also checked the field settings and it does not include the `gifs` volume.

**Comment by J-Protz** [comment]
For now, I've done the following workaround, however I'd love a less clunky way to deal with gifs :)
```html
            {% set img = block.image.one() %}
            {% if img.extension =='gif' %}
            <img src="{{siteUrl}}assets/gifs/{{img.filename}}" alt="{{img.title}}">
            {% else %}
              <img src="{{img.getUrl()}}" alt="{{img.title}}">
            {% endif %}
```

**Comment by J-Protz** [comment]
BTW the reason the thumbnail is broken is because I haven't quite figured out the multi env setup yet, currently all my environments use the prod volume for imgix, so if the image doesn't exist on prod it wont show here either. However I did add the gif to prod and also added it to local within an optimizedImg volume, with gifs excluded in the settings, and it only showed the first frame, it didn't animate.

**Comment by khalwat** [comment]
If you use ImageOptimize to change your transform method to something like Imgix, then all transforms are run through Imgix. 

This is good, because it allows you to switch between image transform services without having to make any template changes.

This is bad in your case, because currently ImageOptimize doesn't support animated .gifs. If you want to voice your support for adding them, head on over here: https://github.com/nystudio107/craft-imageoptimize/issues/172

**Comment by J-Protz** [comment]
@khalwat is there no way to just receive the gif's local url, I don't want any transform applied to it?

**Comment by khalwat** [comment]
You should be able to just do `asset.url` and it should work I think?

**Comment by J-Protz** [comment]
Unfortunately not, sorry if my original issue message wasn't clear. I made a whole new volume , did **not** add the img optimize field to it, called `asset.url` and got `<myDomain>.imgix.net/...`, so my current solution is to do a gif extension check and have all gifs in a specified folder so I can do...


```html
         {% if img.extension =='gif' %}
            <img src="{{siteUrl}}assets/gifs/{{img.filename}}" alt="{{img.title}}">
            {% else %}
              <img src="{{img.getUrl()}}" alt="{{img.title}}">
            {% endif %}

```
