### ISSUE TITLE
Fails to generate assets after changing variant aspect-ratio: "webp variant does not exist"

### ISSUE THREAD

**Issue by saltymouse** [nystudio107/craft3-imageoptimize#260]
After I altered an existing ImageOptimize variant from `16:9` aspect-ratio to `21:9` aspect-ratio, I got an error on my asset's details page saying "This is not an image that can be manipulated."

(#238) As mentioned in that issue, I tried rebuilding the assets via the Craft CP (CLI `craft index-assets/all` doesn't work), but now I see another warning on the assets page: "webp variant does not exist" and "jpg variant does not exist". However, clicking on these warning text links still takes me to the webp or jpg variant.

Running `craft image-optimize/optimize/create` doesn't produce errors in the terminal, but now makes Optimized Images show with this warning: "This is not an image that can be manipulated", and images no longer show up when loading the front-end of the website. Running an asset rebuild brings the assets back to the "jpg variant does not exist" warning message, and images are visible on front-end.

Clearing all caches and rebuilding has no different effect either.

### To reproduce
1. Go to existing ImageOptimize field and change aspect ratio from one setting to a different one.
2. Open Craft's "Assets", click on an optimized image
3. Errors visible on asset's details page
![Screen Shot 2021-02-17 at 1 56 30 AM](https://user-images.githubusercontent.com/7547649/108187912-d3d7c900-70c3-11eb-9e19-a36bba03e910.png)
![Screen Shot 2021-02-17 at 1 58 27 AM](https://user-images.githubusercontent.com/7547649/108187917-d4705f80-70c3-11eb-9612-fa48c66b82e5.png)

Basic config:
[image-optimize.php.txt](https://github.com/nystudio107/craft-imageoptimize/files/5994761/image-optimize.php.txt)
Logs taken after image-optimize create command:
[logs.zip](https://github.com/nystudio107/craft-imageoptimize/files/5994773/logs.zip)

### Expected behaviour
Newly generated images in the requested aspect-ratio.

### Versions
- Plugin version: 1.6.23
- Craft version: 3.6.6
- DDEV/Docker (local)
- PHP 7.4
- All image optimization tools
 are installed and recognized by ImageOptimize

**Comment by khalwat** [comment]
If clicking on the images works, then they have actually been generated. You can verify this by looking at in your Asset Volume's directory structure, you'll see a number of transform directories (they begin with an `_`). This is because ImageOptimize uses regular old Craft transforms to do its thing.

The images that should be appearing in the Asset Detail view is likely due to your local development config. `curl` is used to obtain those images, and if it fails, then ImageOptimize shows this error.

Probably this is due to some kind of internal Docker networking issue, where the `curl` command from the PHP container fails.

**Comment by saltymouse** [comment]
Looking in the Asset Volume directory, I do see there are multiple transformations created for the ImageOptimize files. However, everything was working (without warnings or errors) until I changed that ImageOptimize field's aspect-ratio settings. (I could be wrong about this as the cause. I'll setup a reproduction test this weekend to confirm). But would there be any reason why the plugin would work initially in this same ddev/docker setup, then falter upon subsequent changes?

**Comment by khalwat** [comment]
That's a good question. I'd be happy to do a screenshare with you at some point to try to work out what exactly is going on here. Ping me on the Craft Discord at: `andrew.welch` if you're interested!

**Comment by khalwat** [comment]
So we tracked this one down, it ends up not being an ImageOptimize issue... but rather a combination of very large source images, and ImageMagick running out of resources.

ref: https://stackoverflow.com/questions/31407010/cache-resources-exhausted-imagemagick
ref: https://github.com/phw/peek/issues/112

There was a 11mb and 15mb source image, and the error shown in the logs was:

```
2021-02-19 19:13:23 [-][1][-][error][Imagine\Exception\RuntimeException] ImagickException: cache resources exhausted `/home/vagrant/webdev/sites/craft3/web/assets/home_photo_1.jpeg' @ error/cache.c/OpenPixelCache/3984 in /home/vagrant/webdev/sites/craft3/vendor/pixelandtonic/imagine/src/Imagick/Imagick.php:189
```

If you run this command:

```
html$ convert -list resource
Resource limits:
  Width: 16KP
  Height: 16KP
  List length: 18.446744EP
  Area: 128MP
  Memory: 256MiB
  Map: 512MiB
  Disk: 1GiB
  File: 786432
  Thread: 8
  Throttle: 0
  Time: unlimited
```

You'll see the current resource policy limits for ImageMagick... If you edit the policy file:

```
sudo nano /etc/ImageMagick-6/policy.xml
```

Change the following resources (I doubled memory and quadrupled disk):
```
  <policy domain="resource" name="memory" value="512MiB"/>
  <policy domain="resource" name="disk" value="4GiB"/>
```

This would have happened if ImageOptimize wasn't even installed, and the same image transform was attempted using regular Craft transforms.
