### ISSUE TITLE
IO is setting the `url` property on asset events when it doesn't need to

### ISSUE THREAD

**Issue by mattgrayisok** [nystudio107/craft3-imageoptimize#262]
### Describe the bug

IO is setting the `url` property on asset events when I don't think it necessarily needs to, preventing other well behaved plugins from changing it later if they're listening to the same event. Related Servd plugin issue:

https://github.com/servdhost/craft-asset-storage/issues/21

I think it's this line which is causing the problem:

https://github.com/nystudio107/craft-imageoptimize/blob/a077b4c3ee7cb8ca69eaf83119b4e750f8bb6839/src/services/Optimize.php#L159

IO is explicitly setting the URL for non-image assets to what I think would be the same value as Craft would use if the plugin were to leave the url as null, but by setting it to a value, other plugins which check for a null value in order to prevent overwriting are not adding their value when they otherwise would.

If you think it wouldn't cause any problems, would we be able to update this to just return null and let Craft, or another plugin, handle filling in the url param instead in this instance?

*There's a larger conversation about how it's potentially stupid that multiple plugins can all edit the same event, but we'll save that for another day.*

### To reproduce
Steps to reproduce the behaviour:
1. Install IO
2. Install Servd Plugin
3. IO will return urls for non-image assets which the Servd plugin then dutifully, but incorrectly accepts as gospel

### Expected behaviour
IO shouldn't set the URL param if it hasn't explicitly wanted to set it to something custom.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-imageoptimize/commit/a1f8a0214afeea5b32ac290972960ef4e580a8c2

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.27”,
```
Then do a `composer update`
