### ISSUE TITLE
Imgix USM Param Setting

### ISSUE THREAD

**Issue by devotoare** [nystudio107/craft3-imageoptimize#263]
### Is your feature request related to a problem? Please describe.
Images are sharpened too much/too little.

### Describe the solution you would like
Please add a setting for manually setting the USM (and preferably ALL possible Imgix values).

### Describe alternatives you have considered
Forking the code and changing it manually.

### Additional context
Our images look way too sharp most of the time and we can't change them. I have disable auto sharpen images for now because whatever the conditional check for this always returns true regardless of image size.

**Comment by khalwat** [comment]
Can definitely get this looked into; how is this always scaling it tho?

```php
                if ($settings->autoSharpenScaledImages) {
                    // See if the image has been scaled >= 50%
                    $widthScale = $asset->getWidth() / ($transform->width ?? $asset->getWidth());
                    $heightScale = $asset->getHeight() / ($transform->height ?? $asset->getHeight());
                    if (($widthScale >= 2.0) || ($heightScale >= 2.0)) {
                        $params['usm'] = 50.0;
                    }
                }
```

It should only be doing it if the scaling is > 50%?

**Comment by devotoare** [comment]
@khalwat I'm actually not 100% sure. I saw that snippet and I'm not sure what it's returning for widthScale or heightScale but it's always true. It could very well be the source images are that large it's just that 50% is way too much. Usually 18-20 is perfect for our specific use case.

**Comment by khalwat** [comment]
Probably due to the nature of the algorithm. I'll drop it down to 25, how's that?

**Comment by devotoare** [comment]
Sorry, there's nothing wrong with the scale check like that's fine. It's just the USM value is too high. I think being able to set this in the plugin options for a default sharpness setting as well as a "scaled image sharpening" setting would be ideal. For now we've just disabled autoSharpen.

**Comment by khalwat** [comment]
One of the design goals of the plugin is not to tie you to a particular service. The idea is if you decide to switch back to using Craft CMS to do the transforms, or you decide to spin up your own Serverless Sharp image transform lambda function, everything will continue to work with zero template changes.

If it's something that can be implemented as a standardized way across the board, I can do it. I probably will not be adding Imgix-specifc things, for the reason mentioned above, though.

I don't want you to be tied to any particular transform method/service.

**Comment by devotoare** [comment]
@khalwat I understand that, but since Imgix is just URL parameters is there a reason why an "Imgix Settings" can't be created and used to modify the URL params for that service? Sure there won't be feature parity across methods/services but to expect that would be insane. Instead what we have now is the inability to use the service properly.

**Comment by khalwat** [comment]
Other than the USM param (which I'm working on something for), what do you need in order to use the service properly?

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.27 & https://github.com/nystudio107/craft-imageoptimize-imgix/releases/tag/1.2.1

**Comment by devotoare** [comment]
@khalwat Thanks for releasing this for Auto Sharpened images.

Whatever updates happened (either to my images or the plugin) have made the sharpening stop applying on images I need them on because they're not being scaled down enough. Can we unlock the setting for all images to apply? Potentially with a different field for the ones that get further reduced?

Ideally I should be able to control all Imgix parameters across all images. I like how the USM parameter was applied to auto sharpened images but really anything that is not available in the plugin but is available in Imgix is giving us issues because we can't dial in the images exactly how we want. For now it's sharpness. I'm sure in the future it could be other things. Is there a reasonable way to get feature parity? We chose this plugin because of it's explicit Imgix support but it's more limiting than that and beginning to be a pain point instead of an enhancement.

**Comment by khalwat** [comment]
The changes I made should not have affected which images the sharpness is applied to, but rather just how much is applied when they are sharpened.

Are _none_ of your images being sharpened when being scaled down now (as opposed to before)?

As for the request to add arbitrary parameters for Imgix, I think it's important to understand that Image Optimize is not intended to be simply a way to use Imgix. It's intended to be a way to make optimized image variants using any arbitrary image transform service.

I don't love the idea of having service-specific settings, because if you decide to stop using Imgix, for example, suddenly your images may look different because whatever custom settings you used for Imgix are not available to Craft or the lamba function, or what have you.

Let's solve your current problem, to get that addressed, and then have a discussion about this separate issue of being able to send arbitrary commands down to a specific image processing service.

**Comment by devotoare** [comment]
Now it's calculating properly and only applied when scaled down over 50%. I honestly think my images were the problem with that before so it's not the plugin. So right now the plugin is working as intended and images that are scaled more than 50% get the sharpness applied.

I just need a way to apply usm parameter to every image.

**Comment by khalwat** [comment]
How about this @devotoare -- I could add a global or field setting that lets you specify the percentage at which the sharpening kicks in?

**Comment by devotoare** [comment]
@khalwat That would be great if it would work for every image if I set it to 0% or something like that? That would be great.

**Comment by khalwat** [comment]
@devotoare to be clear, ImageOptimize never does _anything_ to the original images you upload. So you'd need to be using some kind of transformed variant. But yes, if you set it to 0, then it'd do it for all of the image variants.

**Comment by devotoare** [comment]
@khalwat That would be perfect, thanks!

**Comment by devotoare** [comment]
@khalwat I'm being asked to ask if you know of an ETA for this update? Sorry to bug you.

**Comment by khalwat** [comment]
Should be able to get you a version to test today. Stay tuned.

**Comment by khalwat** [comment]
Did not forget about this @dennisfrank -- just had a bit of a rough day on Friday (second COVID-19 jab too).

**Comment by dennisfrank** [comment]
@khalwat I think, you mean @devotoare 😄 (I probably won't get my first vaccination appointment until sometime in the summer or so.)

**Comment by devotoare** [comment]
@khalwat Sounds good!

Thanks for the tag @dennisfrank ;)

**Comment by khalwat** [comment]
Alrighty this is all set. It'll be in the next release.

**Comment by khalwat** [comment]
@devotoare Released in https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.33
