### ISSUE TITLE
services\ManifestService

### ISSUE THREAD

**Issue by bfjare** [nystudio107/craft3-imageoptimize#266]
Just upgrading everything on a site and getting this error with Image Optimize when its installed.
`
Failed to instantiate component or class "nystudio107\pluginmanifest\services\ManifestService".`

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.28

**Comment by bfjare** [comment]
Thank you sir!
