### ISSUE TITLE
Hide error messages in detail if asset is a movie

### ISSUE THREAD

**Issue by JensvdHeydt** [nystudio107/craft3-imageoptimize#267]
### Describe the bug
ImageOptimize is throwing error messages in an asset's detail view (<url>/admin/assets/media/<media filename>) for movie files (.mp4). I have configured an Image Optimizer field for an asset volume that also contains movie files. My client is a little confused by these error messages.

### To reproduce
Steps to reproduce the behaviour:
1. Add ImageOptimize to an asset volume
2. Upload a non-image file to that volume

### Expected behaviour
I would like these error messages to only appear for files that have a file extension associated with images.

### Error messages:

Optimized Image Variants:
 This is not an image that can be manipulated or the images would all be up-scaled

Error Messages:
Could not create transform for: 01 kms team schneider stage loop 16 9 - Final format: mp4 - Element extension: mp4 - canManipulateAsImage:
Could not create transform for: 01 kms team schneider stage loop 16 9 - Final format: mp4 - Element extension: mp4 - canManipulateAsImage:
Could not create transform for: 01 kms team schneider stage loop 16 9 - Final format: mp4 - Element extension: mp4 - canManipulateAsImage:
Could not create transform for: 01 kms team schneider stage loop 16 9 - Final format: mp4 - Element extension: mp4 - canManipulateAsImage:
Could not create transform for: 01 kms team schneider stage loop 16 9 - Final format: mp4 - Element extension: mp4 - canManipulateAsImage:
Could not create transform for: 01 kms team schneider stage loop 16 9 - Final format: jpg - Element extension: mp4 - canManipulateAsImage:
Could not create transform for: 01 kms team schneider stage loop 16 9 - Final format: mp4 - Element extension: mp4 - canManipulateAsImage:

### Versions
- Plugin version: 1.6.28
- Craft version: 3.6.11.2

**Comment by khalwat** [comment]
Yeah, these shouldn't be displayed, I agree

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize/commit/fb72f126e38e61ea892d8054e194446b12b93b39

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.30”,
```
Then do a `composer clear-cache && composer update`
