### ISSUE TITLE
Can't add new image variants

### ISSUE THREAD

**Issue by richardcalahan** [nystudio107/craft3-imageoptimize#268]
### Describe the bug
After creating a new Optimized Images field, I can't add new variants. I can edit the values of the existing default variants, but the UI to add or reorder variants is non-responsive. 

### To reproduce
Steps to reproduce the behaviour:
1. Create a new optimized images field
2. Attempt to add a new image variant 
3. The UI does not update and no new variant is created.

### Expected behaviour
New variant is added to the list and can be edited.

### Versions
- Plugin version: 1.6.28
- Craft version: 3.6.11.2

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize/commit/92bf54427dca822a4f5f9e4decede18cce15aa4c

**Comment by richardcalahan** [comment]
Thanks for the quick fix!
