### ISSUE TITLE
Could not create transform. Final format: pdf - Element extension: pdf

### ISSUE THREAD

**Issue by carolineboeykens** [nystudio107/craft3-imageoptimize#269]
### Describe the bug
The Optimized Images fields on an asset are displaying errors if we upload a pdf in the asset library. Is it possible to ignore this fields if it the asset is not an image?

### To reproduce
Steps to reproduce the behaviour:
1. Create a volume
2. Create Optimized Images fields
3. Set the fields on the volume
4. Upload a pdf in this volume

### Screenshots
![Screen Shot 2021-04-02 at 13 48 25](https://user-images.githubusercontent.com/42932673/113413186-4f62b080-93ba-11eb-8b14-786d8f8c9d4d.png)

### Versions
- Plugin version: 1.6.29
- Craft version: 3.6.11.2

**Comment by khalwat** [comment]
Same as: https://github.com/nystudio107/craft-imageoptimize/issues/267

Will fix!

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize/commit/fb72f126e38e61ea892d8054e194446b12b93b39

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.30”,
```
Then do a `composer clear-cache && composer update`
