### ISSUE TITLE
Incorrect plugin name in breadcrumb

### ISSUE THREAD

**Issue by owenandrews** [nystudio107/craft3-imageoptimize#27]
Small detail but it appears that the incorrect plugin name appears in the breadcrumb immediately after installation. 

<img width="350" alt="screen shot 2017-12-26 at 2 44 45 pm" src="https://user-images.githubusercontent.com/5018955/34346689-80339e54-ea4e-11e7-992d-cd509daddf0f.png">

**Comment by khalwat** [comment]
Ooops! Fixed in 1.4.6, thanks.
