### ISSUE TITLE
SVG Silhouette not generating for specific images

### ISSUE THREAD

**Issue by jakepm** [nystudio107/craft3-imageoptimize#270]
### Describe the bug
Some of the images we use are failing to convert into an SVG Silhouette.

### To reproduce
Steps to reproduce the behaviour:
1. Install & configure plugin to create SVG Silhouettes
2. Create relevant ImageOptimize field on an asset volume
3. Upload the images below to the volume
4. Observe incorrect data: which results in a broken image

https://s3.eu-west-2.amazonaws.com/ds-darwinsoftware-dev/cs/marquis.jpg
https://s3.eu-west-2.amazonaws.com/ds-darwinsoftware-dev/cs/promotion-line.png

### Expected behaviour
SVG Silhouette to be created.

### Screenshots
Sample data: output 

data:image/svg+xml,data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%27300%27 height=%27412%27 style=%27background:%23CCC%27 /%3E

### Versions
- Plugin version: 1.6.29
- Craft version: 3.6.9

**Comment by khalwat** [comment]
I think what this is would be the underlying tool I'm using to generate the SVGs... if the resulting SVG is too large (it's an arbitrary cutoff I added) then it just gives up and returns what you're seeing above.

**Comment by khalwat** [comment]
So both of these images worked for me here:

<img width="441" alt="Screen Shot 2021-04-23 at 4 45 15 PM" src="https://user-images.githubusercontent.com/7570798/115927967-52017480-a453-11eb-9c7f-766c9edb7850.png">
<img width="441" alt="Screen Shot 2021-04-23 at 4 45 04 PM" src="https://user-images.githubusercontent.com/7570798/115927969-529a0b00-a453-11eb-8945-bd613df170b0.png">

What settings do you have for the Optimized Images field where you're using them?

**Comment by khalwat** [comment]
Yeah looking at the code you showed, it's working as expected. If the silhouette is larger than 30k:

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/services/Placeholder.php#L43

...it just returns a placeholder box for the image:

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/services/Placeholder.php#L195

...because the point of having a placeholder image is that it's significantly smaller than the image it's representing. That code you pasted in above will display, it'll just be a box.

**Comment by khalwat** [comment]
Actually you know what, I think I'll add a preference for this behavior. So if you really want large SVG outline placeholder, you can have them.

**Comment by jakepm** [comment]
@khalwat thank you for looking into this and that does make sense. I loved this silhoutte feature and got carried away with trying to use it for inappropriate images that cannot resolve into a lightweight vector. It worked nicely for team photos though!

A preference would be great to prioritise an expected output/display, although would there be a way to get notified on images exceeding 30k for follow-up action?

**Comment by khalwat** [comment]
Added a preference in https://github.com/nystudio107/craft-imageoptimize/commit/a0f7abff7ab37c4f1fdccdb7b4a911e0259e333a

**Comment by khalwat** [comment]
Released in https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.33
