### ISSUE TITLE
Lower Quality Retina Image Variants setting: potential replacement for 404 help text link

### ISSUE THREAD

**Issue by toddprouty** [nystudio107/craft3-imageoptimize#271]
The helper text beneath the _Lower Quality Retina Image Variants_ setting links to an article that is now 404:
"Controls whether retina images are automatically created with reduced quality as per [here](https://www.netvlies.nl/tips-updates/design-interactie/design-interactie/retina-revolution/)."

This [follow-up to the original article](https://www.netvlies.nl/blogs/retina-revolutie-follow) _might_ be a suitable replacement.

I didn't submit this as a pull request because, not having seen the original article, I'm not sure the follow-up supports the help text in the same way.

**Comment by khalwat** [comment]
I think maybe this one could work: https://alidark.com/responsive-retina-image-mobile/

**Comment by toddprouty** [comment]
I'm seeing a lot of broken image refs on that one.

**Comment by khalwat** [comment]
Yeah I'm not sure I can link to an article written in Dutch, however.

**Comment by khalwat** [comment]
Well, I guess it's better than nothing, and most browsers will offer to translate so... https://github.com/nystudio107/craft-imageoptimize/commit/227c85e890d28ff61b5d04a28942ae525ee77e80
