### ISSUE TITLE
Nested sub-folders for OptimizeImage field

### ISSUE THREAD

**Issue by Rees1993** [nystudio107/craft3-imageoptimize#274]
### Is your feature request related to a problem? Please describe.
You currently allow the functionality to only select subfolders but it's only 1 level. We have different transforms required for mobile and desktop so I have put them in nested folders, desktop and mobile respectively, but can't select them when filtering in CMS

### Describe the solution you would like
Be able to select nested subfolders  

### Describe alternatives you have considered
Could create more subfolders but it makes more logical sense to be nested

**Comment by khalwat** [comment]
Unfortunately this is unlikely to happen.
