### ISSUE TITLE
Job must be a JobInterface instance instead of __PHP_Incomplete_Class

### ISSUE THREAD

**Issue by Rees1993** [nystudio107/craft3-imageoptimize#275]
### Describe the bug
We have our site on AWS Fargate and have a queue listener set up, as per option 2 on this article: https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms#solution-2-forge-daemons

We are getting the following error:

```
Job must be a JobInterface instance instead of __PHP_Incomplete_Class#1 ( [__PHP_Incomplete_Class_Name] => 'nystudio107\\imageoptimize\\jobs\\ResaveOptimizedImages' [criteria] => [ 'siteId' => 1 'volumeId' => '1' 'status' => null 'enabledForSite' => false ] [fieldId] => null [force] => false [description] => 'Optimizing images in Carousel' [craft\queue\BaseJob:_progress] => 0 [craft\queue\BaseJob:_progressLabel] => null ).
```

### To reproduce
Steps to reproduce the behaviour:

1. Set up Queue Listener as per guide (in supervisor)
2. Try and run the the image optimiser
3. See error messageabove

### Expected behaviour
Run the queue as expected with images being created

### Screenshots
![image](https://user-images.githubusercontent.com/50775373/116439668-b3f11e00-a847-11eb-908f-0570cbbd8eda.png)

### Versions
- Plugin version: 1.6.33
- Craft version: 3.6.12

**Comment by khalwat** [comment]
re: the PR... are you sure this is the issue? Craft's jobs don't seem to implement `JobInterface`:

https://github.com/craftcms/cms/blob/develop/src/queue/jobs/ResaveElements.php#L24

I'm thinking this might be some other kind of issue potentially?

**Comment by Rees1993** [comment]
After further investigation, I believe you are right. I hastily believed that it needed JobInterface but overlooked the fact that BaseJob implements that already.

Turns out it was my setup on AWS - so I will close this and PR
