### ISSUE TITLE
[FR] Bind imageoptimize to asset fields, not source

### ISSUE THREAD

**Issue by ZapaNOR** [nystudio107/craft3-imageoptimize#278]
To reduce server load on generations (or taking down the server when we make a change to assets source), and space by having so many unused transforms, i would like to see an option where the optimize images transforms / field is connected to an asset field instead of an asset source (maybe it would have to be its own field type?).

This way I could have an asset field named "Profile image" or "Top banner" and just have the transforms for this field defined.
The transforms are generated in the CP on entry save (instead of asset upload).

Right now, with quite a few different transforms (top banner, inline images, full width slider, profile images etc), many of our projects ends up with a LOT of transformed images, one example has 300 real images, and 8000 transforms.

Many of these transforms comes from the slider and / or top banner transforms, since few images are used here, but they share asset source so the transforms are generated.

One solution could be to add separate asset sources for each of these types, but we feel that one source for all the "content images" fits best, where some images are used for many different scenarios, instead of users having to upload the same image to different sources if they want to use them in a banner or slider (to get the right transforms front-end).

(Profile images is an example that usually have its own asset source).

I understand this might not be desirable or feasible at all, but thought I could at least air the idea.

**Comment by khalwat** [comment]
Yeah I've thought about ideas like this. There are rubs involved, but I will be exploring them. Stay tuned!

As for "taking down the server" -- asset transforms are only always done one at a time in the queue job. So it doesn't matter how many you're doing, it will only ever do them one at a time, and so all that increases is the amount of time it takes to do them all, not the peak load on the server.
