### ISSUE TITLE
Request for inline CSS support

### ISSUE THREAD

**Issue by mikestecker** [nystudio107/craft3-imageoptimize#28]
It would be great to have an option to print the code in as inline CSS (complete with `@media` queries for all sizes/retina settings) for use as a `background: url(imagefile.here);` of a HTML element.

I'm thinking something along the lines of:
```
{% set optimizedImage = entry.myAsset.one().optimizedImageField %}
<div id="my-div" style="background-color: {{ optimizedImage.colorPalette().one() }}; {{ optimizedImage.srcsetCss() }}"></div>
```
Turns into (sloppy example but you get the idea):
```
{% set optimizedImage = entry.myAsset.one().optimizedImageField %}
<div id="my-div" style="background-color: #ff0000; background-image: url(/myAsset/mobileSize.jpg); @media only screen and (min-width: 768px) { background-image: url(/myAsset/tabletSize.jpg); }; @media only screen and (min-width: 980px) { background-image: url(/myAsset/desktopSmall.jpg); }; @media only screen and (min-width: 1280px) { background-image: url(/myAsset/desktopMed.jpg); }; @media only screen and (min-width: 1440px) { background-image: url(/myAsset/desktopLarge.jpg); };"></div>
```

Thoughts?

**Comment by mikestecker** [comment]
I just realized you can't do inline `@media` queries... but maybe if support could be added to generate a `<style>` tag instead?

**Comment by khalwat** [comment]
So FWIW, you can roll your own via Twig pretty easily... but the way I'd approach it for background images would be to use LazySizes' bgset plugin: 

https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/bgset
