### ISSUE TITLE
Images gone after updating

### ISSUE THREAD

**Issue by newtonfreelance** [nystudio107/craft3-imageoptimize#281]
Hi I have updated a clients website that uses imageoptimize and imgix, once updated all images are gone on all of the pages.

console just says 404. In an attempt to fix I have done the following:

1. updated asset index's
2. cleared caches
3. created a new api in imigix
4. looked through your github error log (couldnt see anything).

website is https://perlaphotography.com.au/

**Comment by khalwat** [comment]
I'm getting a 500 error trying to load that URL, so I can't glean any information from it.

But check your Craft CMS logs for errors -- and ensure the Imgix account is up to date and functioning

ref: https://nystudio107.com/blog/zen-and-the-art-of-craft-cms-log-file-reading

**Comment by newtonfreelance** [comment]
Apologies I didn't think you would reply that quick...thanks!

I deleted the vendor file and updated craft to see if that helped when you got the 505

I am looking in the logs they seem ok?

**Comment by newtonfreelance** [comment]
It's ok figured it out. I was missing a ? in the url which didn't seem to matter before but does now.

Thanks for you quick reply earlier. Appreciate it.
