### ISSUE TITLE
Setting a subfolder not saved to project configs.

### ISSUE THREAD

**Issue by gjhead** [nystudio107/craft3-imageoptimize#282]
### Question
I'm not sure if this is a bug or is intentional.  But when editing an Optimized Images field, if I select a subfolder for aunder the _"Create Optimized Image Variants for images in the sub-folders:"_ it doesn't get saved to the project config.  So if I commit these to me repo, and deploy to staging, I need to  go back into the field and re-check the folder.  Normally this would be a trivial edit, but whenever I push to Production, I have "allowAdminChanges" set to false, so I am unable to edit this field on Production.  

### Additional context
It seems odd to have to edit this one setting manually each time I push to a new environment.

**Comment by khalwat** [comment]
mmmm that doesn't sound right... those fields settings should be saved in the Project Config data, just like any other setting.

Are you automatically applying project config on deploy, and clearing caches, etc.?

**Comment by gjhead** [comment]
It's strange. I have had it happen a few times on this specific site I am working on.  I'm hosting it on servd, so each deploy is a brand new build with clean cache.  I'll recreate my steps again tomorrow so I can get some more specific info to you.

**Comment by gjhead** [comment]
OK - just pushed a new build and I am seeing this happen again.  Attached are a few things:

Screenshot of Stage on the left and Local on the right.  Local shows the sub-folder being selected, and Stage shows it's not selected.

![Screen-Shot-2021-06-03-at-5 40 31-PM](https://user-images.githubusercontent.com/192508/120716727-6d20c480-c494-11eb-853e-a4d22d7318fb.png)


Also the .yaml file for this specific field from my local machine so you can see what data is being saved to it.  Github won't let me attach the .yaml file  - but I posted it at this dropbox link:

https://www.dropbox.com/sh/fgz6l7rivs0m5l3/AACdZnoFLDQgLATyAfDuNdLEa?dl=0

The only other thing that I can think of  that may be effecting this, is that all of my Asset volumes are being pushed to AWS. using the Amazon S3 Plugin from Pixel and Tonic, V 1.2.11

**Comment by khalwat** [comment]
Okay, I just realized what this is... it's actually storing the information in project config as it should, but the volume IDs must be different on production than in your local dev environment.

**Comment by khalwat** [comment]
Related to: https://github.com/craftcms/cms/issues/7742

(@mildlygeeky  never filed an issue here)

So my thought on how to fix this would be to use the sub-folder name as what to key off of, rather than the UID. This is still fragile, in that the user can then rename the sub-folder and it'll break but... there's nothing I can see that will stay constant here.

**Comment by gjhead** [comment]
Ah, ok I see now.  Well, at least I didn't get to far into this particular problem, and I should be able to just pull down my database and make a few edits, so I can get all my environments synced.  Live and learn!  Thanks again, Andrew!

**Comment by khalwat** [comment]
I intend to fix it!

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/a8a44041c319e664dfc62437f5892128e55b981e

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.34”,
```
Then do a `composer clear-cache && composer update`

**Comment by gjhead** [comment]
Hey! Seems to work so far!  Thanks for address this so quickly.  You saved me a ton of time today!  It's awesome having people like you in the Craft community!

**Comment by khalwat** [comment]
Thanks for your patience -- will likely release it today!
