### ISSUE TITLE
Replacing an Asset with original filename fails to generate variants

### ISSUE THREAD

**Issue by maccadesign** [nystudio107/craft3-imageoptimize#283]
### Description
When replacing assets with the same filename variants don't regenerate. 

### To reproduce
Steps to reproduce the behaviour:
1. Install Image Optimize
2. Upload an asset
3. Replace asset using the same filename as original.
4. Asset is replaced but image variants are not regenerated.

### Expected behaviour
Variants should be regenerated

### Versions
- Image Optimize: 1.6.33
- Amazon S3: 1.2.11
- Craft version: Craft Pro 3.6.12

**Comment by khalwat** [comment]
To be clear, you're using S3 as your asset volume repository here yes?

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/053734913fe4028a23b3bfe152c148da58952c95

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.34”,
```
Then do a `composer clear-cache && composer update`
