### ISSUE TITLE
Force creation of webp variants on a specific asset from the Craft Dashboard.

### ISSUE THREAD

**Issue by houtaiwong-toast** [nystudio107/craft3-imageoptimize#288]
### Is your feature request related to a problem? Please describe.

This feature request stems from an issue I'm having with some of my image assets. Sometimes the webp variants are not actually created, they show up with the url but the image is empty. 

### Describe the solution you would like

I would love a way to force the creation of those webp variants from the asset dashboard. Just like running the specific CLI command you have in your documentation. Unfortunately with my project, I don't have ssh access to prod to run that command.

`php craft image-optimize/optimize/create-asset 101 --force`

### Describe alternatives you have considered

I could try and gain access to the server, but it is unlikely.

### Additional context

![image](https://user-images.githubusercontent.com/55763151/124960491-6254d480-dfea-11eb-808d-6912729c2ae2.png)

**Comment by khalwat** [comment]
You are completely unable to gain ssh access to the server in question here?

The issue is that Craft CMS does not re-create image transforms if the transforms already exist on disk. So another option you'd have would be to delete all of the transforms (via ftp client or the like) and then re-save the image transforms.

**Comment by houtaiwong-toast** [comment]
Unfortunately the project i'm working on is in a Fargate set up so there is no ssh access.

**Comment by khalwat** [comment]
No way to access whatever container is being used for persistent storage?

Alright let's see if there isn't some way to do this for you.

**Comment by houtaiwong-toast** [comment]
Thank you for the help, but actually it seems like a non-issue now. Their assets are connected/uploaded to s3. So i've connected my local with their bucket and was able to run the cli commands locally which would give the same naming url convention as the production db as well as uploading to the same folder in S3.

Thanks for your time!
