### ISSUE TITLE
No images generated on Craft 3.7

### ISSUE THREAD

**Issue by almeric** [nystudio107/craft3-imageoptimize#289]
### Describe the bug
Due to this change in Craft 3.7: https://github.com/craftcms/cms/issues/6922 updating the field data is broken because the column name is incorrect in https://github.com/nystudio107/craft-imageoptimize/blob/4810447c2b65714c2da4fe0ffc270200976b67d4/src/services/OptimizedImages.php#L278

A possible solution would be to use `$field->columnSuffix` to fetch the suffix of the field.

### To reproduce
Steps to reproduce the behaviour:
1. Update to craft 3.7
2. Create new ImageOptimize field
3. Upload an asset/Use the console to create optimized variant

### Expected behaviour
Generated optimized variants & placeholder info

### Versions
- Plugin version: 1.6.34
- Craft version: 3.7

**Comment by almeric** [comment]
Our current quick and dirty™ fix (not accounting for older versions of craft):

```php
$column = $asset->getFieldColumnPrefix().$field->handle . ($field->columnSuffix ? '_'. $field->columnSuffix : '');
```

**Comment by khalwat** [comment]
Thanks for the detailed report -- are any of these attributes specific/new to 3.7? Looking to see if I need to be special-casing things based on the Craft version.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/b62be7c0c611b6b37941a17fce3ffbe8653f690c

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.35”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Fix confirmed:

<img width="1178" alt="Screen Shot 2021-07-14 at 12 36 48 PM" src="https://user-images.githubusercontent.com/7570798/125659524-6b56788f-74a9-498f-a857-137441f99b75.png">

**Comment by khalwat** [comment]
Released as https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.35

**Comment by almeric** [comment]
Awesome! Thanks for the quick fix!
