### ISSUE TITLE
Clear Cache / Transforms

### ISSUE THREAD

**Issue by davidhellmann** [nystudio107/craft3-imageoptimize#29]
What's the right way to clear Image Caches. 
Case is: The Client changes the Focal Point but no images are recreated.
I must delete them manually from /web/uploads/images/XXX

Imager have the Option to Select an Image within the Assets and Choose: "Clear Transforms"
Maybe that would be a solution for ImageOptimize

**Comment by nielsnuebel** [comment]
https://github.com/craftcms/cms/blob/develop/src/services/AssetTransforms.php#L1362 Craft3 Bug. $asset is old it come from the DB https://github.com/craftcms/cms/blob/develop/src/services/AssetTransforms.php#L588

**Comment by khalwat** [comment]
@nielsnuebel sounds like something they need to fix in Craft 3? Is there a bug report anywhere on https://github.com/craftcms/cms/issues ?

**Comment by khalwat** [comment]
Related: https://github.com/craftcms/cms/issues/2285

**Comment by khalwat** [comment]
So the long and the short of it is that there's an issue when you change the Focal Point, and I'm not sure what the best way to solve it is.

In the interim, if you go to Edit Image and move the Focal Point a _second_ time, it will use the Focal Point that was _previously_ set.

So you can just move the Focal Point a little to the left or a little to the right, save it, and all should be well.

And yes, I realize that this is very non-ideal.

**Comment by khalwat** [comment]
Fixed in 1.4.8:

https://github.com/nystudio107/craft3-imageoptimize/releases/tag/1.4.8

**Comment by Wiejeben** [comment]
Am currently experiencing the same issue. The supposed `?mtime=20190112172325` at the end of the URL does not change after changing the focal point.

Craft 3.0.37
ImageOptimize 1.5.1

Volume type is Google Cloud Storage with a cache duration of 7 days.
