### ISSUE TITLE
duplicate Queue Jobs

### ISSUE THREAD

**Issue by aloco** [nystudio107/craft3-imageoptimize#290]
### Describe the bug
After deploying an update to an existing site, I can see multiple imageoptimized tasks which takes a long time for ~5.900 assets. I have 2 active sites.

Here is the description of two jobs which are queued after each other
```
{
    "criteria": {
        "siteId": 2,
        "volumeId": "1",
        "status": null,
        "enabledForSite": false
    },
    "fieldId": null,
    "force": false,
    "description": "Optimizing images in Uploads"
}
```

```
{
    "criteria": {
        "siteId": 2,
        "volumeId": "1",
        "status": null,
        "enabledForSite": false
    },
    "fieldId": "626",
    "force": false,
    "description": "Optimizing images in Uploads"
}
```

`626` is the optimized image field id (there is only one imageoptimized field in this installation)

there are another 2 jobs for siteId 1

I guess the job with field id `null` just means check all fields, when this job is running, there shouldn´t be other jobs beeing enqueued for specific fields.

JFYI this is the same project which is affected by this https://github.com/nystudio107/craft-seomatic/issues/932

thank you for your help

Update:
it seems that exactly the same jobs are queued another time (just saw this later in the queue)
```
{
    "criteria": {
        "siteId": 2,
        "volumeId": "1",
        "status": null,
        "enabledForSite": false
    },
    "fieldId": null,
    "force": false,
    "description": "Optimizing images in Uploads"
}
```

### To reproduce
Steps to reproduce the behaviour:
1. create one single imageoptimize field and add some assets.
2. add another site so you have 2 in total.
2. deploy your site similar to this approach https://nystudio107.com/blog/executing-atomic-deployments
3. see multiple jobs for each site

### Expected behaviour
only 1 image optimize job for each site, currently I can see 4

### Versions
- Plugin version: 1.6.34
- Craft version: 3.6.18

**Comment by aloco** [comment]
It seems like 4 of those jobs are spawned when doing `project-config/apply --force` probably because the fields and asset volumes are updated although there are no changes - that might trigger those jobs. We shouldn´t use `--force` for deployments. Going to close this because it´s not really an issue of this plugin. However, some kind of guaring against this would be an enhancement imho.

**Comment by khalwat** [comment]
There is a feature to disable the automatic image generation (which you generally want on though) https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/config.php#L49
