### ISSUE TITLE
Image optimization preview issue FF

### ISSUE THREAD

**Issue by mikewink** [nystudio107/craft3-imageoptimize#291]
### Describe the bug

When viewing previews in Firefox browsers (latest Firefox 91, Dev Edition 91 and Nightly Build 93) I see no correct .webp column and preview file sizes. I see the .jpeg column twice. That happens only in Firefox. In Chrome Canary 93, Ungoogled Chrome 91 and Microsoft Edge 94 I see the correct preview. 

The FF Nightly build has zero plugins or modified settings. The FF Developer Edition has no special plugins or settings either. 

The ImageOptimze info pane shows check marks for all optimizers including cwebp. And looking at the server I see the smaller .webp files generated and used.

### To reproduce

I use the plugin in several projects. I tested in two of them with the same result. To reproduce just follow the regular instructions of installing and configuring your excellent plugin. 

### Expected behaviour

I am used to see the left and right being different in that the size of .webp files should be smaller.

### Screenshots

<img width="464" alt="Screenshot 2021-08-17 at 08 48 34" src="https://user-images.githubusercontent.com/85063626/129678678-2993e337-9f70-4180-9773-4e335a7833cc.png">
<img width="464" alt="Screenshot 2021-08-17 at 08 48 59" src="https://user-images.githubusercontent.com/85063626/129678691-9e0835fe-92d9-4b4e-a103-cebfb4012c4b.png">

### Versions
- Plugin version: 1.6.35
- Craft version: 3.7.8

**Comment by khalwat** [comment]
I'm thinking this is probably just a bug in the nightly; if the browser doesn't support _displaying_ `.webp` files, but the server is capable of creating them, it will display the `.jpg` version instead (thus the sizes being the same).
