### ISSUE TITLE
image-optimize.php

### ISSUE THREAD

**Issue by LieselotV** [nystudio107/craft3-imageoptimize#293]
Hi,

I took the courses on craftquest to setup imageOptimize. When I replaced the settings with image-optimize.php, it worked and everything showed green under 'installed'.
But when I transferred my local code to online. It's no longer installed, even though I am still using the same file: image-optimize.php file.
What am I doing wrong?

L

**Comment by khalwat** [comment]
I'm assuming you mean the image optimizers -- you'll need to install those on your production server, too. Details are here:

https://nystudio107.com/docs/image-optimize/configuring.html

**Comment by LieselotV** [comment]
Hi, 
It's not possible for me to install it on the production server that I rent. Is there another way to still use this feature? (webp)
