### ISSUE TITLE
SQL Error when generating placeholder images

### ISSUE THREAD

**Issue by d-karstens** [nystudio107/craft3-imageoptimize#296]
### Describe the bug
Hi,

We have a public facing form for people to upload images which we run through Image Optimize as they are usually huge, and lately we've been having an issue where the following error pops up in our logs when trying to create image variants
```2021-11-11 10:05:25 [-][-][-][error][nystudio107\imageoptimize\jobs\ResaveOptimizedImages::execute] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'field_optimizePetListings' at row 1```

I've manage to narrow it down a bit and it seems to be happening because of something in an images exif data, as we have the `preserveExifData` config setting turned on and uploading the same image that errors without any exif data seems to work correctly. Though it seems to be something specific in the exif as most images have been working correctly.

It looks like it's also generating a placeholder image specifically that's causing it, as shown in the attached screenshot - the string just goes on across multiple pages

We have tried to make images smaller on upload using Image Resizer, but it didn't seem to help

Here are two examples of images that people have uploaded, one that works and one that doesn't

https://drive.protonmail.com/urls/D0E9JYWRC8#yy2nMkZcmjg5
https://drive.protonmail.com/urls/Q8SMXJPZQG#1Rn52jXlcRCe

It seems to have started recently, maybe with with 3.7 changes

Hopefully this is enough info, but let me know if any more is required

### Screenshots
![Screen Shot 2021-11-11 at 12 36 03 pm](https://user-images.githubusercontent.com/21274925/141224464-c7da27f3-f377-46f8-a666-5f5916ef6daf.png)

### Versions
- Plugin version: 1.6.36
- Craft version: 3.7.20

**Comment by khalwat** [comment]
So I'm going to suspect something just isn't right with this particular image. It's probably not something specific to ImageOptimize, and rather it's dying at a lower level in GD or ImageMagick.

Can you just strip the exif data for this image, and then upload it?

**Comment by d-karstens** [comment]
Ah, that's unfortunate
Initially we were stripping exif data, but then there was an issue with some images being uploaded with the wrong orientation - seems like a dammed if we do, dammed if we don't situation

Maybe we'll just have to stick with using Image Reiszer instead of optimizing these particular images

Thank you for the quick response!

**Comment by khalwat** [comment]
Maybe I misunderstood -- is this happening for more than one image?

I was assuming it was just one image that was having this problem, and then thought that perhaps something was corrupted with that image?

**Comment by d-karstens** [comment]
Oh sorry for the confusion, yeah - it's happening on a number of different images, from a few different users/devices

**Comment by khalwat** [comment]
What placeholder images are you generating? The silhouette placeholder images for instance can be quite large... and if you're not using them you could turn them off.

**Comment by d-karstens** [comment]
This is just using the standard low res placeholder image, the silhouette and color palette ones are already turned off.

I can't see if there's a way to there a way to turn those off too per volume or field, is that possible?

**Comment by khalwat** [comment]
So here's what would be really helpful. If you're able to reproduce the issue in local dev, delete all of your logs in `storage/logs/` and then make the issue happen, and then attach your logs here, or email them to: andrew@nystudio107.com

I'd like to see if I can find any trace of what could be going wrong here.

Also are you using GD or ImageMagick?

**Comment by khalwat** [comment]
Released as 1.6.37 -> https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.37
