### ISSUE TITLE
Image Ratios are Broken after Save

### ISSUE THREAD

**Issue by davidhellmann** [nystudio107/craft3-imageoptimize#30]
I Create the Field and save:
![image](https://user-images.githubusercontent.com/764292/34654031-fac1ef26-f3f5-11e7-8fb8-88a9ebf0f4e4.png)

Now I go back into the field and it looks like this: 
![image](https://user-images.githubusercontent.com/764292/34654039-0f9187ea-f3f6-11e7-9dea-cc10d77ead2a.png)

Newest Version.

**Comment by khalwat** [comment]
@davidhellmann Did you change the settings in the `config.php` in the interim or such? It will default to a single transform of `16:9` if there is something wrong with the `config.php`

**Comment by davidhellmann** [comment]
No nothing changed in the config. Tried it also with a new field. Can do that again later today.

**Comment by khalwat** [comment]
Was this also fixed by your `brew update` local dev update?

**Comment by khalwat** [comment]
I'm unable to replicate this with `1.4.8` using the config you pasted in for that:

```
    ['x' => 16, 'y' => 10],
    ['x' => 16, 'y' => 9],
    ['x' => 4, 'y' => 3],
    ['x' => 1, 'y' => 1],
    ['x' => 10, 'y' => 16],
    ['x' => 3, 'y' => 4],
    ['x' => 3, 'y' => 4],
```

I'm able to create a new field, save it, and edit it, and everything continue to be correct.
