### ISSUE TITLE
SVG optimization command fails due to missing space between command and file path

### ISSUE THREAD

**Issue by bfopma** [nystudio107/craft3-imageoptimize#300]
### Describe the bug
On line 664 of craft-imageoptimize/src/services/Optimize.php, command options are concatenated and padded with spaces *only* if $thisProcessor['commandOptions'] isn't empty. All of the image optimizers except `svgo` have default command options in the config. If using `svgo`, it fails because a space is missing between the command and path in the absence of a command option.

For example:

```
2021-11-12 10:49:52 [-][-][-][profile begin][nystudio107\imageoptimize\services\Optimize::optimizeImage] optimizeImage
2021-11-12 10:49:52 [-][-][-][info][nystudio107\imageoptimize\services\Optimize::executeImageProcessor] /usr/bin/svgo'/app/storage/runtime/temp/7_Text_v1618e9b30d101f3.73745519.svg'
sh: 1: /usr/bin/svgo/app/storage/runtime/temp/7_Text_v1618e9b30d101f3.73745519.svg: not found
```

### To reproduce
Steps to reproduce the behaviour:

Config:
```
'svgo' => [
       'commandPath' => '/usr/bin/svgo',
       'commandOptions' => '',
       'commandOutputFileFlag' => '',
],
```

Create an image transform to trigger optimization on an SVG:

```
{% set transform = {
   quality: 100
} %}

{{ svg.getUrl(transform) }}
```

### Versions
- Plugin version: 1.6.37
- Craft version: 3.7.20

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/33c612fd6eaa02c460a7406a0350f1fc5a45b8bc

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.38”,
```
Then do a `composer clear-cache && composer update`
