### ISSUE TITLE
Webp imageprocessor available but previews as 404

### ISSUE THREAD

**Issue by alanski66** [nystudio107/craft3-imageoptimize#302]
### Question
I have all Image Processors & Variant Creators available apart from svgo

It creates jpegs fine but next to the jpeg are broken webp images (404s)
Screenshot here:https://www.dropbox.com/s/dimq2sk7a2k9csz/Screenshot%202021-11-22%20at%2017.43.55.png?dl=0

I dont mind disabling webp if possible as Icant have cleints looking at this :)

Im using php7.4 and latest craft version
My image driver is Imagick 3.6.0 (ImageMagick 6.9.10-68)

Am i missing some dependencies?

**Comment by khalwat** [comment]
Did you install `cwebp` ?

Click on the broken image, what URL does it try to open up?

When you look at the actual transformed images on disk, are there `.webp` images next to them?

**Comment by alanski66** [comment]
Url is assets/images/projects/_1200x675_crop_center-center_82_line/115296/Clubhouse-Project-Bedford-Creative-Arts.jpg.webp?mtime=1637603025
There are no .webp images to be seen in destination folders

I can use CLI:  cwebp -q 100 David.jpg -o david.webp
which works fine.

**Comment by khalwat** [comment]
My guess is you added webp support in after the image variants were already generated.

You can force their regeneration via the CLI command:

```bash
php craft image-optimize/optimize/create myVolumeHandle --field=myFieldHandle --force
```

ref: https://nystudio107.com/docs/image-optimize/using.html#forcing-image-variant-creation
