### ISSUE TITLE
Unable to update 1.6.19 to 1.6.38 due to Composer error

### ISSUE THREAD

**Issue by stevehurst** [nystudio107/craft3-imageoptimize#303]
Running local dev environment on Nitro, I'm attempting to run a big update to Image Optimize from 1.6.19 to 1.6.38 via console and get the following error dump from Composer:

```
Performing update with Composer ... error: Unknown downloader type: . Available types: git, svn, fossil, hg, perforce, zip, rar, tar, gzip, xz, phar, file, path.

Output:

Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 5 updates, 0 removals
  - Upgrading nystudio107/craft-imageoptimize (1.6.19 => 1.6.38)
  - Upgrading nystudio107/craft-imageoptimize-imgix (1.1.3 => 1.2.3)
  - Upgrading nystudio107/craft-imageoptimize-sharp (1.0.5 => 1.0.8)
  - Upgrading nystudio107/craft-imageoptimize-thumbor (1.3.0 => 1.3.1)
  - Upgrading webfactory/phumbor (1.2.3 => 1.3.0)
Writing lock file
Installing dependencies from lock file
Package operations: 0 installs, 5 updates, 0 removals
  - Upgrading webfactory/phumbor (1.2.3 => 1.3.0): Extracting archive
    Update of nystudio107/craft-imageoptimize failed
  - Upgrading nystudio107/craft-imageoptimize-thumbor (1.3.0 => 1.3.1): Extracting archive
  - Upgrading nystudio107/craft-imageoptimize-sharp (1.0.5 => 1.0.8): Extracting archive
  - Upgrading nystudio107/craft-imageoptimize-imgix (1.1.3 => 1.2.3): Extracting archive
```

I've updated Craft to 3.7.22.

### System Report Dump
**Application Info**

PHP version	7.4.22
OS version	Linux 5.10.47-linuxkit
Database driver & version	MySQL 5.7.35
Image driver & version	Imagick 3.5.1 (ImageMagick 7.0.11-13)
Craft edition & version	Craft Pro 3.7.22
Yii version	2.0.43
Twig version	v2.14.7
Guzzle version	7.4.0

**Plugins**

Asset Usage	2.2.1
AsyncQueue	2.3.0
Calendar Links	1.0.1
Child Me!	1.2.0
Control Panel CSS	2.4.0
Control Panel JS	2.4.0
Control Panel Nav	3.0.17
Cookies	1.1.15
CP Element Count	1.1.0
CP Field Inspect	1.2.5
Craft Redactor Script Buttons	1.1.1
Element Index Defaults	2.0.2
Entries Subset	1.2.3
Expanded Singles	1.1.4
Feed Me	4.4.0
ImageOptimize	1.6.19
Language Redirector	1.5.3
Layout Buttons	1.0.0
Linkit	1.1.12.1
Many to Many Field Type	1.0.2.2
Matrix Colors	2.0.1
Matrix Toolbar	1.0.6
PdfShift	1.1.1
Phone Number	1.5.0
Queue Manager	1.2.0
Redactor	2.8.8
Redactor Custom Styles	3.0.4
Retcon	2.3.0
Retour	3.1.67
SCSS	1.0.0
Searchit	1.0.8
SEO and Contact Settings	3.4.20
Sidebar Toggle	3.0.2
Similar	1.1.5
Single Cat	1.2.1
Site Switcher	2.2.0
Snitch	3.0.4.1
Spoon	3.6.1
Sprig	1.10.4
Super Table	2.6.8
Tags	1.0.9
Videos	2.0.15
Wordsmith	3.3.0.1

**Modules**

verbb-base	verbb\base\Base
sprig-core	putyourlightson\sprig\Sprig

**Requirements**
_Green checks for all_

PHP 7.2.5+ 
PDO MySQL extension 
MySQL 5.5.0+ 
MySQL InnoDB support 
MySQL timezone support 
Sensitive folders should not be publicly accessible 
Reflection extension 
PCRE extension (with UTF-8 support) 
SPL extension 
PDO extension 
Multibyte String extension (with Function Overloading disabled) 
GD extension or ImageMagick extension 
OpenSSL extension 
cURL extension 
ctype extension 
ini_set calls 
Intl extension 
Fileinfo extension 
DOM extension 
iconv extension 
Memory Limit 
Max Execution Time 
password_hash() 
Zip extension 
JSON extension 
proc_open() 
proc_get_status() 
proc_close() 
proc_terminate() 
allow_url_fopen 
ignore_user_abort()

**Comment by khalwat** [comment]
Not sure what to say here, other than I don't think it's an issue with ImageOptimize

A Google search finds that it may have something to do with your Composer cache:

https://stackoverflow.com/questions/29419516/composer-unknown-downloader-type-h-getting-this-error-for-a-repo-on-packigi

lmk if this doesn't resolve it for you; but I've been able to update ImageOptimize on a number of sites without issue.
