### ISSUE TITLE
[Support] Assets are all transformed again after a deployment, how do I stop this?

### ISSUE THREAD

**Issue by zizther** [nystudio107/craft3-imageoptimize#305]
I am having an issue where after each deployment (via atomic deployments on Ploi) it is having to recreate all image transforms for all assets, even though previously it has gone through them all.

My setup is:

- I have the temp asset folder pointing to a volume on S3
- Images hosted on S3
- Images are generally around 1-3mb, but some are up to 4mb with a width of 6000px
- I have Imgix as the transformer
- On each deployment all caches are cleared, not sure if this would have an affect

I run the CLI command to create the image transforms on the server `php craft image-optimize/optimize/create`

After running a deployment I notice that all images have to be transformed again, it seems that the cache maybe gone, as when running this command over images already cached it does not recreate these.

There are a couple of questions I have:

1. How does ImageOptimize know that an asset has been optimised already, is this stored in the runtime folder?

2. Even though I have Imgix being used as the transformer I can see that Imagick is running, is this for a reason?

**Comment by khalwat** [comment]
Clearing the caches does not affect the transformed images. It's likely the transform index, which is a Craft-ism, which is being rebuilt. It's not actually regenerating the transforms, just the transform index.
