### ISSUE TITLE
Fatal error on Assets page due to asset "missing its width or height"

### ISSUE THREAD

**Issue by alexwybraniec** [nystudio107/craft3-imageoptimize#306]
### Describe the bug
When loading Assets page, I get a "A server error occurred." has occurred, and no assets show. If I check web.log, it says there is an asset that "is missing its width or height", which leads to 

`yii\base\ErrorException: Division by zero in /usr/share/nginx/MY_PROJECT_NAME/staging/vendor/nystudio107/craft-imageoptimize-imgix/src/imagetransforms/ImgixImageTransform.php:146`

I have cleared all caches and rebuilt my assets index.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Assets in CP
3. See error message "A server error occurred." in red notification at top of CP page.

### Expected behaviour
Should be able to see assets in Assets section.

### Versions
- Plugin version: 1.6.38
- Craft version: Craft CMS 3.7.23 Pro

### Extended log
https://gist.github.com/alexwybraniec/823ffd62032ac9aa259c1c44b58cdf8e

**Comment by khalwat** [comment]
Probably there is an issue with a source image, but this error shouldn't happen. I'll get it addressed.

**Comment by alexwybraniec** [comment]
@khalwat Thank you. Did some more digging, and this and another image were causing the fault.  Both seem to be failed uploads as they were showing 0kb on the filesystem. Now that I've deleted them both and reindexed the assets, Assets is working again.

**Comment by khalwat** [comment]
Yeah I figured -- still, I think we should fail more gracefully here. I'll have a look.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize-imgix/commit/4d14fe9d36cc7add443c56cd11857ee0f350a125
