### ISSUE TITLE
File(/usr/bin/jpegoptim) is not within the allowed path(s)

### ISSUE THREAD

**Issue by hhentschel** [nystudio107/craft3-imageoptimize#309]
### Question
I installed the plugin several month ago, but just now i wanted to set it up.
When i want to open the settings i get the followoing error page:
`is_file(): open_basedir restriction in effect. File(/usr/bin/jpegoptim) is not within the allowed path(s): `

This is surprising, because the settings page worked in the beginning and i cannot recall that something changed 
regarding filepath setting, or why other changes on the website should have an affect on this settings.

should i really change the php settings as described here?
https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths

site is not local, but on a dev server not hosted by myself.

**Comment by khalwat** [comment]
This is a restriction of your hosting environment:

https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths

You'll have to install the optimizers somewhere that is not restricted by your hosting environment, get them to lift the `open_basedir` restriction, or move to hosting that does not have this restriction, unfortunately.
