### ISSUE TITLE
ImageOptimize not using Imgix urls in Craft control panel

### ISSUE THREAD

**Issue by fredrik-sogaard** [nystudio107/craft3-imageoptimize#312]
### Question
On our production environment if I click the "View" button when viewing an asset, it takes me to an Imgix url. This is what I'm expecting. On our staging environment the same button takes med to our S3 storage where the files is originally located. This is not what I'm expecting.

This is probably caused by updated versions of Craft and/or ImageOptimize, but what is the expected behavior? Should the native Craft asset's url turn into an imgix url or not?

See screenshot: https://cln.sh/7G0Fvj
I've noted the difference in Craft and ImageOptimize versions.

**Comment by fredrik-sogaard** [comment]
I updated our staging environment to Craft CMS 3.7.30.1 and ImageOptimize 1.6.41 with the same results.

**Comment by khalwat** [comment]
It must be something environmental, are you sure the ImageOptimize config is set to do the same thing on your staging and on your production environments? Perhaps in the `config/image-optimize.php` config file?

**Comment by khalwat** [comment]
Will re-open if more information is provided
