### ISSUE TITLE
Specifying src still loads original size despite passing a width

### ISSUE THREAD

**Issue by alanski66** [nystudio107/craft3-imageoptimize#313]
### Question
Regarding using srcset
https://nystudio107.com/docs/image-optimize/using.html#img-srcset
The <img> src  is loading the original hi res image despite me passing in the width 
```
    {% set optimizedImages = asset.optimizedImages %}
    <img src="{{ optimizedImages.src(576) }}"
    srcset="{{ optimizedImages.srcset() }}"
    sizes="100vw" />
```

Latest versions as of date of post. 

Displaying the original src size as isn't desirable if its 3000px wide - am I missing something?

**Comment by alanski66** [comment]
NB to add chrome or FF don't seem to pay any attention to anything other than the file specified in src. I am checking the img properties currentSrc value in dev tools

**Comment by khalwat** [comment]
It is possible that no image exists for this size? It doesn't resize to what you pass in, it just looks up the images:

https://github.com/nystudio107/craft-imageoptimize/blob/develop/src/models/OptimizedImage.php#L137

Edit to add: Yes, if you use `currentSrc` you will end up seeing different results. Try out https://github.com/ausi/respimagelint

**Comment by alanski66** [comment]
> It is possible that no image exists for this size? It doesn't resize to what you pass in, it just looks up the images:
Well I'm upscaling them as I keep getting message that image can be created because it would be upscale all. Image is 300px wide 5MB so I was ignoring that as I couldn't make sense of the message :) I just set upscale to true...
And yes the variants are there...
> https://github.com/nystudio107/craft-imageoptimize/blob/develop/src/models/OptimizedImage.php#L137
> 
> Edit to add: Yes, if you use `currentSrc` you will end up seeing different results. Try out https://github.com/ausi/respimagelint
(Bookmmark thingy doesnt seem to do anything when dragged to bookmarks)
Yes I am expecting to see a specific image at different breakpoints / devices but it always shows the same original src asset

**Comment by khalwat** [comment]
It's almost certain that it's working as expected, sometimes browsers can be annoying in terms of figuring out exactly what is being displayed.

But if you have provided the srcset it will pick from it using the sizes= rules
