### ISSUE TITLE
Deprecated DPR srcset syntax?

### ISSUE THREAD

**Issue by robbeman** [nystudio107/craft3-imageoptimize#316]
### Question
> To use the mostly deprecated 1x, 2x DPR srcset syntax, you can do that by passing in true:

See [Media Query srcset Sizes](https://github.com/nystudio107/craft-imageoptimize/blob/afb2cd735998f9cc86daba81e4a64faba41fe263/docs/docs/using.md?plain=1#L349) What's meant by "mostly deprecated"? We currently rely on this to address the following issue.

### Additional context

In some cases we use different aspect ratios for different device widths, combine this with different screen densities and you get in some trouble. Some desktop screens with higher pixel densities might get variants meant for mobile screens because the standard implementation just returns a sorted array of image widths and does not consider screen densities.

Some MacBooks with @2x screens seemed to select wrong images until resizing and triggering a breakpoint, then they seemed to keep using the correct source. Using different `source` elements with media queries we are able to be more specific in which images are loaded.

Our fix using the "mostly deprecated" syntax:
```twig
  <picture>
    {% set renderedWidths = [] %}
    {% set webp = craft.imageOptimize.serverSupportsWebP() %}

    {%- for width in optimizedImages.variantSourceWidths if width not in renderedWidths -%}
      {# render an image source for this specific breakpoint with pixel densities #}
      <source {{ attr({
        srcset: webp ? optimizedImages.srcsetWidthWebP(width, true) : optimizedImages.srcsetWidth(width, true),
        type: webp ? 'image/webp' : null,
        media: '(min-width: ' ~ width ~ 'px)',
        sizes: '100vw',
      }) }}>

      {# mark as rendered, because variantSourceWidths contains duplicates for different pixel densities #}
      {% set renderedWidths = renderedWidths|merge([width]) %}
    {%- endfor -%}

    {# render the actual image container #}
    <img src="{{ optimizedImages.src() }}" class="{{class|default}}" alt="{{alt|default(asset.title|default)}}" />
  </picture>
```

**Comment by khalwat** [comment]
For separate aspect ratios, I recommend using separate Optimized Images fields. Think of each Optimized Images field as encompassing a single `<source srcset>`. This allows you to have entirely separate images for separate srcset media queries.
