### ISSUE TITLE
Optipng installed, but does nothing

### ISSUE THREAD

**Issue by brandondeweese** [nystudio107/craft3-imageoptimize#318]
### Question
Optipng installed and recognized by Image optimize, but optimization doesn't happen. Any ideas on how to get this to work?

### Additional context
![Screen Shot 2022-02-24 at 7 23 41 AM](https://user-images.githubusercontent.com/18017918/155560577-e54ba013-60d6-4a63-a5d7-67e7ccfbdf97.png)

**Comment by khalwat** [comment]
How do you know that the optimization doesn't happen?

Image optimization takes place when the transforms are created, so you're adding this post-facto, and the transform already exists, it won't be run.

You can force image transforms to be regenerated by either deleting them from the server (Craft stores its image transforms in folders prefixed by an `_`), or you can use the CLI command:

https://nystudio107.com/docs/image-optimize/using.html#forcing-image-variant-creation

**Comment by brandondeweese** [comment]
When I save the OptimizedImages field and it runs the job on that directory, it should generate new, optimized images, correct?

**Comment by khalwat** [comment]
ImageOptimize uses Craft image transforms under the hood. For a variety of reasons, Craft image transforms _do not_ recreate the image transforms if they already exist on disk.

So either delete them, and re-save, or use the CLI command as noted above.

**Comment by brandondeweese** [comment]
Oh ok thanks. this is helpful. Unfortunately, newly created png versions are slightly larger than the originals crated without OptiPNG. Seen that before?

**Comment by khalwat** [comment]
Yes, it can have to do with the optimization level used in the optipng command, and you might also try other more compressive tools like PngQuant

**Comment by brandondeweese** [comment]
Thanks for your help!
