### ISSUE TITLE
Unable to create new image variant

### ISSUE THREAD

**Issue by dwheeldo** [nystudio107/craft3-imageoptimize#319]
### Describe the bug
Hi,

I'm trying to generate a new image optimize variant for a site with ~10,000 images (I know...), but the 'Optimizing images in S3' queue job keeps failing.

As I know this is a long old job, I've been using the CLI command `php craft image-optimize/optimize/create --field=fieldName`. Despite this, every time I try to run the job it's processing some images (varies from a couple of hundred to a few thousand) and then throwing the following error:

```
[error][craft\queue\QueueLogBehavior::afterError]  [394168] Optimizing images in Images (S3) (attempt: 1, pid: 3246455) - Error (time: 634.905s): Resize operation failed
```

On the next line in the logs I'm also getting another issue:

```
[error][Imagine\Exception\RuntimeException] ImagickException: cache resources exhausted
```

Is there anything you can think of that I can do to fix this? Do I need to allocate more memory or extend the execution time on the server? 

Any help much appreciated!

### To reproduce
Steps to reproduce the behaviour:
1. Run `php craft image-optimize/optimize/create --field=fieldName` on the server
2. After some time, the job will throw the error above

### Expected behaviour
Image variants to be created.

### Versions
- Plugin version: 1.6.38
- Craft version: 3.7.26

**Comment by khalwat** [comment]
Two things I'd try:

1. If it's consistently failing on a particular image (the CLI output should show you which one it's trying to process), it's possible that the image is corrupted. You can try removing that image, and trying again
2. Ensure that the `memory_limit` for the CLI PHP that you're using is set to `0` so it can use as much memory as is needed.

**Comment by dwheeldo** [comment]
Thanks @khalwat. After much head-scratching, I figured out that it was the same cause as https://github.com/nystudio107/craft-imageoptimize/issues/260 - changing the resource policy limits for ImageMagick enabled the queue job to successfully complete.
