### ISSUE TITLE
WEBP files not being created on Windows system

### ISSUE THREAD

**Issue by Christopholus** [nystudio107/craft3-imageoptimize#320]
### Question
Hi there - I'm developing alongside of my other team members (all of which are on Mac OSX) and we're using the ImageOptimize plugin. Despite multiple attempts, I'm unable to get any WEBP images created for transforms on the site, but the plugin works just fine for my other devs!

I should add that we're all running MAMP, though I'm running the Windows version of MAMP which did not come with the CWEBP extension by default. I've since installed CWEBP to a folder and pointed the ImageOptimize plugin to it, and I'm getting green checkmarks across the board. However, when I visit a page (or even run the `php craft image-optimize/optimize/create` command) I am not seeing any new WEBP files being created.

I've done some testing on my CWEBP extension via command line on its own and it's able to convert a PNG or JPG straight to WEBP so I don't think the issue lies there.

Here is a picture of the command line when the command is run:
![emptycommandline](https://user-images.githubusercontent.com/1195612/159080986-9f6d9bdd-9074-452a-88b2-9d34bb2ff204.PNG)

And a shot of the configuration page in the admin panel:
![image](https://user-images.githubusercontent.com/1195612/159080603-2cc412de-605a-4a29-a854-ae52ce085c6f.png)

I've also tried a few other solutions:
- Updating the ImageMagick library
- Installing an alternate version of the CWEBP plugin

Just curious if anyone else has run into similar issues? After a few days of troubleshooting I'm at a bit of a loss about where to look next. Any help would be much appreciated.

Thanks!

**Comment by khalwat** [comment]
I'm going to guess it's because it is an `exe` file, when it might need to be an actual unix binary, installed in WSL? I'm not really sure to be honest, I don't use Windows -- but this is some kind of a local environment setup issue.

**Comment by Fakhri17** [comment]
@khalwat  I have the same problem regarding this issue.

So I have installed the cwebp plugins on windows and installed them in the system environment. And on the CP imageOptimize plugins display it indicates that the cwebp plugins are installed

but when I don't see that the photos I upload don't transform to webp.

How do I fix this?

![image](https://github.com/user-attachments/assets/37f7b358-4ab8-4c2b-90e1-cb1ab4dc609f)

![image](https://github.com/user-attachments/assets/152d8cae-76b5-4b1c-b4f4-ce94745edf3e)

![image](https://github.com/user-attachments/assets/ce474d95-3379-4239-9142-5b67e887d2c6)

Im using
-  "craftcms/cms": "5.1.10",
- "nystudio107/craft-imageoptimize": "5.0.2",
