### ISSUE TITLE
Preserve transparency for WebP when Image Format is set to JPGs

### ISSUE THREAD

**Issue by simonkuran** [nystudio107/craft3-imageoptimize#322]
Is it possible to preserve transparency for WebP when the Image Format option for an ImageOptimize field is set to JPG? I like forcing the image format to be JPG to stop huge PNGs getting used on the front end of the site, but it would be nice if the transparency wasn't stripped out of the WebP version. This would allow images with transparency to be supported, but stop large file size PNGs being sent to the small percentage of browsers that don't support WebP.

**Comment by khalwat** [comment]
How would JPEG files end up there with a transparency channel? I'm not sure I understand?

**Comment by simonkuran** [comment]
If a PNG with transparency is uploaded and the ImageOptimize Image Format option is set to JPG (not auto) the generated JPG **_and_** WebP files don't have transparency.

**Comment by khalwat** [comment]
Ah, I see. Currently that isn't supported, but it's possible we could add support for that in the version of the plugin for Craft 4

**Comment by SanboKyo** [comment]
I run in the same issue – with Craft 4.7.1 and ImageOptimize 4.0.5.

Did you implement this?

**Comment by khalwat** [comment]
Set the format to "Auto" and it should work as expected.
