### ISSUE TITLE
[Craft 4.0]: Error when saving asset from an entry modal

### ISSUE THREAD

**Issue by JeanLucEsser** [nystudio107/craft3-imageoptimize#326]
### Describe the bug
When in an entry and editing an asset via it's modal, if the asset's volume has an OptimizedImage fiel on it, saving any change (or even not making any and saving) from the modal generates an error.

HTTP 400 - Bad request - Unable to verify your data submission.

### To reproduce
Steps to reproduce the behaviour:
1. Go to an entry with an asset field with a OptimizedImage on its volume
2. Double click the asset to open the modal
3. Click save from within the modal

### Versions
- Plugin version: latest dev
- Craft version: latest dev (4.x)

**Comment by khalwat** [comment]
FWIW, I'd suggest using the tagged beta versions of both Craft CMS and also of plugins. The reason is they provide landmarks that allow us to attempt to replicate your issue with the exact same setup.

Also the `dev-` branches may have things checked in that aren't fully baked. So for both Craft and ImageOptimize you can use:

```
^4.0.0-beta.1
```

...as your semver.

I will have a look at this, though!

**Comment by JeanLucEsser** [comment]
Hey Andrew, this is still an issue which totally prevents the use of slide out modals and I can't find a way of getting around it somehow. Have you been able to reproduce the issue by any chance?

It *feels* like a Craft issue, but the issue only arise when adding an OptimizedImage field on an asset volume.

Here's the error log of the web request. Should you need anything else just ping me. Craft 4.0.3 / Plugin 4.0.0-beta.3
```
2022-06-02 12:50:00 [web.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=mariadb-10.5-3306.database.nitro;dbname=generation_opera;port=3306 {"memory":10706528}
2022-06-02 12:50:00 [web.INFO] [yii\web\Session::open] Session started {"memory":15527608}
2022-06-02 12:50:00 [web.INFO] [nystudio107\emptycoalesce\EmptyCoalesce::init] Empty Coalesce plugin loaded {"memory":17765200}
2022-06-02 12:50:00 [web.INFO] [nystudio107\imageoptimize\ImageOptimize::init] ImageOptimize plugin loaded {"memory":23624200}
2022-06-02 12:50:00 [web.INFO] [nystudio107\seomatic\Seomatic::init] SEOmatic plugin loaded {"memory":24873256}
2022-06-02 12:50:00 [web.INFO] [nystudio107\vite\Vite::init] Vite plugin loaded {"memory":24991312}
2022-06-02 12:50:00 [web.ERROR] [yii\web\HttpException:400] yii\web\BadRequestHttpException: Unable to verify your data submission. in /app/vendor/yiisoft/yii2/web/Controller.php:223
Stack trace:
#0 /app/vendor/craftcms/cms/src/web/Controller.php(132): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /app/vendor/craftcms/cms/src/controllers/ElementsController.php(87): craft\web\Controller->beforeAction(Object(yii\base\InlineAction))
#2 /app/vendor/yiisoft/yii2/base/Controller.php(176): craft\controllers\ElementsController->beforeAction(Object(yii\base\InlineAction))
#3 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('edit', Array)
#4 /app/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('elements/edit', Array)
#5 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('elements/edit', Array)
#6 /app/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#7 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /app/web/index.php(12): yii\base\Application->run()
#9 {main} {"memory":32519192,"exception":"[object] (yii\\web\\BadRequestHttpException(code: 0): Unable to verify your data submission. at /app/vendor/yiisoft/yii2/web/Controller.php:223)"}
2022-06-02 12:50:00 [web.INFO] [application] Request context:
$_GET = []

$_POST = [
    'fysviiajhj' => [
        'title' => 'Thibaud Desplantes'
        'alt' => ''
        'fields' => [
            'prefererFormatOriginal' => '1'
        ]
        'elementId' => '860'
        'siteId' => '1'
        'fieldLayoutId' => '9'
        'action' => 'elements/save'
        'newFilename' => 'Thibaud-DesplantesLaurent-Guizard-IMG_6598.jpg'
    ]
]
```

**Comment by khalwat** [comment]
@JeanLucEsser yeah while there are some issues in ImageOptimize for Craft 4 that I need to address, the "Unable to verify your data submission" error seems pretty odd to me, and could very well be a Craft issue.

**Comment by JeanLucEsser** [comment]
Looking a little more into it, opening the slide out throws the following js error in the console. Could it be related?

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/14908712/171636083-32915955-6ad4-472e-86a1-3a5c6a6e4c68.png">

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/bb9b7df9bd5266d08b9690b7b06e49c6011fe25f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.0-beta.4”,
```
Then do a `composer clear-cache && composer update`
