### ISSUE TITLE
[4 beta]. Webp image transforms... missing documentation?

### ISSUE THREAD

**Issue by MattWilcox** [nystudio107/craft3-imageoptimize#328]
There is a missing option for output of webp images in the Transform? cwebp is installed. I expect to be able to output webp variants of all images regardless of the source image format.

I can see a section about Image Variants in the docs https://nystudio107.com/docs/image-optimize/using.html#image-variants but nothing actually tells you how to get webp working as an output format? What have I missed?

<img width="519" alt="Screenshot 2022-04-22 at 10 25 42" src="https://user-images.githubusercontent.com/814039/164678088-3d9654a7-5654-4b85-87d1-fcbee62cced8.png">

<img width="1002" alt="Screenshot 2022-04-22 at 10 27 55" src="https://user-images.githubusercontent.com/814039/164678283-38eb5844-9105-445a-a183-ead2f57f62d4.png">

**Comment by MattWilcox** [comment]
Worked it out, but it's not clear from the docs that if you want webp to work, you need to:

* Copy the config.php file buried deep in the Vendor folder to your own config folder as image-optimize.php
* Add a new activeImageVariantCreator block:

```
'activeImageVariantCreators' => [
        'webp' => [
            'cwebp',
        ],
        'jpg' => [
            'cwebp',
        ],
        'png' => [
            'cwebp',
        ],
        'gif' => [
            'cwebp',
        ],
    ],
```

Possibly an imageProcessor too? I'm unclear - can Craft/Image Optimize use *source webp* files as is? We've had a few instances where clients have copied files from online and ended up uploading webp files to the source volumes.

**Comment by JayBox325** [comment]
I am working with a new Craft 4 install with DDEV and I am having an issue where cwebp isn't installed and there's very little documentation that I have found that helps resolve this issue. When you updated your config, did your server have cwebp installed already?

**Comment by khalwat** [comment]
You'd need to get `cwebp` installed in your DDEV Docker container.

**Comment by jl-digital** [comment]
<img width="1639" alt="image" src="https://github.com/nystudio107/craft-imageoptimize/assets/1391326/ba104152-3c9f-4f76-b8c2-729c1e95b94a">
I have the same problem. cwebp is installed. It doesn't show up in the list of Active Image Processors. 
It does show up under Active Image Variant Creators.

I have added webp to the Active Image Processors array in config/image-optimize.php
`// Active image processors
        'activeImageProcessors'      => [
            'jpg' => [
                'jpegoptim',
            ],
            'png' => [
                'optipng',
            ],
            'svg' => [
                'svgo',
            ],
            'gif' => [
                'gifsicle',
            ],
            'webp' => [
                'webp',
            ],
        ],`

But still doesn't show up in the list in the plugin settings. And not in the Image Format dropdown in de field settings.

How do I get webp to work?

**Comment by khalwat** [comment]
What list are you expecting to see in the plugin settings exactly? Can you provide me with a screenshot of where you expect to see it, and what you expect to see?

**Comment by jl-digital** [comment]
![image](https://github.com/nystudio107/craft-imageoptimize/assets/1391326/d3f8a64e-934c-4afb-92db-93958dc2fa4c)
It's the first image in this thread.
On the bottom of the image you see the dropdown. I expect webp to be in that list.

**Comment by khalwat** [comment]
Ah I see. No, webp will never appear there as an option. Those are the primary image formats generated from the transforms.

It creates the webp images automatically as _variants_ of those images, so that both the jpg and the webp images will be available for each asset.

**Comment by jl-digital** [comment]
Allright, now I understand, thank you!
