### ISSUE TITLE
Cache dynamically created images

### ISSUE THREAD

**Issue by peirix** [nystudio107/craft3-imageoptimize#33]
It would be nice if the plugin would cache images created dynamically in the template, as we usually have a lot of different aspect ratios for images used through-out the site. So it would be really hard to set up image variants for each image type. And it's also quite hard to swallow a 10s load time for a page that has 6 images.

**Comment by khalwat** [comment]
The images will get cached; what will not get cached are the color palette, and SVG placeholder... but you can turn those off via the `config.php`
