### ISSUE TITLE
Testing beta plugin error

### ISSUE THREAD

**Issue by scottgruber** [nystudio107/craft3-imageoptimize#332]
### Question
I'm trying to upgrade Craft CMS 4.0 and running into an error when I attempt to install the beta version of craft-imageoptimize. 

Here is the error message I see after running

`composer require nystudio107/craft-imageoptimize` 

```
Composer output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- nystudio107/craft-imageoptimize 4.0.0-beta.3 requires nystudio107/craft-imageoptimize-imgix ^4.0.0-beta.1 -> found nystudio107/craft-imageoptimize-imgix[4.0.0-beta.1, v4.x-dev] but it does not match your minimum-stability.
- Root composer.json requires nystudio107/craft-imageoptimize 4.0.0-beta.3 -> satisfiable by nystudio107/craft-imageoptimize[4.0.0-beta.3].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
```

This occurs whether I try to install via CLI or the Craft Plugin Installer. 

Do you think the version numbers in composer.json may need to be updated?

### Additional context
This site installation doesn't currently use imgx. 

Thanks for your help to update the NYStudio 107 plugins to support 4.0. 

Please let me know if there is anything I could do to help.

**Comment by khalwat** [comment]
Please add this to your `composer.json`:

```
  "minimum-stability": "dev",
  "prefer-stable": true,

```
