### ISSUE TITLE
[v4.x-dev] - Missing subfolder selections for image optimize field

### ISSUE THREAD

**Issue by twitcher07** [nystudio107/craft3-imageoptimize#333]
### Describe the bug
I created a volume in craft and added an image optimize field to it. However, going back and looking at the settings for the optimize field I do not see the option to select which subfolders to limit the creation of optimized images. Is this still a feature that will be carried over into Craft 4 version of the plugin?

### Screenshots
![image](https://user-images.githubusercontent.com/8517321/169146590-c22bd0f9-46bd-45b0-9e42-8ee1c2b6c6ad.png)

### Versions
- Plugin version: v4.x-dev
- Craft version: 4

**Comment by khalwat** [comment]
Yep, it will be carried over. Changes in the way Craft 4 handles volumes/file systems have apparently broken this currently

**Comment by twitcher07** [comment]
@khalwat ok awesome! I kind of assumed it was related to the asset changes for Craft 4. 

Thank you to you and your team for developing such an awesome plugin!

**Comment by mihob** [comment]
@khalwat Is there any news here? This is quite important feature for us, otherwise tons of unnecessary variations will be created.

**Comment by khalwat** [comment]
I'm hoping to have it sorted out shortly. ImageOptimize for Craft 4 is next up on the list.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/8233ec57fc444d9393a44faf1fce71b0025cc4a3

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.0-beta.4”,
```
Then do a `composer clear-cache && composer update`
