### ISSUE TITLE
SVG Issue with Sharp

### ISSUE THREAD

**Issue by JeanLucEsser** [nystudio107/craft3-imageoptimize#336]
SVG assets are broken in the CP. 
All other image formats are fine. 
Switching to CraftTransforms from SharpTransforms make SVGs work again. 
No errors are logged when the SVG transform is generated.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/14908712/170281738-5f1e21c3-a333-484d-8d16-8cd1fcc41b07.png">

Craft 4.0.3 / Plugin Beta 3

**Comment by khalwat** [comment]
I don't think Serverless Sharp supports SVG images, unfortunately.
