### ISSUE TITLE
Dependency conflict when installing ImageOptimize for Craft 4

### ISSUE THREAD

**Issue by furioursus** [nystudio107/craft3-imageoptimize#338]
### Describe the bug
I have a Craft 4.03 installation where I’m trying to install ImageOptimize, but when I try to do so through the plugin store, I get the following error:

```sh
Composer output: Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- nystudio107/craft-imageoptimize 4.0.0-beta.3 requires nystudio107/craft-imageoptimize-imgix ^4.0.0-beta.1 -> found nystudio107/craft-imageoptimize-imgix[4.0.0-beta.1, v4.x-dev] but it does not match your minimum-stability.
- Root composer.json requires nystudio107/craft-imageoptimize 4.0.0-beta.3 -> satisfiable by nystudio107/craft-imageoptimize[4.0.0-beta.3].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
```

### To reproduce
Steps to reproduce the behaviour:
1. Install Craft 4
2. Update `composer.json` to have `minimum-stability` set to `dev`.
3. Update `composer.json` to have `prefer-stable` set to `true`.
4. Run `composer update`
5. In the Plugin Store, attempt to install/try ImageOptimize.
6. Receive the error.
7. Cry a little bit.

### Expected behaviour
The plugin should have installed.

### Screen Recording
![CleanShot 2022-05-25 at 12 11 46](https://user-images.githubusercontent.com/366427/170349826-0c073621-9dd1-48b1-83b0-d1ccba28f864.gif)

### Versions
- Plugin version: N/A (won’t install from the store)
- Craft version: 4.0.3

### Composer File
```json
{
  "require": {
    "craftcms/cms": "^4.0.0.1",
    "vlucas/phpdotenv": "^5.4.0"
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require-dev": {
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "allow-plugins": {
      "craftcms/plugin-installer": true,
      "yiisoft/yii2-composer": true
    },
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "8.0.2"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}
```

**Comment by khalwat** [comment]
Resolved by updating the dependent packages to `4.0.0` release versions:

https://github.com/nystudio107/craft-imageoptimize-imgix/releases/tag/4.0.0

https://github.com/nystudio107/craft-imageoptimize-sharp/releases/tag/4.0.0

https://github.com/nystudio107/craft-imageoptimize-thumbor/releases/tag/4.0.0

If this doesn't work immediately, it should after packagist, et al resolve the new tags.
