### ISSUE TITLE
Replace Sharp position with extract for added precision

### ISSUE THREAD

**Issue by JeanLucEsser** [nystudio107/craft3-imageoptimize#339]
### Is your feature request related to a problem? Please describe.
Spent a few days migrating an all local assets setup to AWS for a client, including for image transforms.
Had a few minor issues and went back to using CraftTransforms and keeping S3 for now.

But the actual reason we went back is focal point support:
I should have anticipated this, but the way focal point is handled right now in sharp is via resize/position, which is very limited (a combination of top, bottom, left, right, center). The result was not what we and the client expected. (it's not only faces, so AWS Rekognition is not really an option in this context).

### Describe the solution you would like
By looking at sharp, it looks like there's an "easy" fix for this:
Using the cropping feature via extract (https://sharp.pixelplumbing.com/api-resize#extract) in place of position.

That way, with a few maths calculations and logic we can define the region to be cropped with the focal point as the origin. So that we can get some more precise end results when the focal point is set. And make AWS ImageHandler an even more credible option to replace CraftTransforms.

Of course there should be an option to bypass this for a volume that uses AWS Rekognition.

### Describe alternatives you have considered
We went back to using CraftTransforms.
This is far from ideal though as our hosting partner (fortrabbit) does not allow (rightly so) for imageoptim and company.

**Comment by khalwat** [comment]
I've never worked with the extract API in sharp, if you'd be open to doing a PR that meets your needs, I'd be happy to have a look at it though!

I'm not sure I agree with your hosting company not allowing for ImageOptim et al, that type of thing shouldn't be an issue for most hosts.

**Comment by khalwat** [comment]
Ah actually, on second thought, what you're suggesting would require changes to the image transform serverless function itself... so this FR probably should be posted there.

You can also have a look at https://github.com/venveo/serverless-sharp too tho

**Comment by JeanLucEsser** [comment]
> I'm not sure I agree with your hosting company not allowing for ImageOptim et al, that type of thing shouldn't be an issue for most hosts.

Their explanation (https://help.fortrabbit.com/quirks#toc-no-image-optimization-tools) makes *some* sense.

> Ah actually, on second thought, what you're suggesting would require changes to the image transform serverless function itself

Not sure what you mean, looks like SIH uses sharp js so should support all of sharp functionality but I may be wrong (at least it did on version 4 in 2019 according to [this](https://github.com/aws-solutions/serverless-image-handler/issues/150) issue).
I will try to find some time to test this and eventually make a PR if I can get it to work.
```json
"extract": {
  "left": 500,
  "top": 500,
  "width": 100,
  "height": 100
}
```

**Comment by JeanLucEsser** [comment]
Just a memo to reference another post for how to crop around a focal point with sharp.
https://github.com/lovell/sharp/issues/2740#issuecomment-1279560949

And this one from which we should be able to use some code.
https://github.com/lovell/sharp/issues/1198#issuecomment-384591756

Still trying to find some time to test this, will keep you posted if and when I get around it.
