### ISSUE TITLE
Image Optimize Failed

### ISSUE THREAD

**Issue by redkrupp** [nystudio107/craft3-imageoptimize#340]
Just upgraded to Craft 4.0.3.

Reviewed the settings (no changes have been made). Clicked save to trigger the plugin and re-generate images.

![AKypFhL](https://user-images.githubusercontent.com/1551388/170854397-c2fa3fd5-c5dd-4de3-8a0d-1275dc4e0efd.png)

LiteSpeed + PHP 8.1.6

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/3598ec1e50fc3fb377fa4fc23708ce4369830339

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-image-optimize": "dev-develop-v4 as 4.0.0-beta.4”,
```
Then do a `composer clear-cache && composer update`
