### ISSUE TITLE
This is not an image that can be manipulated - 4.0.0-beta3

### ISSUE THREAD

**Issue by cookie10codes** [nystudio107/craft3-imageoptimize#343]
Hi Andrew 👋🏼 

### Describe the bug
Each image we try to upload into our field results in a `This is not an image that can be manipulated`. My image is big enough, so that's not the issue. I can't seem to find any error in the logs. What I do see is this log, which maybe causing this problem?

```
2022-06-01 13:55:32 [web.INFO] [nystudio107\imageoptimize\services\OptimizedImages::shouldCreateVariants] Array
(
)
 {"memory":11876624} 
```

As this issue #334 describes, the `./craft image-optimize/optimize/create` solves the issue but we can't expect the author asking to manually run the command each time they upload an image.

### To reproduce
Steps to reproduce the behaviour:
1. Go to a page
2. Upload an image
3. Double click the image (or check the image optmise field in Assets)
4. Showing the message `This is not an image that can be manipulated`

### Screenshots
<img width="965" alt="Screenshot 2022-06-01 at 15 55 41" src="https://user-images.githubusercontent.com/20947573/171423011-904d46c4-e083-41cb-a093-2eaeca2fdcf4.png">
<img width="1250" alt="Screenshot 2022-06-01 at 15 56 16" src="https://user-images.githubusercontent.com/20947573/171423033-541a2190-0ea7-4524-be6f-adc53d81c027.png">

### Versions
- Plugin version: 4.0.0-beta3
- Craft version: Craft Pro 4.0.3

Thanks for looking into this 👍🏼

**Comment by michtio** [comment]
@khalwat any news on this front? As it's excruciatingly annoying, every time an image uploads to run a console command to make it working.

Makes it unworkable at the moment for our content editors. Thank you for having a look!

**Comment by curtismorte** [comment]
We're experiencing the same issue. 

However, our context is slightly different. We always get the message "This is not an image that can be manipulated" for all optimized images fields associated with a volume when we first upload an asset. However, as our queue is running and completing tasks, those messages then get removed and we see the optimized images themselves.

Note that all of our optimized image fields use `auto` for their image format specification.

We don't use the native poor man's queue with Craft, and instead use a service unit (systemd) to always have processes running that watches the queue (we have 4 of them per server).

**Comment by khalwat** [comment]
I believe this is due to the `auto` setting, which will be addressed shortly. There must have been an underlying change in how image transforms are handled in Craft 4

**Comment by curtismorte** [comment]
@khalwat yeah I noticed a big difference in the code bases for transforms between Craft v3 and Craft v4 when tracking down the issue for #329 .

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/3598ec1e50fc3fb377fa4fc23708ce4369830339

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-image-optimize": "dev-develop-v4 as 4.0.0-beta.4”,
```
Then do a `composer clear-cache && composer update`
