### ISSUE TITLE
Cannot assign null to property nystudio107\imageoptimize\models\OptimizedImage::$lightness of type int

### ISSUE THREAD

**Issue by ZapaNOR** [nystudio107/craft3-imageoptimize#345]
When generating transform the queue job fails, giving the error:
Cannot assign null to property nystudio107\imageoptimize\models\OptimizedImage::$lightness of type int

Additionally, I get no output in the terminal if I try to generate transforms there, so I cant narrow down the actual image throwing the error. It failed on 35% this time, so I suspect there are some images throwing this error, not all.

SVG and GIF optimizers are not activated, I generate webp with cwebp locally, have been working fine until the craft 4 upgrade.

### Versions
- Plugin version: 4.0.0-beta.3
- Craft version: 4.0.4

**Comment by khalwat** [comment]
Should be an easy fix, thank you

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/3ac976f6f0b530f797569f94c386d74d894036d3

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.0-beta.4”,
```
Then do a `composer clear-cache && composer update`
