### ISSUE TITLE
Uncaught TypeError: $(...).ImageOptimizeOptimizedImages is not a function

### ISSUE THREAD

**Issue by jl-digital** [nystudio107/craft3-imageoptimize#346]
### Describe the bug
When opening the slideout in the CP through clicking on an image, this JS error is thrown:
```
Uncaught TypeError: $(...).ImageOptimizeOptimizedImages is not a function
at <anonymous>:3:52
at m (jquery.js?v=1654698802:2:867)
at Pe (jquery.js?v=1654698802:2:48866)
at w.fn.init.append (jquery.js?v=1654698802:2:50070)
at Object.appendBodyHtml (Craft.js:1826:18)
at CpScreenSlideout.js:329:17
```

### To reproduce
Steps to reproduce the behaviour:
1. Have an asset field in an entry that uploads to a volume with an OptimizedImages field 
2. Open the entry and click the name of the asset so the side panel will slideout
3. The web console will throw the above error and you cannot enter an image caption for example, it will not be saved.

### Expected behaviour
No error and be able to add a caption to an image.

### Versions
- Plugin version: 4.0.0-beta.3
- Craft version: Craft Pro 4.0.4

**Comment by michtio** [comment]
Same as #344 ( for reference @khalwat )

**Comment by khalwat** [comment]
Yep, same issue.
