### ISSUE TITLE
PDF (asset) .url gives preview instead of the url of the pdf

### ISSUE THREAD

**Issue by limesquare-nl** [nystudio107/craft3-imageoptimize#349]
### Describe the bug
In 1.6.46 and 1.6.45 there is a problem with the asset.url for pdf's. It gives the link to a transformation of the pdf (preview first page) instead of the link to the pdf. Downgrade to 1.6.44 fixes the issue.

### To reproduce
In a template output asset.url for a pdf

### Expected behaviour
Url to download the pdf

### Versions
- Plugin version: 1.6.46 and 1.6.45
- Craft version: 3.7.46

**Comment by khalwat** [comment]
I'm pretty sure I know what this is, will have a fix shortly.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/9ffbb99978340af610f29cce8e94c3b9a681451b & https://github.com/nystudio107/craft-imageoptimize/commit/f257b53accdc0ad34157bf1df416f3d0f0124b68


Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.47”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.1”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Let me know if this addresses it for you, and I will cut a release

**Comment by limesquare-nl** [comment]
It works again. Thanks for getting it resolved so quickly
