### ISSUE TITLE
Image variant console command doesn't work without asset volume handle

### ISSUE THREAD

**Issue by simonkuran** [nystudio107/craft3-imageoptimize#350]
### Describe the bug
`php craft image-optimize/optimize/create` doesn't do anything for me like the docs suggest it would. It just outputs "Creating optimized image variants" and stops. I have to run `php craft image-optimize/optimize/create myVolumeHandle` for each of my volumes to generate images.

### To reproduce
Run `php craft image-optimize/optimize/create`

### Expected behaviour
All asset volumes with an ImageOptimize field get their variants generated.

### Versions
- Plugin version: 4.0.2
- Craft version: 4.2.0.2

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/50d30d34e9c8e9c7cc1481b1508f50358bf5ec6f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.3”,
```
Then do a `composer clear-cache && composer update`
