### ISSUE TITLE
'Numerical argument out of domain' Error when transforming images

### ISSUE THREAD

**Issue by brandondeweese** [nystudio107/craft3-imageoptimize#351]
Simply trying to optimize images on server.
Full error here:

`php: unable to extent pixel cache Numerical argument out of domain @ fatal/cache.c/CacheSignalHandler/3624.`

Using default settings. Never seen this issue before.
<img width="1631" alt="Screen Shot 2022-08-11 at 8 02 18 AM" src="https://user-images.githubusercontent.com/18017918/184165229-7c1df848-92f5-43e6-85e9-4cfbec882095.png">

**Comment by khalwat** [comment]
This looks like an Imagick error -- probably this is some kind of server setup issue, not directly related to ImageOptimize.

Can you provide the full stack trace from the error? It should be in your `storage/logs/web.log`

**Comment by brandondeweese** [comment]
yea. I deleted the web.log to get a fresh log. Tried again and nothing is sent to the log. Yea, I don't know.

**Comment by khalwat** [comment]
Either you are running out of disk space or memory, or something is incorrect with your Imagick install: 

https://github.com/ImageMagick/ImageMagick/issues/1822

**Comment by brandondeweese** [comment]
Thanks.
