### ISSUE TITLE
Silhouette is not being generated for images

### ISSUE THREAD

**Issue by nkpindolia** [nystudio107/craft3-imageoptimize#352]
### Describe the bug
Silhouette is not being generated for images. I have tried to regenerate sizes by `php craft image-optimize/optimize/create` with no change. 

i've tried with the following images: 
[image 1](https://www.pexels.com/photo/tool-set-on-plank-175039/)
[image 2](https://unsplash.com/photos/NMrUtSA7094)

### To reproduce
Steps to reproduce the behaviour:
1. Add the linked image to assets(mine are on s3)
2. use `.placeholderSilhouette()` according to [the docs](https://nystudio107.com/docs/image-optimize/using.html#placeholder-images)
3. no silhouette generated

### Expected behaviour
A silhouette to be generated for the asset.

### Versions
- Plugin version: 4.0.2
- Craft version: 4.2.1.1

**Comment by nkpindolia** [comment]
after a bit more testing it seems that the images are too complicated(too much info in the image, not sure how else to put it). I tried a few "simpler" images and it seemed to work.

[Image 1](https://unsplash.com/photos/4sZmaAzPq8M)
[Image 2](https://unsplash.com/photos/IClZBVw5W5A)

**Comment by khalwat** [comment]
Yeah unfortunately there isn't anything I can do about this; it's using a third-party library to do the silhouette

**Comment by khalwat** [comment]
On second thought, there is a cutoff in the code that I put in to ensure that silhouette images are not overly large. The point of using the placeholders is to ensure that the page loads quickly, without too much data being transmitted.

If the silhouette placeholders are too large, they lose their usefulness. So while I could probably bump up that size limit, and it might fix your problem, perhaps a better idea is to fall back on the lower-resolution placeholder images in those cases.

ref: https://github.com/nystudio107/craft-imageoptimize/blob/develop/src/services/Placeholder.php#L43
