### ISSUE TITLE
Issue with AsyncQueue plugin

### ISSUE THREAD

**Issue by peterurban** [nystudio107/craft3-imageoptimize#354]
### Describe the bug
I am experiencing a problem with this plugin and the AsyncQueue plugin. When adding new assets AsyncQueue seems to start an endless loop of **Generating pending image transforms** tasks which seems to prevent new assets from having responsive sizes generated by this plugin. 

We are just getting a _"This is not an image that can be manipulated"_ on all new assets and all assets that are resaved – even if the latter had optimized image variants generated before.

The job data for these endless loops are simply:
`{
    "description": null
}`

Apologies if this issue is only related to AsyncQueue, but it seems to run all other tasks without issues.

### Versions
- ImageOptimize version:  4.0.2
- AsyncQueue version: 3.0.0
- Craft version: 4.2.3

**Comment by khalwat** [comment]
What happens if you uninstall the Async Queue plugin?

**Comment by peterurban** [comment]
This issue is resolved, but I then have to regenerate all the optimized images.

**Comment by khalwat** [comment]
If it works without the Async Queue plugin, I'm going to have to guess that this is an issue with that plugin. ImageOptimize doesn't do anything special, it just pushes jobs into the queue.

My only other guess is some settings for the Async Queue plugin not what they should be. More on queues here:

https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms
