### ISSUE TITLE
Naming convention using servd.host?

### ISSUE THREAD

**Issue by J-Protz** [nystudio107/craft3-imageoptimize#355]
### Question
So i've come across a tough issue to solve. I have a page created to compare fabrics and colors, and the images are high-resolution. It's built using svelte and using naming conventions for the images (to make life easier for the client). 

So for example an image filename might be `my-site/img/color-xxxx-fabric-xxxx.jpg`

These images have image optimize field attached to them, so there are optimized versions, however because I'm not querying the assets, getting that url is giving me trouble. I noticed each image seems to have a unique hash attached to it. Is there a way to dynamically pull in optimized images via just using a url pattern? This would be huge for this page as each image can be up to 1MB or so. I would like to just set quality to auto and set the width, and maybe serve .webp if the client supports.

Please let me know if there is any other context i can provide to help, or if this is just impossible.

**Comment by khalwat** [comment]
So the easiest way to do this is query the asset itself, and get the data returned from the OptimizedImages field in the query result; it will have all of the optimized image URLs listed in there.

**Comment by J-Protz** [comment]
was hoping to not have to do a query for each asset, since we were using naming conventions and it'd be more performant. but if thats how it needs to be done, then ill go that route.

**Comment by khalwat** [comment]
The naming conventions that are used are actually coming from Craft, it's what is generating those asset names for transforms. So it'd be the same if you used the built-in Asset transforms.
