### ISSUE TITLE
Generate transforms with auto height

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft3-imageoptimize#358]
### Question
We would like to generate the exact craft transforms on upload. But when we check the transforms of the plugin it is not exactly the same as Craft would do. f.e. the height is fixed. How can we generate transforms in the exact folder like Craft would do?

Craft transform:
<img width="329" alt="Screenshot 2022-10-19 at 10 49 36" src="https://user-images.githubusercontent.com/5981440/196644077-ea1b02ed-aed5-419b-ab2d-3a512bc451c9.png">

Plugin transform:
<img width="279" alt="Screenshot 2022-10-19 at 10 49 14" src="https://user-images.githubusercontent.com/5981440/196644130-9b63805c-f1f0-4a7f-8c41-d8b186e5a4a1.png">

### Additional context
We use the graphql api and it gives timeouts when the images are not yet transformed. That's why we want transforms generated on upload instead of on render.

**Comment by khalwat** [comment]
In the Optimized Images field settings, you'd turn off the "Enforce Aspect Ratio" setting.

<img width="1078" alt="Screen Shot 2022-10-19 at 2 56 26 PM" src="https://user-images.githubusercontent.com/7570798/196780081-2959ef0c-0ec8-48f5-8a07-227bb4bdbca9.png">

**Comment by ghost** [comment]
This is not working as it sets a height. To fully match Craft transforms you should do the following things to your plugin (I cant open a PR for this)
- Replace line interlacing with 'none'
- Replace the transform height with null if aspect ratio is not used
- Move webp image to a subfolder with the id of the image

```
if ($useAspectRatio) {
    $transform->height = (int)($width / $aspectRatio);
} else {
    $transform->height = null;
}
```

**Comment by khalwat** [comment]
Currently it does this:

```php
        $useAspectRatio = $variant['useAspectRatio'] ?? false;
        if ($useAspectRatio) {
            $aspectRatio = (float)$variant['aspectRatioX'] / (float)$variant['aspectRatioY'];
        } else {
            $aspectRatio = (float)$asset->width / (float)$asset->height;
        }
```
So if you have "Enforce Aspect Ratio" turned off, it calculates what the AR should be based on the actual height and width of the image.

So you will end up with a height that is correct for the given width.
