### ISSUE TITLE
imgix API

### ISSUE THREAD

**Issue by E2design** [nystudio107/craft3-imageoptimize#36]
Probably a stupid question but I noticed the addition of 'Imgix API Key' question in the Imageoptimize settings when choosing for 'transform method imgix'.

From where do I get the API key? The source details in my IMGIX dashboard don't show such an API key.

**Comment by khalwat** [comment]
The Imgix docs say:

find your API KEY @ https://dashboard.imgix.com/accounts

If you log in, and click on the little user icon in the upper-right corner of the screen, then click on Accounts, you'll see this:

<img width="675" alt="google chromescreensnapz047" src="https://user-images.githubusercontent.com/7570798/35184990-d0db8c9c-fdca-11e7-9708-5d42e17325b0.png">
