### ISSUE TITLE
Plugin doesn't work with selected Transform Method: Sharp

### ISSUE THREAD

**Issue by sword3d** [nystudio107/craft3-imageoptimize#363]
### Describe the bug
The problem appeared when upgrading from Craft 3 to Craft 4

### To reproduce
Steps to reproduce the behaviour:
1. If I select in Transform Method: Craf  - https://prnt.sc/EucgiTlJdbtv
2. If I select in Transform Method: Sharp - https://prnt.sc/nIxlX5bGhvBV
3. My code - https://prnt.sc/SkYk_DeOT8iw 

### Expected behaviour
Need to restore the work of Transform

### Screenshots
https://prnt.sc/EucgiTlJdbtv
https://prnt.sc/nIxlX5bGhvBV
https://prnt.sc/SkYk_DeOT8iw

### Versions
- Plugin version: 4.0.2
- Craft version: 4.3.1

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/03e74e66dd743db532b278e1146daafb1fa06a86

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.3”,
```
Then do a `composer clear-cache && composer update`

**Comment by sword3d** [comment]
Works.
Thank you!
