### ISSUE TITLE
PDFs causing failed queues

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [nystudio107/craft3-imageoptimize#364]
It appears that I/O is trying to optimize PDFs and when those fail/error-out the other optimizations don't run. I'm showing multiple failed "Optimizing images in X...."

Is there a way to skip PDFs? I know you added the Ignore SVGs/Gif option. Can we add PDFs to that as well? This would be handy as a global option in `config/image-optimize.php` or in the field settings.

### Screenshots

![Screenshot 2022-12-16 at 11 26 14 AM](https://user-images.githubusercontent.com/39201467/208171050-256f3c82-39bb-46f0-9109-2fd7b99cc80f.png)
![Screenshot 2022-12-16 at 11 54 17 AM](https://user-images.githubusercontent.com/39201467/208171053-b09e09bf-112e-48ed-96e4-ae78eece9d45.png)

### Versions
- Plugin version: ImageOptimize 4.0.3
- Craft version: Craft CMS 4.3.5

Thanks for the help!

# Additional Info

I just got this reply back from Matt @ Servd and I'm not sure if this helps:

_Hey Mark. It looks like image magick bailed when attempting to create a placeholder image. It doesn't specify why exactly, just that it hit a Runtime Error._

_I've seen that before with PNG files that have been optimised previously. ImageMagick has a bug where it explodes when it tries to process them._

_It seems to be the first image in the open graph images volume that it got upset about but I'm not 100% sure what order ImageOptimize processes them in._

**Comment by DynamiteGoesBoom** [comment]
Any updates or thoughts on this @khalwat? is skipping the PDFs an option that you could write in?

Thanks again!

**Comment by khalwat** [comment]
Yes, I think adding an option to allow PDFs to be ignored is a good way forward, for setups where PDFs are not rendering properly due to Imagick failing as shown in your stack trace.

Probably it is running out of memory, due to complex or larger PDFs

**Comment by DynamiteGoesBoom** [comment]
@khalwat awesome and thanks! Yeah we're not really running into these issues on production as that's a much beefier server. But it would still be nice to be able to skip PDFs from being optimized.

I appreciate the response and will look for an update whenever you get to it.

Happy Holidays Andrew and thanks again!

I was certain that this would work:

```
{% set availableAt = craft.entries()
    .section('parkReservations')
    .relatedTo({
        targetElement: entry,
        field: 'availableAt.parkFieldSelect'
    })
.all() %}
```

**Comment by soulseekah** [comment]
This snippet lets you pick whether an optimize job gets queued or not depending on the extension. Works well for us.

```php
Craft::$app->getQueue()->on(
    Queue::EVENT_BEFORE_PUSH,
    function(PushEvent $event): void {
        if (ResaveOptimizedImages::class !== $event->job::class) {
            return; // Do not intervene. Not the optimize job.
        }

        $asset = Asset::findOne($event->job->criteria);

        $unskippableExtensions = [
            'jpg', 'jpeg', 'png', 'bmp', 'gif', 'webp',
        ];

        if (in_array($asset->getExtension(), $unskippableExtensions, true)) {
            return; // All good. Let it through.
        }

        $event->handled = true; // Short-circuit to skip.
    }
);
```

**Comment by khalwat** [comment]
Addressed via the above commits.
