### ISSUE TITLE
Sharp transformer works not correctly with native setTransform 

### ISSUE THREAD

**Issue by umkasanki** [nystudio107/craft3-imageoptimize#365]
### 

Works correct:
```
{% set transform = transform ?? {
    width: 300,
    height: 300
} %}
{{ tag('img', {
    src: asset.getUrl(transform),
    srcset: asset.getSrcset(['1.5x', '2x', '3x'], transform),
}) }}
```
![изображение](https://user-images.githubusercontent.com/496132/210209033-d70281fc-0cc2-46da-8190-2c792c5ca00c.png)

Works incorrect:
```
{% do asset.setTransform({ width: 300, height: 300 }) %}
{{ tag('img', {
    src: asset.url,
    width: asset.width,
    height: asset.height,
    srcset: asset.getSrcset(['1.5x', '2x', '3x']),
    alt: asset.title,
}) }}
```
see src param:
![изображение](https://user-images.githubusercontent.com/496132/210209354-57f2eb8b-d442-45ea-91ff-47f4d9822cf2.png)

### To reproduce
Steps to reproduce the behaviour:
1. Set Sharp as Transform Method
2. Define template transforms using [native Craft tags](https://craftcms.com/docs/3.x/image-transforms.html#generating-srcset-sizes)
3. See value of src param

### Expected behaviour
Src should be transformed using serverless image hangler [like srcset]

### Screenshots
See above

### Versions
- Plugin version: 4.0.3
- Craft version: 4.3.5

**Comment by khalwat** [comment]
`src` won't be transformed, because ImageOptimize only kicks in when an image transform takes place. When you do `asset.url` it's just going to return the URL to the untransformed image.
