### ISSUE TITLE
Trouble Using ImageOptimize with S3 Bucket on Craft 4

### ISSUE THREAD

**Issue by NicolasBarse** [nystudio107/craft3-imageoptimize#369]
Since my assets are piling up I decided to switch from local assets to a S3 bucket with CloudFront CDN, however I'm not sure how ImageOptimize is supposed to work in this context. I'm mainly using it for webp versions and downscaled images with the attribute srcset.

The upload on S3 and display with CloudFront works just fine from the CP but ImageOptimize doesn't seem to be generating any variants, either locally or in the bucket. Since I have a lot of assets I'm only testing this on a folder with approx 100 images that don't need any downscaling, but no webp nor silhouette / placeholder are being generated after either saving the asset or the imageoptimize fields.

Is there any documentation on how to use ImageOptimize with S3? Are variants supposed to be saved and uploaded automatically in the bucket? I think I'm failing to see the big picture here or I may have a bad S3 configuation.

Thanks!

**Comment by khalwat** [comment]
Is it possible that you need to resave the assets via the CLI command?

https://nystudio107.com/docs/image-optimize/using.html#command-line-optimized-image-variant-creation

**Comment by khalwat** [comment]
You don't mention the version of Craft or the version of ImageOptimize... but also if you're using Craft 4, is it possible that you have the image transforms set to save to a different volume?

**Comment by NicolasBarse** [comment]
> You don't mention the version of Craft or the version of ImageOptimize... but also if you're using Craft 4, is it possible that you have the image transforms set to save to a different volume?

I had set the transform volume to something local because I had performance issues but now that I changed it back to the filesystem path it worked just fine. Thanks a lot!
