### ISSUE TITLE
All the variants can be deleted.

### ISSUE THREAD

**Issue by spAnser** [nystudio107/craft3-imageoptimize#37]
It is possible to remove all variants which then makes it not possible to re-add a variant once all the variants have been deleted.

In the dropdown to delete variants the last variant shows the delete grayed out but it still functions.

Reloading the field after saving it with no variants will repopulate it will all the default variants.

**Comment by khalwat** [comment]
I thought disabling it would be enough! Apparently not :)

**Comment by khalwat** [comment]
Fixed in 1.4.10:

https://github.com/nystudio107/craft3-imageoptimize/releases/tag/1.4.10
