### ISSUE TITLE
Long pending Image transform queue (ImageMagick out of resources?)

### ISSUE THREAD

**Issue by hhentschel** [nystudio107/craft3-imageoptimize#370]
From time to time if the customer uploads several images, 5-10 at one time, for a gallery e.g. (some are quite big n 10mb), 
the transformation of the images takes quite a long time and seems to get stuck.
 
After some time, the queue is cleared, but the images are not displayed on the frontend and if i have a look
in the backend and click on the image, there are no image transforms being generated.

i looked up the queue.log and found some errors, but don't know exactly what they mean.
`[object] (ImagickException(code: 425): Insufficient memory (case 4) ... @ error/jpeg.c/JPEGErrorHandler/348` 

`{"memory":3437648,"exception":"[object] (craft\\errors\\ImageException(code: 425): Failed to save the image.`

`2023-02-20 14:03:19 [queue.ERROR] [yii\base\ErrorException:1] yii\base\ErrorException: Out of memory (allocated 6291456) (tried to allocate 528384 bytes)`

What does this exactly mean? 
- Images are too big? (should be no more than 5mb, for example?)
- is ImageMagick running out of resources. [See this post](https://github.com/nystudio107/craft-imageoptimize/issues/260)

Also, if I resave the image optimize field, the re-transformation of the images takes 5-10 minutes.
Is this normal, or do we have a slow hosting environment?

i read through different github issues, increased the max_execution_time, 
tried it with the transform via the CLI, but this did not change anything.  

Thanks for helping out here! 

Craft CMS | 4.3.9
PHP version | 8.1.15
Image driver & version | Imagick 3.7.0 (ImageMagick 7.1.0-57)
ImageOptimize | 4.0.4

max_execution_time | 108000
memory_limit | 256M

**Comment by khalwat** [comment]
ImageOptimize just uses regular Craft transforms to do the image resizing, so if these images were used in a Craft transform, you'd see the same error.

It sounds like the images are fairly large, and thus Imagick is running out of memory.

This can be addressed with a policy file:

https://imagemagick.org/script/security-policy.php

Example here:

https://twitter.com/nystudio107/status/1363124167764238337

**Comment by hhentschel** [comment]
Thanks a lot for the info!

Images are between 5 - 12 mb. There are cases, where the customer uploads 10 images for a gallery and then saves the entry. 
So we should then encourage our customer to use smaller images?
As they are not technically experienced at all and it was very convenient just to use the images they get. 

i did convert -list resource and it looks like the server has enough memory:
Resource limits:
  Width: 461.169PP
  Height: 461.169PP
  Area: 411.971GP
  List length: unlimited
  Memory: 191.839GiB
  Map: 383.678GiB
  Disk: unlimited
  File: 45000
  Thread: 1
  Throttle: 0
  Time: unlimited

**Comment by khalwat** [comment]
Yes, the server has enough memory, but that policy.xml file I mentioned above _limits_ the amount of memory that Imagick can use. You will need to adjust it.
