### ISSUE TITLE
Optimizing image tasks throws error: "fclose(): supplied resource is not a valid stream resource". 

### ISSUE THREAD

**Issue by RobinWithouck** [nystudio107/craft3-imageoptimize#371]
The Optimizing image tasks throws an error: "fclose(): supplied resource is not a valid stream resource". 
Our file system is of type "Google Cloud Storage". 
We think it started after the update to Craft 4.4. We changed the filesystem to local to test and this works.

### Screenshots
 
![Screenshot 2023-03-13 at 16 43 41](https://user-images.githubusercontent.com/6160509/224753173-32c07fca-dee7-4287-ba27-e5656612d455.png)

### Versions
- Plugin version: 4.0.4
- Craft version: 4.4.1

**Comment by khalwat** [comment]
ImageOptimize just uses regular Craft transforms -- so this is likely to be some kind of an issue with Craft itself, or the Google Cloud Storage plugin.

Feel free to link this issue to one you create for the Google Cloud Storage plugin or Craft CMS, and I'll help out if I can. 

But this is unlikely to be related to ImageOptimize itself.

**Comment by DynamiteGoesBoom** [comment]
Getting the same issue with Azure Blob Storage too @khalwat. I can setup another GitHub issue if needed but the error message is the same as the original issue.

**Comment by RobinWithouck** [comment]
I filled an issue on the Github page from Craft and they fixed the fclose issue in the 4.4.3 update. So you can try it with the update?

[https://github.com/craftcms/cms/issues/12878](url)

**Comment by DynamiteGoesBoom** [comment]
Awesome @RobinWithouck trying now...

Looks like that corrected it 🤘

**Comment by khalwat** [comment]
Glad it was sorted.
