### ISSUE TITLE
Failed Install for Craft 3

### ISSUE THREAD

**Issue by matthaltuch** [nystudio107/craft3-imageoptimize#374]
### Question
Im trying to install this plugin in a Craft env running Craft 3.5, when trying to install it looks like the plugin is requiring Craft v4 but the documentation states that it should be available for v3.0 and 4 - Is there a specific version that works with Craft 3 or is there a way to use this plugin on a Craft 3 site without the need to upgrade to Craft 4?

### Additional context
When running : composer require nystudio107/craft-imageoptimize

the terminal output is 
Problem 1
    - nystudio107/craft-imageoptimize[4.0.0, ..., v4.x-dev] require craftcms/cms ^4.0.0 -> found craftcms/cms[4.0.0-alpha.1, ..., 4.5.x-dev] but it conflicts with your root composer.json require (^3.5.3).
    - nystudio107/craft-imageoptimize[4.0.0-beta.1, ..., 4.0.0-beta.3] require craftcms/cms ^4.0.0-beta.4 -> found craftcms/cms[4.0.0-beta.4, ..., 4.5.x-dev] but it conflicts with your root composer.json require (^3.5.3).
    - Root composer.json requires nystudio107/craft-imageoptimize ^4.0 -> satisfiable by nystudio107/craft-imageoptimize[4.0.0-beta.1, ..., v4.x-dev].
    Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by khalwat** [comment]
> - Root composer.json requires nystudio107/craft-imageoptimize ^4.0 -> satisfiable by nystudio107/craft-imageoptimize[4.0.0-beta.1, ..., v4.x-dev].

Change the semver in your `composer.json` to look like this:

```json
    "nystudio107/craft-imageoptimize": "^1.0.0",
```
