### ISSUE TITLE
Delete all generated transforms

### ISSUE THREAD

**Issue by luke-nehemedia** [nystudio107/craft3-imageoptimize#375]
### Question
Is there a way to delete all generated transforms? I recently made a lot of changes to a clients side. In this process, I limited some of the imageOptimize fields to specific folders, removed transformations etc. However, I still can see all the generated transforms from earlier versions of the site, taking up a lot of unnecessary space on the server.

I tried using `Utility > Caches > Clear Caches`, but the files are still there. I also removed the imageOptimize-fields all together, but the files are still there. Is there any way to get rid of them? Or possibly even delete all of them?

**Comment by khalwat** [comment]
They are just regular Craft transforms, so you can delete them the same way, which is to delete any directories in the asset volume that being with an `_`
