### ISSUE TITLE
Is it possible to rescan all assets?

### ISSUE THREAD

**Issue by jashiacopper** [nystudio107/craft3-imageoptimize#377]
### Question
Hello, I'm seeing a lot of broken images throughout our assets on the webp transforms. When I download and resave the assets, the webp appears. Is there a way to rescan the entire catalog?

### Additional context

![Screenshot 2023-04-19 at 9 54 50 AM](https://user-images.githubusercontent.com/53240156/233146323-58d0d0f4-ca20-4ae5-8593-a6e5689963b9.png)

**Comment by farmbureau** [comment]
I'm having a similar issue when client moves directories around. I have to resave each entry.

**Comment by petenice** [comment]
I'm having a similar issue when client renames or nests directories. All thumbnails break. I can fix by resaving each entry in assets. A challenge when they move a directory with hundreds of images.

**Comment by BAM-Dennis** [comment]
should be doable via:
`craft image-optimize/optimize/create --force`

**Comment by khalwat** [comment]
Yep, using the CLI command `craft image-optimize/optimize/create --force` will do it for you.
