### ISSUE TITLE
Purchased license key but still seeing the "ImageOptimize requires purchase." banner

### ISSUE THREAD

**Issue by matthaltuch** [nystudio107/craft3-imageoptimize#382]
### Describe the bug

I have a client that has the NYS ImageOptimize plugin installed, they have purchased the license key from the craft console - they have provided proof of payment but the licensing banner is still showing up on the Craft Admin CP.

The order was placed on 5/19/2023 but when I look at the invoice where it says License Key there appears to be a partial key (only 4 digits/number) and not a full key as show in the Craft CP for the IO plugin. There is also no domain listed on the Craft Console invoice (not sure if that may also be an issue)

I'm guessing that the problem is a discrepancy in the keys but im not sure how to resolve this and make sure that the correct plugin license is registered.

**Comment by khalwat** [comment]
This is something you'd need to contact Pixel & Tonic, the people who run the Craft Plugin Store about. I don't have access to any information that could help you, unfortunately.

You can contact them at support@CraftCMS.com

**Comment by matthaltuch** [comment]
Sounds good, Thank you
