### ISSUE TITLE
DivisionByZeroError

### ISSUE THREAD

**Issue by alexagui** [nystudio107/craft3-imageoptimize#383]
### Describe the bug
We're getting a division by zero error on Craft 4 Commerce site that's under development.

### To reproduce
When we attempt to view a product detail on the frontend or visit products index in the admin.

### Screenshots
![divisionbyzero](https://github.com/nystudio107/craft-imageoptimize/assets/685/a1af1569-c810-4997-9376-013f54bae8aa)

### Versions
PHP 8.2.3
MariaDB 10.6.12
Imagick 3.7.0 (ImageMagick 6.9.11-60)

Craft  4.4.11
Commerce 4.2.8
ImageOptimize 4.0.5
SEOmatic 4.0.25

**Comment by khalwat** [comment]
Looks like you have an asset in there that has no width at all. I can add some guards to avoid the error, but still probably an asset in there is corrupted or the like

**Comment by alexagui** [comment]
Thanks Andrew! Yes it seems this was an issue on our end. Closing this one out.

**Comment by mikewink** [comment]
I had the same problem twice with .avif files in Craft CMS right now. If one of them was in a folder, the preview image generation stopped with an error 500. Once the file was gone, everything worked fine again.

**Comment by khalwat** [comment]
@mikewink what transform method are you using?

**Comment by mikewink** [comment]
> @mikewink what transform method are you using?

From the configuration file, I have it is the "CraftImageTransform.class", if that is what you mean.

**Comment by khalwat** [comment]
Addressed in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.57”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.11”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v5 as 5.0.4”,
```
Then do a `composer clear-cache && composer update`
