### ISSUE TITLE
ImageOptimize does not return an absolute URL of image transforms

### ISSUE THREAD

**Issue by stefanprosch** [nystudio107/craft3-imageoptimize#387]
Optimized image variants are not displayed and have a relative URL. If the image is resaved again, in most cases absolute URLs to the optimized image variants are created and thumbnails are visible.

Steps to reproduce the behaviour:
1. Go to assets or upload an image on an entry page.
2. Images are being optimized and saved correctly to the correct path.
3. During the process optimized images are sometimes visible.
4. On optimizing process end image variants are not displayed, hover over the images shows, that the url is relative, e.g. 'uploads/images/_800x1203_crop_center-center_line/assetname.jpg?mtime=1688584317'
5. Opening the image over asset manager and resave results in most case solves the problem. Sometimes not. 

Locally it works fine, but on live environment not. Initially I thought it has something to do in combination with the Blitz Plugin, but it seems I was wrong. See https://github.com/putyourlightson/craft-blitz/issues/528

https://github.com/nystudio107/craft-imageoptimize/assets/26538087/c021adf0-4a23-4490-be80-54249abe0d14

I am using
Craft Solo 3.8.14
Blitz 3.12.9
ImageOptimize 1.6.50

**Comment by khalwat** [comment]
If it all works fine locally, but not live... that sounds to me like some kind of a devops/environment issue?

Maybe you have a relative URL for your Assets or Sites?

**Comment by stefanprosch** [comment]
Thank you for your reply. I was able to solve the problem due to craft 3 to craft 4 migration.
