### ISSUE TITLE
When is a queue job triggered, and how can trigger queue jobs without server access? (Craft 3 -> Craft 4 context)

### ISSUE THREAD

**Issue by abigailjxn** [nystudio107/craft3-imageoptimize#388]
### Question
Hello! I was wondering two things:

1. What actually triggers a queue job for image transforms?
2. Is there a recommendation on how to run `php craft image-optimize/optimize/create myVolumeHandle` if you don't have server access?

I observe that transforms trigger when you save an asset, but I recently upgraded a site from Craft 3 to Craft 4, and it created a queue that got up to 300,000+ jobs (when there are only about 1,000 assets) and the jobs kept going up.  It seemed caught in a loop of creating new jobs. 

I cancelled the queue jobs and am now trying to trigger the queue one volume at a time. However, I am a bit limited in my ability to test this since I do not have server access and have to put in a support ticket to try to run any console commands. I have created a support ticket to do so, but I was just wondering if there was any kind of utility I am missing or a recommendation this kind of scenario? I've been able to hack generating some transforms by running the "update asset indexes" util, but not sure if that's the best way to force the transform generations.

### Additional context
I have my hands tied a bit with how everything is set up. We have a larger client that owns and runs their own servers, which I don't have direct access to. In order to run any console commands on staging or prod, the only way to do so is through a support ticket with their IT team. 

I can't run the transforms locally to test since everything is tied up in AWS permissions, and though I have the proper credentials, they are using ECS and IAM and roles, so I get 403 errors when trying to view the assets/transforms locally.

I know this is a weird situation, so if there's nothing really to be done, I understand. Just wondering if I'm missing something.

### Settings
Craft version: Craft Pro `4.4.15`
ImageOptimize: `4.0.5`

PHP things that might be relevant
`max_execution_time = 120`
`memory_limit = 256M`

**Comment by abigailjxn** [comment]
Update: I was able to get IT to run `php craft image-optimize/optimize/create`, which oddly created 15 queued jobs, even though there are only two volumes to transform. Is this expected behavior?
<img width="1337" alt="CleanShot 2023-07-13 at 13 10 13@2x" src="https://github.com/nystudio107/craft-imageoptimize/assets/41799687/fb48c667-1bbc-4109-83a7-68a948c6b887">

**Comment by khalwat** [comment]
Well, it shouldn't harm anything. If the images already exist, the optimization jobs will just return relatively quickly.

I'm not sure what could have caused all of those jobs to queue up, but they are executed one by one, so having a number of items in the queue won't harm anything.

**Comment by abigailjxn** [comment]
Gotcha! Thanks for your input. In all the complications, it ended up being an old cache that was holding on after I ran all the transforms, which are now nice and regenerated. I will see myself out. 👋 🙏
