### ISSUE TITLE
imgix api-key parameter added to all image requests

### ISSUE THREAD

**Issue by jeremyfrank** [nystudio107/craft3-imageoptimize#39]
When using imgix, all image requests have the api-key appended as a url parameter. I'm assuming this should only happen for purge requests, and not for normal public requests?

e.g.
```
https://mydomain.imgix.net/filename.jpg?api-key=[key-from-plugin-config]&auto=compress%2Cformat&crop=focalpoint&domain=mydomain.imgix.net&fit=crop&fp-x=0.5&fp-y=0.5&h=450&ixlib=php-1.2.0&sharp=50&w=600
```

**Comment by khalwat** [comment]
Fixed in 1.4.12:

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.12

You'll need to go to Settings->Fields and then click on your OptimizedImages field(s) and click on Save to have it regenerate the URLs.
