### ISSUE TITLE
The process has been signaled with signal "7".

### ISSUE THREAD

**Issue by bartrylant** [nystudio107/craft3-imageoptimize#396]
### Describe the bug
I'm having a queue full of failed Optimizing image id tasks. The error is:
`The process has been signaled with signal "7".`

### To reproduce
Steps to reproduce the behaviour:
Save an entry with an ImageOptimize field
Wait for the queue to show this error

### Screenshots
<img width="784" alt="Scherm­afbeelding 75" src="https://github.com/nystudio107/craft-imageoptimize/assets/1434451/9791b629-5df9-482e-87cd-c71404a8cefb">

### Versions
- Plugin version: 4.0.5
- Craft version: Craft Pro 4.7.1

**Comment by khalwat** [comment]
This is very likely to be a server-side issue, but I'd need to see the full stack trace to help you diagnose it. It should be in your `queue.log`

**Comment by khalwat** [comment]
Will re-open if more information is provided
