### ISSUE TITLE
When will be the Craft5 version of Image Optimize be released?

### ISSUE THREAD

**Issue by E2design** [nystudio107/craft3-imageoptimize#397]
Working hard on some projects to get them ready to move them to Craft5. Most of the used plugins are Craft5 ready but Image Optimize is lacking. 

When can we expect a Craft5 version?

**Comment by khalwat** [comment]
I"m hoping this week!

**Comment by khalwat** [comment]
So the Craft 5 port is all done... I'm just documenting some cool new features I've added to it :)

**Comment by E2design** [comment]
Happy with that news :)

**Comment by khalwat** [comment]
A little preview:

![carbon (7)](https://github.com/nystudio107/craft-imageoptimize/assets/7570798/6a45d731-0ee9-4625-8c0d-55385ecf43cf)
![carbon (6)](https://github.com/nystudio107/craft-imageoptimize/assets/7570798/2cfad5d8-71aa-4001-9f69-43393d25ebb7)

**Comment by khalwat** [comment]
Craft 5 version released: https://github.com/nystudio107/craft-imageoptimize/releases/tag/5.0.0-beta.1

**Comment by khalwat** [comment]
Details on the new `.imgTag()`, `.pictureTag()` (with `.artDirection()`), `.linkPreloadTag()`, etc. here -> https://nystudio107.com/docs/image-optimize/using.html#displaying-images-on-the-frontend
