### ISSUE TITLE
Sharp: Asset name won't show in src="" so it doens't get SEO ranking

### ISSUE THREAD

**Issue by Nielsvdel** [nystudio107/craft3-imageoptimize#399]
### Describe the bug
When I use the Sharp transform method and then view the image-src in the HTML the src doesn't show the filename in the URL. Also if I try to download the image I get a filename like this: _eyJidWNrZXQiOiJpeHJlbmV3YWJsZXMtMjAyNCIsImtleSI6Im1lZGlhL1NlcnZpY2VzL3NlcnZpY2UxLmpwZyIsImVkaXRzIjp7ImpwZWciOnsicXVhbGl0eSI6ODAsInByb2dyZXNzaXZlIjpmYWxzZSwidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWl6ZVN_

With imgix I get the filename which like it is in the CMS.

### Versions
- Plugin version: 4.0.5
- Craft version: 4.8.1

**Comment by khalwat** [comment]
That's just how Sharp generates the image name, file an issue on the Sharp repo if you'd like to see it changed.
