### ISSUE TITLE
Add option to resize and resave uploaded image and discard the original upload

### ISSUE THREAD

**Issue by juresrpcic** [nystudio107/craft3-imageoptimize#40]
If a client uploads an image that is too large (either due to format - eg. TIF - or to size - eg. huge 10k x 10k image), there should be an option to enforce:

- maximum size (fit to bounds) in pixels - width and height
- image format (probably good to keep png=png, jpg=jpg and just convert other image types to jpg)

Another benefit of this could be quality - there is an old trick (and a plugin) for Photoshop where if you're a professional photographer and really want to optimize your photos for the web (though this was in pre-retina times), you would run it through a few consecutive unsharp mask filters - so resize down a bit, unsharp mask slightly, resize down a bit, unsharp... etc. Doing multiple steps like this produced a significantly better image than just unsharpening strongly and downsizing (which is still better than nothing). 

So by adding a sharpening step before saving the smaller original in case the image is really big (say you're starting with a camera upload 8k x 8k) - and then using the existing option to use sharpening when creating transforms *as well* would actually produce better quality images than just uploading a huge file (like it is now) and only sharpening once on transform creation.

Going even further, there could be conditional code that does multiple sharpening-downsizing passes if the image is really large, until reaching a specified desired original size (still bigger than any transforms obviously).

**Comment by davidhellmann** [comment]
The downscale sounds nice. Simply via config or backend setting to set the longest side of an image. I like it to have a big bigger pictures cause we don't know what needs in the future and diskspace ist cheap. But to cap on 4000xXXX oder 3000xXXX would be nice. 

Also the renaming from JPEG > jpg and stuff like this sounds good.

**Comment by khalwat** [comment]
So my stance on this thus far is that ImageOptimize never ever ever touches the pristine original. It only makes optimized variants from the pristine original.

What I do on the frontend is that I never display any client-uploaded image on the frontend; instead, I create optimized variants from their uploads with ImageOptimize. I do the same thing with text with the [Typogrify](https://github.com/nystudio107/craft-typogrify) plugin.

So I'm not necessarily opposed to the idea of some kind of standards for image uploads, I'm just not 100% sure that it should be part of the ImageOptimize plugin.

Definitely will consider it, though.

**Comment by juresrpcic** [comment]
Just a note - while this would be very handy in ImageOptimize, I saw that VERBB are working on a Craft 3 version of their Image Resizer plugin - https://verbb.io/craft-plugins/image-resizer . I've been using this one in Craft 2, a nice feature was that you could set destructive resizing of uploaded images per asset type (eg. no more 2000x2000px images to be used as a small circle icon in the end).

Not sure if VERBB will be using all the advanced Unix resizing tools that ImageOptimize does though - it's the quality that those produce that makes IO really shine.

**Comment by khalwat** [comment]
I just came here to recommend their plugin:

https://verbb.io/craft-plugins/image-resizer/pricing

It doesn't do any of the image optimizing, but in a way, it doesn't matter. It's just a way to prevent people from uploading a massive image in the first place.

We're _still_ not going to display anything the client uploads on our web pages, and instead use transforms on them before displaying them; at which point ImageOptimize will kick in (whether you use an OptimizedImages field or a native Craft transform), and all is right with the universe.
