### ISSUE TITLE
Picture element not working in v4.0.7

### ISSUE THREAD

**Issue by clintonbeattie** [nystudio107/craft3-imageoptimize#401]
When using this code the image output

```
{% set optimizedImage = entry.testImage.one().optimisedImages %}
        {% if craft.imageOptimize.serverSupportsWebP() %}
            Supports WebP
        {% endif %}
        <img src="{{ optimizedImage.srcsetWebP() }}"
                srcset="{{ optimizedImage.srcset() }}"
                sizes="100vw" />
        <div class="image-test">
            
            <img src="{{ optimizedImage.srcsetWebP() }}"
                srcset="{{ optimizedImage.srcset() }}"
                sizes="50vw" />
        </div>
```

but when trying to output the picture element it does not render the image

```
{% set asset = entry.testImage.one() %}
        {{ asset.optimisedImages.pictureTag()
            .loadingStrategy('lazy')
            .sourceAttrs({
                'media': '(min-width: 800px)',
                'sizes': '80vw',
            })
            .addSourceFrom(asset.optimisedImages, {
                'media': '(max-width: 799px)',
                'sizes': '60vw',
            })
            .render() }}
```

It renders the HTML but the image does not appear on screen. (just showing the relative urls here, but they do output the absolute url)

```
<picture>
    <source type="image/webp" srcset="/_1400x787_crop_center-center_82_line/entry-img-veg.jpg.webp 1400w, /_1024x576_crop_center-center_82_line/entry-img-veg.jpg.webp 1024w, /_768x576_crop_center-center_60_line/entry-img-veg.jpg.webp 768w, /_320x240_crop_center-center_60_line/entry-img-veg.jpg.webp 320w" width="1400" height="787" media="(min-width: 800px)" sizes="80vw">
    <source srcset="/_1400x787_crop_center-center_82_line/entry-img-veg.jpg 1400w, /_1024x576_crop_center-center_82_line/entry-img-veg.jpg 1024w, /_768x576_crop_center-center_60_line/entry-img-veg.jpg 768w, /_320x240_crop_center-center_60_line/entry-img-veg.jpg 320w" width="1400" height="787" media="(min-width: 800px)" sizes="80vw">
    <source type="image/webp" srcset="/_1400x787_crop_center-center_82_line/entry-img-veg.jpg.webp 1400w, /_1024x576_crop_center-center_82_line/entry-img-veg.jpg.webp 1024w, /_768x576_crop_center-center_60_line/entry-img-veg.jpg.webp 768w, /_320x240_crop_center-center_60_line/entry-img-veg.jpg.webp 320w" width="1400" height="787" media="(max-width: 799px)" sizes="60vw">
    <source srcset="/_1400x787_crop_center-center_82_line/entry-img-veg.jpg 1400w, /_1024x576_crop_center-center_82_line/entry-img-veg.jpg 1024w, /_768x576_crop_center-center_60_line/entry-img-veg.jpg 768w, /_320x240_crop_center-center_60_line/entry-img-veg.jpg 320w" width="1400" height="787" media="(max-width: 799px)" sizes="60vw">
    <img class="lazyload" src="/_1400x787_crop_center-center_82_line/entry-img-veg.jpg" width="1400" height="787" loading="lazy" style="background-size: cover;">
</picture>
```

### Versions
- Plugin version: 4.0.7
- Craft version: 4.8.7

**Comment by khalwat** [comment]
Is it possible you have a CSS class `lazyload` that is making it hidden?

Have you tried debugging it using the browser to inspect the `<picture>` and `<img>` tag to see why they aren't appearing?

Can you give me a live URL to look at?

**Comment by clintonbeattie** [comment]
I'm afraid the project is just local at the moment. JPG images appear to be loading fine, it is just webP that is an issue. lazyload is not the issue here from what I can see.
I assume this just uses Craft's/PHPs own image generators like when you would use format? Something like the following would output a webP image fine.

```
{{ asset.getUrl({
  transform: 'thumb',
  format: 'webp',
}) }}"
```
I will try and get a version online.

**Comment by khalwat** [comment]
No, it uses `cwebp` to generate the WebP images -- if you go to ImageOptimize Settings it will show you what it expects. Also here:

https://nystudio107.com/docs/image-optimize/configuring.html#native-craft-images

**Comment by clintonbeattie** [comment]
Just in reference to webp. Locally in Craft in PHP Info it states 'WebP Support	enabled'. Do I still need to install 'cwebp'? If so, would you know how that is that done on a Mac local server? WebP is already installed via Homebrew but assume cwebp is different as it is not picked up on in ImageOptimizer when using {% if craft.imageOptimize.serverSupportsWebP() %}

**Comment by khalwat** [comment]
Yes, you need to install `cwebp`. Details are here: https://nystudio107.com/docs/image-optimize/configuring.html#native-craft-images
