### ISSUE TITLE
How do I incorporate my native image transforms into the .imgTag() method?

### ISSUE THREAD

**Issue by mattias78** [nystudio107/craft3-imageoptimize#404]
### Question

The docs state the plugin works with 'native Craft image transforms', how do I incorporate my native image transforms into the .imgTag() method?

For instance my code before I used the plugin was…

`<img src=“{{ featureImage.getUrl('insightFeatureImage') }} ”>`

Which renders an image with the image transform crop of 1200px x 700px

Now I’m doing:

```
{{ featureImage.optimizedImages.imgTag()
						.imgAttrs({
							'alt': altTxt,
						})
						.loadingStrategy('lazy')
						.render() }}
```

Which renders my image, but obviously there is no reference to the crop I want so all images appear different sizes? How do I add that? Does the plugin not actually work with Craft image transforms the way I envisioned? What am I missing here?

Thanks

**Comment by khalwat** [comment]
What it means by "using native Craft transforms" is that Craft's image transforms do the work under the hood.

To accomplish what you want, you'd be setting up a separate Optimized Images field that has the cropping the way you want it. ImageOptimize will then take care of the responsive image sizes and variants for you.
