### ISSUE TITLE
imgTag returns a string varible

### ISSUE THREAD

**Issue by smockensturm** [nystudio107/craft3-imageoptimize#406]
### Describe the bug
I don't know that it is a bug. But this

`{{ asset.optimizedImagesField.imgTag().render() }}`

Yields this:

_Impossible to invoke a method ("render") on a string variable ("<img...... etc. etc._

Where can I look to see what might be causing this and what could be the remedy?

### Versions
- Plugin version: 4.0.5
- Craft version: 4.6.0

**Comment by khalwat** [comment]
Can you do:

```twig
{% dump asset.optimizedImagesField.imgTag() %}
```

...so we can see what we're working with here?

**Comment by smockensturm** [comment]
Certainly.

`<img src="https://dycfhyaaa8c3t.cloudfront.net/eyJidWNrZXQiOiJhc3NldHMuYWhnYmFja3VwLmNvbSIsImtleSI6ImltYWdlcy80LVN0ZXAtUHJvZ3JhbS9sYXduX3Byb2dyYW1fbWFpbl9saXN0aW5nX3N0YWNrLnBuZyIsImVkaXRzIjp7InBuZyI6eyJxdWFsaXR5Ijo4MiwicHJvZ3Jlc3NpdmUiOnRydWV9LCJyZXNpemUiOnsid2lkdGgiOjE2MDAsImhlaWdodCI6MjMwNSwiZml0IjoiY292ZXIifSwic2hhcnBlbiI6dHJ1ZX19" srcset="https://dycfhyaaa8c3t.cloudfront.net/eyJidWNrZXQiOiJhc3NldHMuYWhnYmFja3VwLmNvbSIsImtleSI6ImltYWdlcy80LVN0ZXAtUHJvZ3JhbS9sYXduX3Byb2dyYW1fbWFpbl9saXN0aW5nX3N0YWNrLnBuZyIsImVkaXRzIjp7InBuZyI6eyJxdWFsaXR5Ijo4MiwicHJvZ3Jlc3NpdmUiOnRydWV9LCJyZXNpemUiOnsid2lkdGgiOjE2MDAsImhlaWdodCI6MjMwNSwiZml0IjoiY292ZXIifSwic2hhcnBlbiI6dHJ1ZX19 1600w, https://dycfhyaaa8c3t.cloudfront.net/eyJidWNrZXQiOiJhc3NldHMuYWhnYmFja3VwLmNvbSIsImtleSI6ImltYWdlcy80LVN0ZXAtUHJvZ3JhbS9sYXduX3Byb2dyYW1fbWFpbl9saXN0aW5nX3N0YWNrLnBuZyIsImVkaXRzIjp7InBuZyI6eyJxdWFsaXR5Ijo4MiwicHJvZ3Jlc3NpdmUiOnRydWV9LCJyZXNpemUiOnsid2lkdGgiOjEyMDAsImhlaWdodCI6MTcyOCwiZml0IjoiY292ZXIifSwic2hhcnBlbiI6dHJ1ZX19 1200w, https://dycfhyaaa8c3t.cloudfront.net/eyJidWNrZXQiOiJhc3NldHMuYWhnYmFja3VwLmNvbSIsImtleSI6ImltYWdlcy80LVN0ZXAtUHJvZ3JhbS9sYXduX3Byb2dyYW1fbWFpbl9saXN0aW5nX3N0YWNrLnBuZyIsImVkaXRzIjp7InBuZyI6eyJxdWFsaXR5Ijo2MCwicHJvZ3Jlc3NpdmUiOnRydWV9LCJyZXNpemUiOnsid2lkdGgiOjc2OCwiaGVpZ2h0IjoxMTA2LCJmaXQiOiJjb3ZlciJ9LCJzaGFycGVuIjp0cnVlfX0= 768w, https://dycfhyaaa8c3t.cloudfront.net/eyJidWNrZXQiOiJhc3NldHMuYWhnYmFja3VwLmNvbSIsImtleSI6ImltYWdlcy80LVN0ZXAtUHJvZ3JhbS9sYXduX3Byb2dyYW1fbWFpbl9saXN0aW5nX3N0YWNrLnBuZyIsImVkaXRzIjp7InBuZyI6eyJxdWFsaXR5Ijo2MCwicHJvZ3Jlc3NpdmUiOnRydWV9LCJyZXNpemUiOnsid2lkdGgiOjU3NiwiaGVpZ2h0Ijo4MjksImZpdCI6ImNvdmVyIn19fQ== 576w" width="1600" height="2305" sizes="100vw">`

**Comment by khalwat** [comment]
Please update to the latest version of ImageOptimize, which is currently 4.0.8. This will fix your issue.
