### ISSUE TITLE
Settings changes in control panel don't stick

### ISSUE THREAD

**Issue by marionnewlevant** [nystudio107/craft3-imageoptimize#41]
When I change the settings in the control panel (turning off Create Color Palette etc.), and then Save and then view the settings again, they are still on.

**Comment by khalwat** [comment]
If the settings are being overridden by your `config.php` you should see a warning about this.

But yes, whatever is in the `config.php` always overrides the db settings.

**Comment by Saboteur777** [comment]
+1 on this. Stock install of `composer require nystudio107/craft-imageoptimize`, CP should be able to override the default config.php - maybe a separate config/imageoptimize.php config file should be able override the CP settings.

**Comment by Saboteur777** [comment]
Even setting `'createColorPalette'` to `false` in vendor/nystudio107/craft-imageoptimize/src/config.php doesn't work: 

![image](https://user-images.githubusercontent.com/9061795/36052016-523ba836-0dec-11e8-828c-1eef5b82ba72.png)

**Comment by marionnewlevant** [comment]
This is with no config/image-optimize.php. When I create that file, it does override the control panel settings (and I do get the warnings). But with no config/image-optimize.php, the control panel settings don't work.

@Saboteur777 the vendor/nystudio107/craft-imageoptimize/src/config.php file is ignored, the one that will be used (if it exists) is config/image-optimize.php

**Comment by khalwat** [comment]
Fixed in 1.4.14:

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.14

**Comment by Saboteur777** [comment]
@marionnewlevant Thanks for the clarification! 

@khalwat Thank you for the new release!
