### ISSUE TITLE
Blank colour svg injected as bg image

### ISSUE THREAD

**Issue by Cstrachan4** [nystudio107/craft3-imageoptimize#410]
### Describe the bug
After updating to version 5.0.2 images are getting a grey svg injected as a css background via the style attribute meaning images with a transparency show a grey background instead. (downgrading to 5.0.1 fixes the issue)

### To reproduce
Steps to reproduce the behaviour:
1. Have image with transparency
2. View on front end

### Expected behaviour
This style attribute shouldn't get injected ('generatePlaceholders' setting is set to false)

### Screenshots
<img width="473" alt="Screenshot 2024-09-26 at 11 29 56" src="https://github.com/user-attachments/assets/c84d4b12-49a3-4576-af07-6a7b6d65f605">

resulting in

<img width="599" alt="Screenshot 2024-09-26 at 11 29 37" src="https://github.com/user-attachments/assets/6c0e08ef-89da-41b2-921b-c0cb54038bc2">

### Versions
- Plugin version: 5.0.2
- Craft version: 5.4.5.1

**Comment by khalwat** [comment]
Can you show me the code you're using to output said image?

**Comment by Cstrachan4** [comment]
Sure, here you go:


In template
```
{% block bWhoBlockImage %}
      {% if whoBlockImage %}
            {# Output optimized image #}
            {{ whoBlockImage.imageTransformMax.pictureTag()
              .pictureAttrs({
                  'class': 'who-section-block__image',
              })
              .imgAttrs({
                  'alt': whoBlockImage.alt ??? ' ',
              })
              .loadingStrategy('lazy')
              .render() }}
      {% endif %}
{% endblock %}
```
Component
```
{% if whoBlockImage or _whoBlockImage is defined %}
      <div class="who-section-block__image-wrap">

        {% block bWhoBlockImage %}

          {% if _whoBlockImage %}
            <img class="who-section-block__image" src="{{ _whoBlockImage }}" alt="" />
          {% endif %}

        {% endblock %}

      </div>
{% endif %}
```

**Comment by khalwat** [comment]
This is a result of the lazy loading strategy that is being used which works fine for normal images, but not for images like SVGs that can be transparent in places.

I'm looking into a solution that makes sense here.

**Comment by khalwat** [comment]
Addressed in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.56”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.10”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v5 as 5.0.3”,
```
Then do a `composer clear-cache && composer update`

**Comment by rmales** [comment]
This issue also seems to affect PNGs with transparent backgrounds (in 5.0.4), the patch only changes the behaviour for SVG and GIFs.

**Comment by khalwat** [comment]
@rmales would you like it done for PNGs as well?

**Comment by rmales** [comment]
@khalwat Yes, if possible, as we have users uploading PNGs with alpha transparency which hit this problem. I'd imagined it might be difficult to make that change though (as presumably, it works as desired for PNGs with a solid background).

**Comment by khalwat** [comment]
@rmales so I solved this with a slightly different approach.

I added a new `.placeholder('none')` parameter, so that you can specify that no background image CSS should be applied for a given image tag.

It now also defaults this parameter to `none` if the image is an `svg` or `gif`. It doesn't default it to `none` for `png` images, because you may or may not want it for some `png` images you use. But you can just add it yourself via the parameter above.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.59”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.13”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v5 as 5.0.6”,
```
Then do a `composer clear-cache && composer update`
