### ISSUE TITLE
.heic files give a set_mempolicy error. 

### ISSUE THREAD

**Issue by KarelJanVanHaute** [nystudio107/craft3-imageoptimize#415]
### Describe the bug
When the server encounters .heic files, it tries to process these. And this gives an error of "set_mempolicy"
<img width="510" alt="image" src="https://github.com/user-attachments/assets/cd85153c-c87d-4f10-9b2c-96e7b0ab977b" />

### To reproduce
Upload some .heic file

### Expected behaviour
I hope to ignore this filetype. 

### Versions
- Plugin version: 5.0.3
- Craft version: 5.5.5

**Comment by khalwat** [comment]
That's interesting... because it shouldn't be trying to optimize that file type. Do you have a little bit more of that log you could show? The screenshot cuts off the first line.

**Comment by KarelJanVanHaute** [comment]
@khalwat When digging deeper into the logs. I'm guessing it was not the .heic file. This only gives a warning. 

```
2024-12-16 13:49:26 [queue.WARNING] [application] Could not determine image information for /data/sites/web/fadweblivestatikbe/subsites/fadweb.live.statik.be/shared/public/files/IMG_2379.heic {"memory":16684280}
```
But the .heic file was followed by a .pdf. Only this is not clear in the console output. So the errors were from the .pdf that followed the .heic file. I've now disabled the transformation of .PDFs. And now it seems to work. 

Sorry for the confusion.
