### ISSUE TITLE
accessing Image Optimize plugin from another plugin

### ISSUE THREAD

**Issue by AlexVotry** [nystudio107/craft3-imageoptimize#43]
I'm trying to use the image optimizer with the element-api plugin in.  I am writing an app for a big touch screen. So the images won't be changing sizes, but I won't have control of the images they put in the cp.  After calling the image, I would like to modify it prior to converting it to json.  
my questions are:
1) how do I call your plugin?  my closest guess is: `use nystudio107\imageoptimize\ImageOptimize;`
this is incorrect. 
2) how do I call the createOptimizedImages() ?
```  
public function includeLeft(Entry $entry)
  {
    return $this->collection($entry->left, function($model) {
      $image = $model->image;
      $optimzedImage = ImageOptimize::getInstance()->createOptimizedImages(
        $image,
        [
          [
            'width' => 200,
            'useAspectRatio' => true,
            'aspectRatioX' => 1.0,
            'aspectRatioY' => 1.0,
            'retinaSizes' => ['1'],
            'quality' => 82,
            'format' => 'jpg',
          ],
        ]
      );
        return $optimzedImage;
    }, 'left');
  }
```

**Comment by khalwat** [comment]
If you only need a single size, I would just use a regular Craft transform for it.  There are two parts to the plugin:

1) The image optimizers that run for _any_ transforms created via Craft; these run `jpegoptim` etc. for you automatically for any image transform.

2) The OptimizedImages Field, which is for `srcset` and placeholder generation.

Since you don't need #2, I'd just use a regular old Craft transform on the images. ImageOptimize will dutifully optimize them for you.

**Comment by kbardi** [comment]
Hi @khalwat,
I'm trying to use **imageoptimize** from a website built with react, and I'm using `element-api` to fetch the data from Craft.

Is there any way to load images using an API? It could be adding this to element-api, or adding a new api only for images.

Thanks in advance,

**Comment by khalwat** [comment]
Absolutely! In the Element API, the OptimizedImages field is just a sub-field of your assets. So you can return them however you like.

Pseudo-code:

```php
$srcset = $entry->blogImage->optimizedBlogImages->srcset();
```

Where `blogImage` is your Assets field, and `optimizedBlogImages` is the Optimized Images field.

**Comment by khalwat** [comment]
Also if you end up using GraphQL, ImageOptimize works with that too:

https://github.com/nystudio107/craft-imageoptimize#graphql-via-craftql-plugin
