### ISSUE TITLE
'gd not installed' error

### ISSUE THREAD

**Issue by romanov-sky** [nystudio107/craft3-imageoptimize#45]
After one of the latest updates i get this error "Variable "gdInstalled" does not exist" though i have GD installed. And before this update plugin was working fine and placeholder silhouettes were created. Can you check this?

**Comment by khalwat** [comment]
On your server, do:

```
php -m
```

To have it print out a list of installed modules. I'm guessing you won't see `gd` listed.

**Comment by khalwat** [comment]
You can also go to Utilities->PHP Info and search on `gd` -- you should see something that looks like this:

![google chromescreensnapz1010](https://user-images.githubusercontent.com/7570798/36106137-80f22cfa-0fe4-11e8-825a-925210337dc5.png)

**Comment by khalwat** [comment]
All I'm doing is calling [extension_loaded('gd')](http://php.net/manual/en/function.extension-loaded.php) -- for whatever reason, it's returning `false` on your setup.

**Comment by romanov-sky** [comment]
i checked with 'Utilities->PHP' in Craft, it looks installed:


 Передача image.png… 99%


Пн, 12.02.2018 в 7:07 PM Andrew Welch писал(а):
> All I'm doing is calling extension_loaded('gd')[1] -- for whatever
> reason, it's returning false on your setup.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. http://php.net/manual/en/function.extension-loaded.php
  2. https://github.com/nystudio107/craft-imageoptimize/issues/45#issuecomment-364970405

**Comment by romanov-sky** [comment]
it looks i have GD installed, check my php settings:
http://1soul.frb.io/php_info.php

Пн, 12.02.2018 в 7:03 PM Andrew Welch писал(а):
> On your server, do:


> php -m
> 
> To have it print out a list of installed modules. I'm guessing you
> won't see gd listed.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/nystudio107/craft-imageoptimize/issues/45#issuecomment-364969138

**Comment by khalwat** [comment]
Well, now, that's very strange indeed. Why would it be showing as enabled in your `phpinfo()` but not when I call `extension_loaded('gd')`?

**Comment by romanov-sky** [comment]
i've no idea, that's odd! I reinstalled Php and downgraded version to
7.0 - no avail.

Вт, 13.02.2018 в 5:37 PM Andrew Welch писал(а):
> Well, now, that's very strange indeed. Why would it be showing as
> enabled in your phpinfo() but not when I call extension_loaded('gd')?> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/nystudio107/craft-imageoptimize/issues/45#issuecomment-365285196

**Comment by khalwat** [comment]
In version 1.4.15, I check to see if the function `imagecreatefromjpeg` exists to determine whether `gd` is active or not, see if it works for you:

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.15

**Comment by romanov-sky** [comment]
Now it works Ok (placeholder silhouettes are working no problem). But, i can not enter the imageoptimize settings in Craft control panel. When i click on plugin settings i get this error:
![2018-02-15_14-31-29](https://user-images.githubusercontent.com/35177055/36248361-3da2be58-125d-11e8-9f87-d172ac355051.png)

**Comment by romanov-sky** [comment]
does it really make sense to check for GD installed in the first place.. since it's a requirement for 'Craft 3' install?
