### ISSUE TITLE
Add support for Imgix secure URLs

### ISSUE THREAD

**Issue by benface** [nystudio107/craft3-imageoptimize#46]
Imgix gives us the ability to enable "secure URLs" on a source which requires image URLs to be signed with a secret token to be valid. Right now, image URLs generated with ImageOptimize are not signed so they're not valid when secure URLs are enabled, which makes ImageOptimize less secure! Haha no but it would be great if you could support it. ;)

More info: https://docs.imgix.com/setup/securing-images

**Comment by khalwat** [comment]
This is done in the `develop` branch, and will be part of the next release.

**Comment by benface** [comment]
Whoo!!!! Thank you!
