### ISSUE TITLE
Display a message when the browser doesn't support .webp

### ISSUE THREAD

**Issue by benface** [nystudio107/craft3-imageoptimize#47]
Instead of showing this:

https://slack-imgs.com/?c=1&url=https%3A%2F%2Fmonosnap.com%2Ffile%2F9y3yNio4xxHamFUKYqImcj09O5ydoy.png

**Comment by khalwat** [comment]
This is done, and checked into the `develop` branch. It will be part of the next release.

Now if the `webp` version of the image exists (e.g., your server is set up to generate them, and it's an `activeVariantProcessor`), but your browser doesn't support displaying `.webp` images, it'll just display the non-webp version of the image in its place.

![screen shot 2018-02-14 at 6 31 00 pm](https://user-images.githubusercontent.com/7570798/36233746-6f3ff000-11b5-11e8-89b2-911ac52a47ba.png)
