### ISSUE TITLE
Image Quality issues.

### ISSUE THREAD

**Issue by ddbr** [nystudio107/craft3-imageoptimize#51]
When using imageoptimize i get huge problems with image quality. The example image is 2500px width and is beeing downscaled to 1200px by imageoptimize. (webp get's even worse)

Standard Image transforms of Craft3 are doing a good job from quality side.

What to consider to get the the best image quality? Configuration not changed from standard so far.

**Detail** in image (100%)
![image](https://user-images.githubusercontent.com/14271017/36346594-36b01ec0-1441-11e8-9777-74a9d61b9c4f.png)

**same detail** in original image (100%):
![image](https://user-images.githubusercontent.com/14271017/36346596-5362ca7c-1441-11e8-9cc4-6e5b4e56f399.png)

**Comment by khalwat** [comment]
It uses the same image scaling/compression methods that Craft CMS uses, so as long as the quality setting is the same, the result should be the same as well.

So whatever works for you in terms of a quality setting in Craft transforms, use in ImageOptimize.
