### ISSUE TITLE
Placeholders adhering to the different variations

### ISSUE THREAD

**Issue by sjenset** [nystudio107/craft3-imageoptimize#52]
This is probably more of a feature request than a bug.

Basically, I am attempting to use this plugin to output an image in two variations; a 16:10 variation and a 1:1 variation.

In addition to just displaying the image, I want to lazy-load it while using a placeholder (doesn't matter which one, but let's say the LQIP-version) until the actual image is loaded.

Now, on large screens, displaying the 16:10 variation, the placeholder works nicely as it is the same size as the actual image. However, on smaller screens (displaying the 1:1 variation) the placeholder is still of a 16:10 aspect, making it smaller than the actual image.

So - would it be possible to get an extension to the various placeholder-methods so that we can somehow access the placeholders for each individual variation?

Then we could do something akin to `src="{{ placeholderImage }}" data-srcset="{{ srcset }}" data-placeholder-srcset="{{ placeholders }}"` on the img-element and implement custom JS-logic that set's the correct src based on viewport-width or something (read: I am totally open to completely different methods of implementing this if you can think of a better way)

**Comment by khalwat** [comment]
I think the way I'd want to do it would be to have a placeholder image for each aspect ratio, so we're not making more than we'd need to. My concern is not adding too much generation time for creating the images; adding in the placeholder silhouette for instance can be time consuming.

In the interim, you should be able to use the placeholder box without too much trouble; there's a Twig variable that lets you get an SVG placeholder box of any size:

https://github.com/nystudio107/craft-imageoptimize#arbitrary-placeholder-svgs

**Comment by khalwat** [comment]
Another thing you might consider if you want to take the KISS approach would be to just use one placeholder image, but use the `object-fit` CSS property:

https://www.w3schools.com/css/css3_object-fit.asp

...and not worry about it.
