### ISSUE TITLE
"Smart" responsive images

### ISSUE THREAD

**Issue by riasvdv** [nystudio107/craft3-imageoptimize#54]
Looking at the implementation of the `spatie/laravel-medialibrary` implementation of responsive images, I'm thinking/suggesting you could implement a few things that they do to make using it a lot easier.

One of the things they're doing is automatically calculating the necessary transform width for an image based on when it is 20% smaller. (https://github.com/spatie/laravel-medialibrary/blob/v7/src/ResponsiveImages/WidthCalculator/FileSizeOptimizedWidthCalculator.php) using this, you wouldn't need to specify all the image widths manually.

They also implemented a pretty smart way to use the placeholder without having to rely on something like lazysizes: https://github.com/spatie/laravel-medialibrary/blob/v7/resources/views/responsiveImageWithPlaceholder.blade.php

Of course this is in a Laravel environment so they probably have a bit more flexibility as to what they can do.

**Comment by khalwat** [comment]
Regarding the first issue, what it appears to be doing is making sizes pretty arbitrarily; when the file size is 20% smaller, then it decides to make an image at that size. Which is a somewhat reasonable idea, but I still think that it's better to be able to specify an actual width that matches your media queries.

By providing some base sizes with any new OptimizedImages field with a few default variants, we're effectively doing the same thing. They are also being a wee bit speculative just multiplying the file size by `0.7` to predict how big it'll be.

The second example appears to just be setting the `sizes` property dynamically via JavaScript, the placeholder just appears to be coming from a fixed source, if I'm understanding it correctly?

**Comment by riasvdv** [comment]
Regarding the first point, I personally don't think it should be based on media queries but rather on the display width of the image. The browser knows at what width the image is being displayed and will choose the best option for that case, so having arbitrary image sizes which are guaranteed to be the best choice within 20% of the filesize seems like a better option.
Certainly because we have 1 asset volume for images, and images can be displayed in any place in any size really. So we'd need to create a responsive size for each case _and_ have to update it if something in the layout changes at some point.

The second case is indeed doing just that, they create the Medium style effect of loading the image by providing an inline SVG and then switch the srcset once loaded.

**Comment by khalwat** [comment]
The thing is, we're not just using responsive image variants to make copies of the same images at various sizes. We might want the images that are display on mobile to be a different aspect ratio (say, 4:3 vs. 16:9 for desktop). I do this all the time, and if we just did what the Spatie lib does, we miss out on the.

Secondly, for art direction reasons, we may want to use an entirely different image.

I think the way IO does it gives us a good mix of flexibility and automation.
