### ISSUE TITLE
Column for .webp images shown when there is no such file/variant available

### ISSUE THREAD

**Issue by kbergha** [nystudio107/craft3-imageoptimize#57]
Hi.

Take a look at the screenshot.

![no-webp](https://user-images.githubusercontent.com/4321846/37035012-6da697f8-214b-11e8-954f-3f1b797d1409.png)

Given that webp is not installed on the server, and that webp is removed from the config in image-optimize.php:

```
    // Active image variant creators
    'activeImageVariantCreators' => [

    ],
```

Why is there a column showing .webp?
Look at the file size, they are exactly the same as the jpeg-version.

The assests are stored in an S3 bucket, and there is no .webp file there, just the JPG:

![no-webp2](https://user-images.githubusercontent.com/4321846/37035026-78fc83e2-214b-11e8-988e-13b1204ed19d.png)

It just seems that .webp is added to the URL:
https://s3.eu-central-1.amazonaws.com/some-s3-bucket-name/_1920x1080_crop_center-center_60_line/144/giraffe-wild-wildlife-nature-38534.jpg?mtime=20180306141745.webp

"some-s3-bucket-name" is not the actual bucket name ;)

Is it possible to turn webp completly off somehow?

Versions:
Craft 3.0.0-RC13
ImageOptimize 1.4.23

**Comment by khalwat** [comment]
So this is a concession that I put in for people who _do_ want to use `.webp` but are using a browser like Safari that doesn't support it. https://github.com/nystudio107/craft-imageoptimize/issues/47

I'll have to put in a check to make sure we don't try to do this when you have `.webp` off on the backend as well.

Sidenote: it makes me sad that you are not using `.webp`

**Comment by kbergha** [comment]
I'll try to add `.webp` when I have the time - to make you happy ;)

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-imageoptimize/commit/5c612e66098907402de27f6547eb6e81a3392718
