### ISSUE TITLE
Feature request - variations with same width, but different aspect ratios.

### ISSUE THREAD

**Issue by kbergha** [nystudio107/craft3-imageoptimize#58]
Hi (again).

I've got a feature request.

It is possible to add several diffrent variations of an image with the same width, but with a different aspect ratios.

But - as the width is used as a key in the optimizedImageUrls array - only the last variant added to the field config is generated.
I.e. if I've added several variants with width 940px and:

```
{% set optimizedImages = entry.testImage.one().images %}
{{ dump(optimizedImages) }}
```

I get:
```
object(nystudio107\imageoptimize\models\OptimizedImage)[555]
  public 'optimizedImageUrls' => 
    array (size=5)
      1920 => string 'https://s3.eu-central-1.amazonaws.com/....' (length=149)
      940 => string 'https://s3.eu-central-1.amazonaws.com/....' (length=147)
      540 => ....
      ....
```

I would very much like to be able to add several variants with the same width, but with different aspect ratios.

Could one option be to add an optional "handle" property to each variant, or maybe add the aspect ratio as a part of the array key? I don't know what's most practical.

In frontend/Twig, you could maybe add a srcHandle('myAwesomeHandle')?

**Comment by khalwat** [comment]
What I would recommend in this case is that you create a separate OptimizedImages field.

`srcset`s inherently are tied to the width, and OptimizedImages fields are essentially helpers for making `srcset`s. 

So it doesn't really make sense to have multiple versions of an image with the same same with width in any single OptimizedImages field.
