### ISSUE TITLE
An Option to recreate Sizes (Multiselect)

### ISSUE THREAD

**Issue by davidhellmann** [nystudio107/craft3-imageoptimize#60]
Is it possible to add an option like this:
![image](https://user-images.githubusercontent.com/764292/37450535-8fab04f8-282e-11e8-8c18-c32b4e5c1792.png)

When something is wrong and some images are not created it's a bit pain to open each image and save it again. It would be nice to multiselect this images and click a link.

**Comment by khalwat** [comment]
So all you need to do is go to the Field or Asset Volume and click Save and it will re-save any Optimized Images in that Asset Volume.

The idea of adding this to the GUI is nice tho, I like it. So I'll keep it open as a FR.

**Comment by khalwat** [comment]
In retrospect, since this happens automatically when you save an image, I think this probably isn't needed.
