### ISSUE TITLE
Imgix Secure Urls not working

### ISSUE THREAD

**Issue by alexr8** [nystudio107/craft3-imageoptimize#61]
If i enable secure urls with imgix, and add the token to image optimize settings and save, images get 403'd. If i return to the image optimize settings, the security token field is now blank.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize/commit/29f176e1b0e73c14612d732095cd4a2234fd7836

**Comment by alexr8** [comment]
Awesome - thanks for the quick fix!
