### ISSUE TITLE
Placeholder images and asset transforms

### ISSUE THREAD

**Issue by Coysh** [nystudio107/craft3-imageoptimize#62]
May not be an issue per-se, but currently the placeholder doesn't have an option to take into account any image transforms.

Extremely useful for some clients - especially headshots that are cropped to square.

**Comment by khalwat** [comment]
hmmmm. The placeholder images should reflect the after-transformed image. Are you not seeing that?

**Comment by Coysh** [comment]
Not presently - but it might be that I've coded it wrong?
`{% set image = staff.staffPhoto.one() ?? pageDefaults.featuredImage.one() ?? null  %}
{% set optimisedImages = image.optimisedImages %}
{% if image %}<img src="{{ optimisedImages.placeholderImage() }}" data-src="{{ image.getUrl('headshot') }}" class="lazyload blur-up" alt="{{ image.title }}"/>{% endif %}`

Do I need to pass the transform to the optimiser?

**Comment by khalwat** [comment]
No, the transforms are built into the Field; did you not set those up? Each Variant that you set up in the Field is a transform.

**Comment by khalwat** [comment]
![google chromescreensnapz1094](https://user-images.githubusercontent.com/7570798/37661427-28f64d8e-2c2b-11e8-87f9-de1fbe930fcd.png)

^ each of these is a transform.

**Comment by Coysh** [comment]
@khalwat Sorry - I'm talking about 'Image Transforms' like this
![image](https://user-images.githubusercontent.com/5764356/37661689-48e6289a-2c4d-11e8-8620-481f82aecd3e.png)

**Comment by khalwat** [comment]
The placeholder images exist only in the context of an OptimizedImages field. Any transforms you've set up in Craft aren't relevant or used.

There are three separate things that ImageOptimize does for you:

1 - Any transforms you create anywhere will automatically be losslessly optimized one you've set that up as per the docs

2 - You can pick between using Craft transforms of Imgix transforms

3 - There is an OptimizedImages field that if you use it, makes creating image `srcset`s easy

It is this third component that handles the creation of placeholder images. So you will only have access to them from within the context of OptimizedImages fields.

OptimizedImages fields do not use any of your named Craft transforms; you set up the Optimized Image Variants in the Field settings, and those will be used to transform the images.

**Comment by Coysh** [comment]
Thanks for the clarification on this.
