### ISSUE TITLE
Add option to disable Image Optimize fields from displaying in asset preview.

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft3-imageoptimize#63]
Trying to use asset fields is painfully slow with Image Optimize installed. It regularly takes over 6 seconds after double clicking an asset to have its options show up. Makes adding alt text really frustrating.

Additionally, we don't really care to have the crops show up for our clients. We just need the plugin to work behind the scenes.

**Comment by khalwat** [comment]
The feature is already in there... check the Field settings:

<img width="650" alt="google chromescreensnapz095" src="https://user-images.githubusercontent.com/7570798/37858039-7850e3a0-2ed6-11e8-8d50-9f8835942af4.png">
