### ISSUE TITLE
Add the ability to set the lower quality used for `lowerQualityRetinaImageVariants`

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft3-imageoptimize#65]
In some images that are transformed for retina I've noticed some gradient banding and other quality issues because the `lowerQualityRetinaImageVariants` quality is so much lower than the 1x size. I was able to fix this by turning off the 2x size and creating another variant, but it would be nice to be able to set the quality level that `lowerQualityRetinaImageVariants` uses.

**Comment by khalwat** [comment]
Yeah I think it's a touch aggressive for the retina images. Planning to make it 1.5 / retinaSize which for images set to “Very High (recommended)” which is `82` in quality results in `61.5` for the retina image

**Comment by khalwat** [comment]
Implemented in 1.4.25

### Changed
* Fixed a typo in the `config.php` settings, changed `generatePlacholders` -> `generatePlaceholders`
* Made the reduced quality of retina images if `lowerQualityRetinaImageVariants` is enabled less aggressive
