### ISSUE TITLE
generatePlacholders -> generatePlaceholders

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft3-imageoptimize#66]
There's a typo in the `generatePlacholders` (missing an 'e'), but it works because it's consistent throughout its use in the plugin.

**Comment by wbrowar** [comment]
This would need to be updated in `config.php` for anybody who's using one, so maybe it would be good to deprecate it or make a note if this does get fixed

**Comment by khalwat** [comment]
This was fixed in https://github.com/nystudio107/craft-imageoptimize/commit/c816f7b677f7f31a440afb1458c4cf86a07b34ae
