### ISSUE TITLE
Error on image upload

### ISSUE THREAD

**Issue by dlaprade** [nystudio107/craft3-imageoptimize#67]
Versions:

- CraftCMS 3:latest
- craft-imageoptimize:latest

Error:
Exception 'Error' with message 'Access to undeclared static property: nystudio107\imageoptimize\ImageOptimize::$generatePlaceholdersholders'

I think it might be related to this checkin:
https://github.com/nystudio107/craft-imageoptimize/commit/c816f7b677f7f31a440afb1458c4cf86a07b34ae#diff-06e49d5eb945a7eabb9795a57fc1fc00

**Comment by khalwat** [comment]
Fixed in 1.4.26... just a typo.

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.26
