### ISSUE TITLE
Consider disabling autoSharpenScaledImages if imgix is used

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft3-imageoptimize#68]
Just set up imgix and immediately noticed a heavy glow on the edges of our images. Seems that their sharpen feature isn't the best.

https://docs.imgix.com/apis/url/adjustment/sharp

**Comment by khalwat** [comment]
huh. Or maybe I'm not passing the right parameters to it. Can you show me what an image looks like before and after?

**Comment by jsunsawyer** [comment]
Here's a link to an image with sharpen used:

https://nebraska-loves-public-schools.imgix.net/images/blog/StandingUptoPoverty.jpg?crop=focalpoint&domain=nebraska-loves-public-schools.imgix.net&fit=crop&fm=webp&fp-x=0.5&fp-y=0.5&h=324&ixlib=php-1.2.1&q=82&sharp=50&w=576

Changing the `sharp=50` value to 0 or removing it will show the difference:

https://nebraska-loves-public-schools.imgix.net/images/blog/StandingUptoPoverty.jpg?crop=focalpoint&domain=nebraska-loves-public-schools.imgix.net&fit=crop&fm=webp&fp-x=0.5&fp-y=0.5&h=324&ixlib=php-1.2.1&q=82&sharp=0&w=576

**Comment by khalwat** [comment]
To me, this is a sharpen filter doing what it's supposed to do. What level of sharpness do you think looks good?

**Comment by jsunsawyer** [comment]
Hmmm. Maybe it is, but the outer glow seems extreme and unwanted. Creates a border/glow effect in use on our site. I don't think we had that show up when not using imgix. I can just disable the sharpen option.

**Comment by khalwat** [comment]
Right, so play around with the parameter, and tell me what number for `sharp=` seems good to you in terms of sharpening the image, but not creating too much "glow"?

**Comment by jsunsawyer** [comment]
It seems like anything over 20 starts getting really noticeable. So 20 would probably be good.

I have an open support request with imgix. Here's a test of a solid color at sharpen=50. I really just think that imgix is handling sharpen poorly.

https://iloveps.imgix.net/images/test-solid.png?auto=compress&crop=focalpoint&domain=iloveps.imgix.net&fit=crop&fm=webp&fp-x=0.5&fp-y=0.5&h=300&sharp=50&ixlib=php-1.2.1&w=328

**Comment by khalwat** [comment]
Well, it also could be just that their numbers are on a different scale. I'll make it 20 for Imgix.

**Comment by jsunsawyer** [comment]
imgix recommended trying https://docs.imgix.com/apis/url/adjustment/usm

Looks like that should resolve the "edge glow" issue.

**Comment by khalwat** [comment]
Switched over to Unsharp Mask in 1.4.28 -- it does look better, thanks!

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.28
