### ISSUE TITLE
Can't save Image after Setting FocalPoint

### ISSUE THREAD

**Issue by davidhellmann** [nystudio107/craft3-imageoptimize#69]
Newest Version

![image](https://user-images.githubusercontent.com/764292/38167600-ef0750b2-3537-11e8-8bbb-894bf3c8acc8.png)

:| :)

**Comment by khalwat** [comment]
Fixed in 1.4.26... just a typo.

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.26
