### ISSUE TITLE
3.0.0-beta.20 beaks the translation files

### ISSUE THREAD

**Issue by johanzandstra** [nystudio107/craft3-imageoptimize#7]
The plugin is broken with the last Craft update. 

Please note one of the release note's of the update. 

{note} Plugin handles are kebab-cased now rather than camelCased. Plugins’ Craft::t() and |t() calls, translation files, and template paths must be updated accordingly, as well as any plugin config files in Craft 3 projects.

Please let me know if i can assist you with the fix!

**Comment by khalwat** [comment]
This is fixed in 1.0.9
