### ISSUE TITLE
Slow processing time

### ISSUE THREAD

**Issue by redkrupp** [nystudio107/craft3-imageoptimize#70]
What are the best practices to speed up the transformation procedure. I have around 12k images and it takes ages to process them all.

I'm using the AsyncQueue plugin (https://github.com/ostark/craft-async-queue) but it makes no difference. The server has 2GB of RAM and memory limit is set to 1536.

**Comment by khalwat** [comment]
I would do it via the CLI... 

https://github.com/nystudio107/craft-imageoptimize#command-line-optimized-image-variant-creation

You can start it with `screen` and just let it run. I would expect it to take a long time with 12k images.
