### ISSUE TITLE
Purchase a license key?

### ISSUE THREAD

**Issue by brandondeweese** [nystudio107/craft3-imageoptimize#72]
Crazy question...Where and how do I purchase a license key?

**Comment by kbergha** [comment]
Could you (or @khalwat ) tell me where you got your key?

In the CP:

![untitled2](https://user-images.githubusercontent.com/4321846/38421365-2c0ff338-39a7-11e8-909b-f7e567b28443.png)
This goes to the plugin settings, but I can't find any option to purchase a key...

![untitled](https://user-images.githubusercontent.com/4321846/38421281-e89f91c6-39a6-11e8-9a4b-66fd669a4a91.png)

I can't see an option "to pay up" anywhere in Craft ID either - it just says I have "No plugin licenses."

**Comment by kbergha** [comment]
Found it - thank you GitHub for beeing my rubber duck.

1. Go to plugin store in the CP
2. Find correct plugin
3. Puuuuuuuuuuush the buy-button
4. Enjoy!

![untitled3](https://user-images.githubusercontent.com/4321846/38421805-b86f4486-39a8-11e8-9b90-cc4457cc9a12.png)
