### ISSUE TITLE
[FR] Use selected image format unless source image is animated GIF

### ISSUE THREAD

**Issue by markhilverda** [nystudio107/craft3-imageoptimize#73]
An option to override the selected image format if the source file is an animated GIF would be very helpful. For example, a large image library needs to be maintained in one assets volume (for easy searching), and JPG variants are preferred, unless the source image is an animated GIF - then the variants should be animated GIFs.

**Comment by paraform** [comment]
Is there a solution for animated GIFs? They stop animating after the transform.

**Comment by markhilverda** [comment]
@paraform - This could be due to ImageMagick not being installed or unavailable. I encountered a similar issue on a new server and once Craft recognized ImageMagick, the transformed GIFs were processed with animations intact.

**Comment by paraform** [comment]
@markhilverda that is exactly the problem, Craft is using GD at the moment. I will install imagik and confirm. Thanks

**Comment by khalwat** [comment]
I'm going to roll this into the next version @markhilverda

**Comment by markhilverda** [comment]
Wonderful! Thanks very much @khalwat

**Comment by khalwat** [comment]
Okay, maybe not the _very next version_ -- but it's coming!

**Comment by khalwat** [comment]
Related: https://github.com/nystudio107/craft-imageoptimize/issues/100

**Comment by markhilverda** [comment]
Thanks for the update @khalwat - looking forward to it!

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-imageoptimize/commit/97eb6664d67b2e766408cf9cc5dffed966234d8b

**Comment by markhilverda** [comment]
Thanks for looking into this @khalwat - being able to detect if the source file is an animated GIF and then automatically overriding any image transform formats to GIF to retain the animated transforms would be really helpful.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-imageoptimize/commit/705a721709706ba3744e7e478017b008ac4aa6ac

You can test this out by setting your semver to:
```
"nystudio107/craft-imageoptimize": "dev-develop as 1.6.4"
```
...and doing a `composer update` -- let me know how it works for you
