### ISSUE TITLE
Updating Asset Indexes Removes All Image Optimize Images

### ISSUE THREAD

**Issue by brandondeweese** [nystudio107/craft3-imageoptimize#74]
Hi, when I update asset indexes, it removes all images that are transformed using the plugin. Basically, in the code, the image URL just shows up blank. Have you seen this before?

**Comment by khalwat** [comment]
I just tested this locally, and what it's doing for me is after update the Asset Index, it's re-generating the Optimized Images:

![google chromescreensnapz1135](https://user-images.githubusercontent.com/7570798/38627853-f2b4b0da-3d7d-11e8-8974-134597f24863.png)

This should happen automatically. If for some reason it doesn't, you can always go to the Asset Volume in question via AdminCP -> Settings -> Assets then click on the Asset Volume in question, and click Save and it should kick off the re-saving.
