### ISSUE TITLE
licensing issue banner on local site

### ISSUE THREAD

**Issue by KatieMFritz** [nystudio107/craft3-imageoptimize#75]
I have a live site and a local/dev site (thanks again for the awesome multisite config repo!). My client just purchased a license on the live site. I copied the database from live to local, and I'm getting the error "This license is tied to another Craft install."

That totally makes sense, but the banner alert is annoying and obviously I'm not going to buy a second license for my local install - I'm not even using the plugin locally, since I'm on Windows and don't have good optimization tools installed (don't @ me 😆 ). The only reason I have the plugin on the local install is because that's where I'm installing/updating all plugins.

Any tips for how to make the banner go away, other than custom CSS to hide it?

**Comment by khalwat** [comment]
So the easiest way to do it is just to have your local development domain be `.dev` or `.test` or such; Craft doesn't complain about licensing issues if it thinks you're running on a local dev or staging domain.

The other thing you can do is (I _think_) copy the `license.key` from `config/` on the server to your local dev; then it should think it's running on the same install.

**Comment by KatieMFritz** [comment]
Note for future Katie and others: go to https://id.craftcms.com/account/licenses/cms and download the `license.key` file. Don't just copy/paste the license string.
