### ISSUE TITLE
Support for Redactor fields

### ISSUE THREAD

**Issue by rjdusk** [nystudio107/craft3-imageoptimize#77]
I have an issue where clients will put images into their Redactor fields (sometimes 4mb sized files) and would love to be able to optimize them with this plugin. Something similar to what [RetconHTML](https://github.com/mmikkel/RetconHTML-Craft/) does. Is this possible?

**Comment by khalwat** [comment]
If you were willing to go in and re-write the HTML using Retcon post facto, that should work.

I'm not really sure of any other way that this could integrate with Redactor unfortunately.

**Comment by rjdusk** [comment]
No worries, I figured out a much more elegant way of handling this with Super Tables and embedded Matrix fields. It makes the admin interface for editing much easier to understand and shifts image handling away from the Redactor field and back into an Image Optimize field 👍  Thanks for all the hard work mate!

**Comment by martin-coded** [comment]
I am also looking for a workaround for older articles. At this point, the solution doesn't have to be good. It should just give the editors enough time to update the old articles. I am even considering using the craft cms transforms with Retcon and curl all articles in a staging area, to have kind of "pre" generated all images.

I'm aware that just not using images in a rich text field is the solution :) But this will not solve mistakes from the past.

Unfortunately, using Retcon doesn't really work with pre-generated images.
https://github.com/mmikkel/Retcon-Craft/issues/52

Could an integration with CKeditor be a possibility or do you think a basic integration with any WYSIWYG Editor is not possible?

**Comment by khalwat** [comment]
Given that P&T is ending support for Redactor in favor of CKEditor, I'm going to close this issue.

Once the CKEditor from P&T supports 3rd part plugins, perhaps we can evaluate it for that plugin.
