### ISSUE TITLE
Replacing assets that use imgix are not purged

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft3-imageoptimize#80]
I've verified that my **Imgix Source Domain** and **Imgix API Key** are properly set.

**Comment by khalwat** [comment]
The handler is in place to do it, though?

```
        // Handler: Assets::EVENT_BEFORE_REPLACE_ASSET
        Event::on(
            Assets::class,
            Assets::EVENT_BEFORE_REPLACE_ASSET,
            function (ReplaceAssetEvent $event) {
                Craft::debug(
                    'Assets::EVENT_BEFORE_REPLACE_ASSET',
                    __METHOD__
                );
                /** @var Asset $element */
                $element = $event->asset;
                // Purge the URL
                $purgeUrl = ImageOptimize::$transformClass::getPurgeUrl(
                    $element,
                    ImageOptimize::$transformParams
                );
                if ($purgeUrl) {
                    ImageOptimize::$transformClass::purgeUrl($purgeUrl, ImageOptimize::$transformParams);
                }
            }
        );
```

Are you able to see `Assets::EVENT_BEFORE_REPLACE_ASSET` in the `web.log`?

**Comment by khalwat** [comment]
In your log, you should also see either an info or error logged:

```
            Craft::info(
                'URL purged: '.$url.' - Response code: '.$response->getStatusCode(),
                __METHOD__
            );
        } catch (\Exception $e) {
            Craft::error(
                'Error purging URL: '.$url.' - '.$e->getMessage(),
                __METHOD__
            );
```

**Comment by jsunsawyer** [comment]
I'm not seeing any of that stuff.

**Comment by khalwat** [comment]
Do you have `devMode` enabled?

**Comment by jsunsawyer** [comment]
Nope. This is on our staging site and I've verified that devMode is not enabled.

**Comment by jsunsawyer** [comment]
I just pushed a bunch of craft/plugin updates to our server and I'm not longer having this issue. There's a chance that imgix was having issues earlier and that was causing images to not update. I'll keep an eye out for this.

**Comment by khalwat** [comment]
If you run into it again, turn `devMode` on for the staging server to see the logged messages

**Comment by AdamChlan** [comment]
Not sure if it's best to comment on this issue, or start a new one, but I am seeing the following errors when trying to replace a file with the same name:

```
Client error: `POST https://api.imgix.com/v2/image/purger` resulted in a `401 UNAUTHORIZED` response:
Unauthorized
```

I have my API key set, and it has purge privileges. Curious if there is anything else I should be looking for here.

**Comment by khalwat** [comment]
@AdamChlan probably over here? https://github.com/nystudio107/craft-imageoptimize/issues/273

**Comment by AdamChlan** [comment]
@khalwat We are seeing the issue on a few different versions, but we do have a version running the latest, including `craft-imageoptimize-imgix` at version 1.2.2. We'll keep hunting on our end, but let me know if any other info would be useful.
