### ISSUE TITLE
stop pending? 

### ISSUE THREAD

**Issue by daniellefrapp** [nystudio107/craft3-imageoptimize#81]
Is there a way I can stop pending jobs? I've tried deleting logs, I've tried disabling the plugin but no matter what I do I have a lot of pending jobs I can't seem to stop. 
![screen shot 2018-04-27 at 1 35 39 pm](https://user-images.githubusercontent.com/33430386/39376511-eea44394-4a1f-11e8-8397-dd8e0e404379.png)

**Comment by daniellefrapp** [comment]
I was able to fix it by emptying the queued table.

**Comment by khalwat** [comment]
Yeah, this is really a generic Craft issue with tasks. Until there is a Task Manager / Queue Manager style plugin, emptying the `queue` table will do it.
