### ISSUE TITLE
Return width and height

### ISSUE THREAD

**Issue by rjdusk** [nystudio107/craft3-imageoptimize#84]
Heya mate,
I'm trying to return the width and height of the largest transformed image, but for the life of me can not figure it out. Any chances you could point me in the right direction?

Typically I would do this with a Craft asset `image.getWidth()` and `image.getHeight()`. But this method just results in errors, like so:

`Impossible to access an attribute ("getHeight") on a string variable ("//localhost:3000/images/portfolio/_1920x1281_crop_center-center_82_line/selifoss-closeup@2x.jpg").`

Which makes sense, but I'm really scratching my head on how I retrieve these attributes. Any pointers? Cheers!

**Comment by khalwat** [comment]
So you can get the width of the transformed images as described here:

https://github.com/nystudio107/craft-imageoptimize#iterating-through-urls

Or you can use the media srcset sizes which might do what you want:

https://github.com/nystudio107/craft-imageoptimize#media-query-srcset-sizes

**Comment by shalanah** [comment]
Hi, loving the plugin so far! 

I'm using image optimizer with lazysizes and the parent-fit plugin (https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/parent-fit).

In order for lazysizes to pick the correct bg cover image I need to supply a height for at least one of the transformed images. It would be great if we could have easy access to the transformed image heights. This would be especially helpful in cases where there are specific (and different) ratios set.

Lucky for me, we are not setting ratios for our transformed images and just setting widths so I can calculate the height by using the original image width/height.

**Comment by rjdusk** [comment]
Right, so getting the width of my images is no problem - as pointed out by @khalwat above, this works just fine. But I would love to get the height of my transformed image too. 

I'm using the very awesome [PhotoSwipe](https://github.com/dimsemenov/PhotoSwipe) modal  gallery and [image dimensions](http://photoswipe.com/documentation/faq.html#image-size) are required for a part of the script to operate correctly.

I have my galleries almost complete with Lazysizes to lazy load the images, ImageOptimize to transform my images and enforce correct image aspect ratio, PhotoSwipe for image modals and Bulma to control the aspect ratio boxes via CSS on the front end. Just need the height :)

**Comment by khalwat** [comment]
Yeah I've had times where I've wanted access to the height and width too. I'll turn this into a FR (Feature Request) and re-open it.

**Comment by khalwat** [comment]
Added to the docs:

### Image Variant Height

Should you want to access the height of a given variant, you can do that via:

```twig
    {% set optimizedImages = entry.myAssetField.one().optimizedImagesField %}
    {{ optimizedImages.variantHeight[VARIANT_WIDTH] }}
```

...where `VARIANT_WIDTH` is the width of the image variant.

Or to iterate through the `width` as well as the `height`, you can do:

```
    {% set optimizedImages = entry.myAssetField.one().optimizedImagesField %}
    {% for width,height in optimizedImages.variantHeight %}
        {{ width ~ ' - ' ~ height }}
    {% endfor %}
```

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-imageoptimize/commit/4ceac375c893b823f3dce948ace52932d836f3b0
