### ISSUE TITLE
Stuck on ”Optimizing images”

### ISSUE THREAD

**Issue by slebbo** [nystudio107/craft3-imageoptimize#85]
I have a bunch of images with ImageOptimize on top, I just changed the settings (the image quality) so ImageOptimize begun to run the task to generate new versions of the images. 

But, it has stuck now on 10% and it's been over 20 hours. So something has happened but I don't know where to figure out the error. Also, there's no front-end option to cancel the task either afaik.

It would be cool with a more detailed progress, so one can see whats going in the machinery ![alt text]

[Screenshot on dropbox](https://www.dropbox.com/s/kdf2hs1uadorm4c/Sk%C3%A4rmklipp%202018-05-17%2012.53.09.png?dl=0)

**Comment by khalwat** [comment]
@slebbo So what I'd suggest doing is truncating the `queue` table (this is a general way remove any stuck tasks in Craft 3, not just IO tasks).

Options you have then are:

1) Increase the PHP `max_execution_time` and try again
2) Install the [Async Queue](https://github.com/ostark/craft-async-queue) plugin which will run _all_ Craft queue jobs via a CLI where there are no restrictions on the `max_execution_time` and such
3) Generate the transforms via CLI as per: https://github.com/nystudio107/craft-imageoptimize#command-line-optimized-image-variant-creation

**Comment by slebbo** [comment]
Didn't notice that CLI function 😮. That is exactly what I wanted  💯
