### ISSUE TITLE
"Auto" format causes crop to fail

### ISSUE THREAD

**Issue by wfendler** [nystudio107/craft3-imageoptimize#87]
I'm creating image sources similar to this in my templates with Imgix:
```twig
{% set fullImageSrc = craft.imageOptimize.createOptimizedImages(image, [{
  'width': 400,
  'useAspectRatio': true,
  'aspectRatioX': 1,
  'aspectRatioY': 1,
  'retinaSizes': ['1'],
  'quality': 65,
  'format': 'auto' }]
).src() %}
```

If `format` is set to `auto` the crop doesn't work. If I change that to `jpg` the crop works.

**Comment by khalwat** [comment]
If you want the format to be auto, just set `format` to `null` (or omit it entirely).
