### ISSUE TITLE
craft.imageOptimize.createOptimizedImages only creates defaultImageVariant

### ISSUE THREAD

**Issue by janson** [nystudio107/craft3-imageoptimize#88]
I've tried various things, to no avail—cleared cached, reindexed assets, removed all extraneous steps/logic in the twig, deleted transforms to the file system... but no matter what I can only render named OptimizedImages fields... not dynamic transforms. Any pointers or ideas?

config/image-optimize.php:
```
  'defaultVariants'            => [
    [
      'width'          => 1200,
      'useAspectRatio' => false,
      'aspectRatioX'   => 1.0,
      'aspectRatioY'   => 1.0,
      'retinaSizes'    => ['1'],
      'quality'        => 82,
      'format'         => 'jpg',
    ],
  ],
```

template.twig:
```
{% set optimzedImages = craft.imageOptimize.createOptimizedImages(
    someAsset,
    [
        {
            'width': 740,
            'useAspectRatio': true,
            'aspectRatioX': 1.0,
            'aspectRatioY': 0.4375,
            'retinaSizes': ['1'],
            'quality': 82,
            'format': 'jpg',
        },
    ]
) %}
<img srcset="{{ optimizedImages.srcset() }}"
         sizes="100vw" />
```

**expected HTML**:
```
<img srcset="/_740x324_crop_center-center_line/someAsset.jpg 740w" sizes="100vw">
```

**observed HTML**:
```
<img srcset="/_1200x1200_crop_center-center_line/someAsset.jpg 1200w" sizes="100vw">
```

Edit:
- Craft CMS 3.0.9
- craft-imageoptimize 1.4.33

**Comment by khalwat** [comment]
What is `img` and `img.image` in this example?

**Comment by janson** [comment]
Ah, yes—`img` is a matrix block and `img.image` is an Asset Field for the block.

**Comment by khalwat** [comment]
So are we all set then?

**Comment by janson** [comment]
No? I'll revise my initial issue for greater clarity. But in summary:

I expect, given that `createOptmizedImages` is called with a specific rendition, that it outputs a 740x324 image. 

Instead, it outputs a 1200x1200 image as specified in the _default_ config.

**Comment by khalwat** [comment]
Hmmmmm, that is very strange. I'll set up a test environment for it here.

**Comment by khalwat** [comment]
Now I know what I couldn't replicate this... I've been trying to... you have a typo in `optimzedImages` -- it should be `optimizedImages`

If you have `devMode` on in local dev, you'll see these "hidden" errors:

![google chromescreensnapz1254](https://user-images.githubusercontent.com/7570798/42526068-d1e8599a-8442-11e8-8aec-7d1722731b2f.png)

Once I fix the typo, I get the expected result:

```html
<img srcset="//craft3.test/img/blog/_740x323_crop_center-center_82_line/beauty_171213_181422.jpg 740w" sizes="100vw">
```

**Comment by khalwat** [comment]
This article also might be helpful to you @janson https://nystudio107.com/blog/handling-errors-gracefully-in-craft-cms

**Comment by janson** [comment]
Sorry, no, the typo was due to my hand-editing of the issue's twig purely for clarity's sake. The original code, without typo, still exhibited the behavior of the default srcset being generated instead of the provided rendition:

```
{% set rendition = {
    'width': 740,
    'useAspectRatio': true,
    'aspectRatioX': 1.0,
    'aspectRatioY': 0.4375,
    'retinaSizes': ['1'],
    'quality': 82,
    'format': 'auto'
} %}
{% set optimized = craft.imageOptimize.createOptimizedImages(img.image.one(),[rendition],true) %}
<img src="{{ optimized.placeholderImage() }}" srcset="{{ optimized.srcset() }}" sizes="100vw" />
```
Sure, defensive coding is helpful—but doesn't catch example pseudo-code dropped into GH issue editor. If I've time, I'll pull together an example Craft instance to try and isolate the observed behavior.

**Comment by khalwat** [comment]
Sure, let me know if you still find issues with it. I was able to use your code, with the successful result.
