### ISSUE TITLE
Placeholder Silhouette

### ISSUE THREAD

**Issue by MGxpwr** [nystudio107/craft3-imageoptimize#89]
I'm having this idea: wouldn't it be awesome to make the placeholder silhouette in the most dominant color of the image instead of grey? Just a thought. What do you think?

**Comment by khalwat** [comment]
Yep, that's definitely doable, and I think I played around with it at some point too.

I ended up going with just a gray because it seemed a little more neutral, and you should be able to style the SVG with a little inline CSS and the dominant color from ImageOptimize!
