### ISSUE TITLE
Settings Screen - Duplicate Image Processors When Clicking Save

### ISSUE THREAD

**Issue by mikestecker** [nystudio107/craft3-imageoptimize#9]
After clicking the "Save" button in the top right of the settings view, each image processor displays twice. Uninstalling the plugin and reinstalling resolves the issue.

<img width="1214" alt="screenshot 2017-09-08 11 20 50" src="https://user-images.githubusercontent.com/407465/30225857-d325be10-9488-11e7-9492-2930b8919d70.png">

**Comment by khalwat** [comment]
Put in a hotfix, thanks!
