### ISSUE TITLE
Retina Image variant are creating funky assets when scaled up. 

### ISSUE THREAD

**Issue by DenisG0** [nystudio107/craft3-imageoptimize#90]
Hi, 
 When i am generating images,  instead of this:
![image](https://user-images.githubusercontent.com/25282106/42189467-56c1502c-7e26-11e8-837d-dab69fd2c8de.png)
It instead turns into:
![image](https://user-images.githubusercontent.com/25282106/42189495-762b6c68-7e26-11e8-8bc3-2e03fd0d0a62.png)
Are logos something that do not work? I notice this seems to happen alot more for images with negative space. When i turn off " Allow Up-Scaled Image Variants"  the problem is no longer there but the image srcset doesn't appear to contain retina images. Is there something i am doing wrong or missed?

**Comment by DenisG0** [comment]
From what i gathered i can not scale up pngs, and jpegs. I am better of uploading a dense retina image and scaling down my assets. Closing this issue.

**Comment by DenisG0** [comment]
I had hoped using a dense image i would be able generate the different optimized variations that i need for the website. However it looks like the quality dipped when i used the plugin. In some cases the image even has negative space filled with black. I made sure the width is set to the width of the image and tried turning of retina sizes as well to see if that helps but it does nothing.

**Comment by khalwat** [comment]
So what image driver are you using for PHP? Make sure Imagick (aka ImageMagick) is installed.

As for the quality issue, you can set the quality to be whatever you want it to be in the Optimize Images field. What do you currently have it set to?

As for the negative space filled with black, I think that gets back to the image driver question about.

**Comment by DenisG0** [comment]
I installed the image driver imagick into the system and also set the quality to maximum. 
This is the image through the plugin, set at 175w. 
![image](https://user-images.githubusercontent.com/25282106/42576780-273bfe8e-84f1-11e8-88bc-cc6390e03fb1.png)
This is the image without the plugin:
![image](https://user-images.githubusercontent.com/25282106/42576859-4f5e7bd0-84f1-11e8-9f75-67f6c17cfe4d.png)

**Comment by khalwat** [comment]
So if you're scaling the image _down_ to 175w, it's not going to look good scaled up to whatever dimensions you're displaying it as. The image you posted is much larger than 175w (the dimensions are 521w x 285h); that same image displayed at 175w looks like this:

![42576780-273bfe8e-84f1-11e8-88bc-cc6390e03fb1](https://user-images.githubusercontent.com/7570798/42600271-b8ef7d86-852f-11e8-8852-b5bb3fdf2f7f.png)

**Comment by khalwat** [comment]
Can you paste in your HTML/Twig code you're using to display these images?

**Comment by DenisG0** [comment]
So what you're saying is that because the natural size of the image is so big, its causing this issue? Would there be a way of protecting from this? 
Here is the code for displaying the image, 

>  <div class="pinch pillars collapsing ">
    {% set partners = block.clients.all() %}
    {% for partner in partners %}
    {% set optimizedImages = partner.optimizeimagesclientlogo %}
    <img class="pillar lazyload" 
          data-src="{{ optimizedImages.src() }}"
         data-srcset="{{ optimizedImages.srcset() }}" /> 
    {% endfor %}
  </div>

**Comment by khalwat** [comment]
Right @DenisG0 but you're also not passing in any `sizes` for the `srcset` to use. Check out this article on using `srcset`: 

https://cloudfour.com/thinks/responsive-images-101-part-5-sizes/
