### ISSUE TITLE
How to use in lightbox? (UIkit)

### ISSUE THREAD

**Issue by E2design** [nystudio107/craft3-imageoptimize#91]
How can I use the optimized image in the lightbox images?

In my code the first (static) image is a optimized image. But how can I integrate or bind the picture element to the href="" for all lightbox images

    <div uk-grid uk-lightbox="animation: slide; autoplay: 1;">
          {% for image in images.all() %}
          {% set optimizedImages = image.twhOptimizedImages %}
	      {% if loop.first %}
		<a class="uk-inline" href="{{ lightboxImage.url }}" data-alt="{% include '_includes/elements/photo-alt.html' %}">
	            <img src="{{ optimizedImages.placeholderBox() }}" width="1800" height="1200" alt="{% include '_includes/elements/photo-alt.html' %}" uk-cover uk-img="target: !.uk-slideshow-items">
		    <picture>
			        <source srcset="{{ optimizedImages.srcsetWebP() }}"
			                 sizes="100vw"
			                 type="image/webp" />
			        <img src="{{ optimizedImages.placeholderImage() }}"
			             srcset="{{ optimizedImages.srcset() }}"
			             sizes="100vw" />
		    </picture>
        	</a>
        	{% else %}
		    <a class="uk-inline" href="{{ image.url }}" data-alt="{% include '_includes/elements/photo-alt.html' %}"></a>
        	{% endif %}
    	{% endfor %}
	</div>

**Comment by khalwat** [comment]
So I'm really not sure how to answer the question, because it depends on what Lightbox JS you're using, but it should work just like any other image.

Can you be a bit more specific in what you're asking?

**Comment by khalwat** [comment]
Will re-open the ticket if you come back with more info
