### ISSUE TITLE
Image Processors not working but installed [sort of]

### ISSUE THREAD

**Issue by wihodges** [nystudio107/craft3-imageoptimize#92]
I believe this to be a specific issue with my valet and local environment, but thought I'd see if anybody has a fix. I have already installed the image processors via Brew, but for some reason they show as not installed via ImageOptimize settings page. 

<img width="557" alt="screenshot 2018-07-10 22 32 32" src="https://user-images.githubusercontent.com/286956/42549319-27e03536-8491-11e8-822b-7802e00b958a.png">

<img width="1030" alt="screenshot 2018-07-10 22 33 03" src="https://user-images.githubusercontent.com/286956/42549342-3d823ede-8491-11e8-99af-1d994c7ba7e8.png">

Craft is updated to latest 3.0.15
PHP 7.1
Valet & Hombrew
All requirements in Utilities/System Report Checked.

**Comment by khalwat** [comment]
So I'm going to guess that the paths to these packages installed by Homebrew are not the same as the paths listed in the `config.php` for ImageOptimize. You'll have to modify the paths to point to wherever Homebrew put them.

**Comment by jalendport** [comment]
@wihodges the paths to those tools should be `/usr/local/bin/xxx`, so you'll want to use something like this in your ImageOptimize `config.php`:

```
    'imageProcessors' => [
        'jpegoptim' => [
            'commandPath' => '/usr/local/bin/jpegoptim', // <- updated to correct path
			...
        ],
```

An easy way to test where those image processing tools are is to run `which xxx` in your terminal. So to find the location of `jpegoptim` for example, you could run `which jpegoptim` and it will give you the location of the `jpegoptim` binary (mine is installed in `/usr/local/bin/jpegoptim`; yours _should_ be too).

**Comment by khalwat** [comment]
Thank you @jalendport -- yep just edit the paths in the `config.php` and make sure you rename it `image-optimize.php` when you copy it to your `config/` folder, as per the instructions in the comments in that file.
