### ISSUE TITLE
Custom imgix parameters

### ISSUE THREAD

**Issue by limesquare-nl** [nystudio107/craft3-imageoptimize#93]
I want to create a transformation with custom imgix parameters. So i can add a [watermark](https://docs.imgix.com/apis/url/watermark)..
Can you add this to the createOptimizedImages function?

**Comment by khalwat** [comment]
I think this is something that probably should be added as a general "watermark" feature, voice your support here:

https://github.com/nystudio107/craft-imageoptimize/issues/26

**Comment by MikeMcChillin** [comment]
I'd also love to see this custom parameter feature added - but not for just the watermark. Imgix has a lot of additional features that don't seem accessible through this plugin. For example, I often find myself needing the stylize feature: https://docs.imgix.com/apis/rendering/stylize

Is it currently possible to pass through any custom imgix parameters?

**Comment by khalwat** [comment]
One of the design goals of the plugin is not to tie you to a particular service. The idea is if you decide to switch back to using Craft CMS to do the transforms, or you decide to spin up your own Serverless Sharp image transform lambda function, everything will continue to work with zero template changes.

If it's something that can be implemented as a standardized way across the board, I can do it. I probably will not be adding Imgix-specifc things, for the reason mentioned above, though.

I don't want you to be tied to any particular transform method/service.
