### ISSUE TITLE
Spoon plugin causes ImageOptimize field settings to disappear

### ISSUE THREAD

**Issue by BenParizek** [nystudio107/craft3-imageoptimize#94]
Screenshot: http://share.barrelstrength.co/10390c1z1N2D
Related Issue: https://github.com/angell-co/Spoon/issues/15

The ImageOptimize plugin uses matrix block classes in how it styles its settings pages:
https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/templates/_components/fields/OptimizedImages_settings.twig#L69

It seems the styles Spoon adds to the CP may conflict with these in some way. I haven't dug too deep so not sure if the primary issue is in Spoon or in ImageOptimize. Hopefully you folks can coordinate and find a common ground.

**Comment by khalwat** [comment]
I'm gonna blame Josh for this. I'm just re-using existing CSS styles ¯\_(ツ)_/¯
