### ISSUE TITLE
Transforms not created after uploading asset / saving entry

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-imageoptimize#95]
First of all; great plugin! 

But I am bumping into a weird work-flow issue: after I upload an asset (image) and save the entry, the transformations aren't created. I have to manually click on every asset so it opens the modal and click - save -. At this point it seems to be running and creating things.

Also, the first time it shows the error:  This is not an image that can be manipulated.  But, ignoring this and clicking the save button nevertheless runs the transformation process. 

Screencast; https://streamable.com/8j1lk

Also, there are no errors found in any logs and I've installed all required server tools;;

![screen shot 2018-08-10 at 10 34 17](https://user-images.githubusercontent.com/1286410/43947664-f89a344c-9c88-11e8-9774-e80db84b86dd.jpg)

Two questions: 

1) should I click save manually every time a want the transformations to be created?
2) What is the cause of the errror on initial load? 

EDIT; also there seems to be a process locked: optimizing images in images. Don't know if this is part of the plugin or Craft itself:

![screen shot 2018-08-10 at 10 54 02](https://user-images.githubusercontent.com/1286410/43948702-d479a086-9c8b-11e8-8a75-6c1eb3a68d91.jpg)

Running Craft CMS 3.0.19
PHP 7.0.30-0ubuntu0.16.04.1

Thanks!

**Comment by arifje** [comment]
Hm ok, just found out that this full queue is causing the issue, so this topic can be marked as closed.

**Comment by khalwat** [comment]
Glad you found a solution!
