### ISSUE TITLE
Error while upgrading a batch of versions

### ISSUE THREAD

**Issue by E2design** [nystudio107/craft3-imageoptimize#97]
I'm getting this error after trying to upgrade a batch of new versions of ImageOptimize. Because of the error I'm no longer able to log in to the back-end.

Updated Craft3 to 3.0.20
Trying to update (update all) imageoptimize 1.4.34 -> 1.4.37

![schermafdruk 2018-08-16 19 10 40](https://user-images.githubusercontent.com/5907530/44250940-cee5e600-a1f6-11e8-953c-a2195ffe8fc0.png)

[phperrors.log.zip](https://github.com/nystudio107/craft-imageoptimize/files/2296189/phperrors.log.zip)

**Comment by khalwat** [comment]
Looks to me like a Composer error -- it's saying the file isn't there. So I'd try re-installing the plugin.
